### PR TITLE
Respect naming convention for new geo tables

### LINKED ISSUE #5175: Fix workbench validation for `CollectionObjectType`
**Describe the bug**
From #5170: Workbench validation does not work when mappings involve CollectionObjectType

**To Reproduce**

1. Create a workbench dataset
2. Choose base table as CollectionObjectType or CollectionObject
3. Map a column to a relation with CollectionObjectType
4. Click validate
5. See error

**Expected behavior**
Workbench should be able to validate columns related to CollectionObjectType

**Screenshots**
From #5170:

https://github.com/user-attachments/assets/7f9f4b4c-1d41-46bd-b0e3-21506acb5ad9

### LINKED ISSUE #5192: Schema labels and configuration are not being respected with new tables
**Describe the bug**
Despite each field in the schema config being assigned a label and visibility status, the forms and queries do not respect field visibility, descriptions, or captions.

This is on a local copy similar to `geo_swiss_2024_08_05` on the test panel
 
**To Reproduce**

1. Customize the schema for `collectionobjectgroup` and `collectionobjectgroupjoin`
2. Go to the query builder (`/specify/query/new/collectionobjectgroup/`) or to the form (`/specify/view/collectionobjectgroup/new/`)
3. See that the custom visibility/labels/descriptions are not being respected

**Expected behavior**
It should work as it does across other tables.

**Screenshots**
image

See that a number of these fields are hidden and my custom schema names are not being respected (`isprimary` should be `Is Primary`).

**Crash Report**
System Information:
macOS, Arc
Git SHA: https://github.com/specify/specify7/commit/9f37028b2e20f10eb9972d50f4058790b3dcca9f

[Specify 7 System Information - 2024-08-05T17_13_03.215Z.txt](https://github.com/user-attachments/files/16500712/Specify.7.System.Information.-.2024-08-05T17_13_03.215Z.txt)

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #5175
Fixes #5192

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions
Verify this is fixed: 
https://github.com/specify/specify7/issues/5192
https://github.com/specify/specify7/issues/5175

### CODE REVIEW

**Comment by realVinayak** [comment]
@CarolineDenis could you resolve the import for tests?

**Review by realVinayak — APPROVED** [review]

**Review by sharadsw — APPROVED** [review]

**Review by combs-a — COMMENTED** [review]
Verify this is fixed: 
- [ ] https://github.com/specify/specify7/issues/5192
- [X] https://github.com/specify/specify7/issues/5175

Looks like it's fixed 5175, but I can't tell for 5192 since I wasn't able to recreate the issue on my end for edge. I had to refresh, but otherwise they were appearing just fine on both queries and forms

For 5175:
https://github.com/user-attachments/assets/1f7fa96f-b9d6-489a-ad02-06e21cfe73d1

**Review by lexiclevenger — CHANGES_REQUESTED** [review]
### Testing instructions
Verify this is fixed: 

- [ ] https://github.com/specify/specify7/issues/5192
- [x] https://github.com/specify/specify7/issues/5175

---
It seems like #5175 is fixed in this branch but #5192 is not:

#5175:
Screenshot 2024-08-14 at 1 22 26 PM

#5192:
Screenshot 2024-08-14 at 1 35 08 PM

**Review by alesan99 — APPROVED** [review]
### Testing instructions
Verify this is fixed: 
- [x] https://github.com/specify/specify7/issues/5192
- [x] https://github.com/specify/specify7/issues/5175

5175 is fixed, and after migrations 5192 is fixed for me too 👍

Validation:
chrome_FbLmSVYLQn

Schema Config changes:
chrome_8s2kCAO7Nf

**Review by combs-a — APPROVED** [review]
Was able to recreate the 5192 on database that ChadronTest2 was cloned from, ChadronTest, so the migrations should have fixed the issue 👍

**Pull request merged**
