### PR TITLE
Allow spaces in Lat Long boxes

### LINKED ISSUE #3354: Space characters cannot be typed in LatLonUI at the end
Our official documentation claims the following:

> The only characters that are allowed in the input field for coordinate fields are:
> 
> - A whitespace character (tab, space)
> - A digit
> - Any of the following: "'-.:ensw° (case-insensitive)

This was demonstrably true some time ago (and @maxxxxxdlp made changes to what was accepted the last time I tested it), but now spaces are not enterable at the end of the line.

https://user-images.githubusercontent.com/37256050/232167722-1323a8a2-8967-46c4-9c0d-5b1ebdb8e958.mov

In this video, I tried typing `30 30 30 N`, but I could only go back to add space characters.

https://sp7demofish.specifycloud.org/specify/view/locality/new/

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3354

### CODE REVIEW

**Review by maxxxxxdlp — CHANGES_REQUESTED** [review]

**Comment by CarolineDenis** [comment]
@maxxxxxdlp:
No problem, I can add the trimStart.

Regarding the useResourceValue function that accepts the new prop trim (a boolean), if we remove it, users will no longer be able to enter spaces in the lat long fields. The useResourceView function calls parseValue, which has a default argument of trim: true. If we don't set trim to false, the value will always be trimmed in line 50 of parseValue: trim ? value.trim() : value.

**Comment by maxxxxxdlp** [comment]
> @maxxxxxdlp: No problem, I can add the trimStart.
> 
> Regarding the useResourceValue function that accepts the new prop trim (a boolean), if we remove it, users will no longer be able to enter spaces in the lat long fields. The useResourceView function calls parseValue, which has a default argument of trim: true. If we don't set trim to false, the value will always be trimmed in line 50 of parseValue: trim ? value.trim() : value.

you are right. I am not sure why it still worked for me when I removed that

**Review by maxxxxxdlp — APPROVED** [review]

**Comment by chanulee1** [comment]
Is this ready for UI review?

**Review by chanulee1 — APPROVED** [review]
Looks good. Able to enter spaces at the end of a string in Lat Long boxes.

**Pull request merged**
