### PR TITLE
add support for new schema 2.10 tables. fixes #2381

### LINKED ISSUE #2381: New tables should be marked as dependent where appropriate
image

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/61085/?recordsetid=97

### PR DESCRIPTION
**Pull request by benanhalt**
fixes #2381

Makes new relationships "dependent" and adds a uniqueness business rule for determiners. Also updates tests for same.

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
image

I'm encountering an issue with Identifiers.

https://kufishnotests-testability.test.specifysystems.org/specify/view/agent/1097/

**Comment by benanhalt** [comment]
It looks like that instance on the test server is using the testability branch which doesn't have these changes. I can rebase this issue branch to be off of testability if you want.

**Review by grantfitzsimmons — APPROVED** [review]
Working fine on the correct branch. Thanks @benanhalt !

**Comment by grantfitzsimmons** [comment]
I do think we should merge this into `testability`

**Pull request merged**
