### PR TITLE
Bring hotfixes to production

### PR DESCRIPTION
**Pull request by grantfitzsimmons**
So far includes a fix to #5067 by @realVinayak 

> Moves the logic for concatenating syn's full names on the backend rather than the frontend. 
> 
> ### Checklist
> 
> - [x] Self-review the PR after opening it to make sure the changes look good
>       and self-explanatory (or properly documented)
> - [ ] Add automated tests
> - [x] Add relevant issue to release milestone
> 
> ### Testing instructions
> 
> **Synonyms**
> Same for https://github.com/specify/specify7/pull/4704.
> go to any tree
> hover over a node that has synonyms
> 
> **Tree stats**
> Same as in https://github.com/specify/specify7/pull/3613#issuecomment-1792814457
> 1. go to any tree node
> 2. tree stats should appear faster than they do in producton

Also verify timestamp is being saved properly

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
@realVinayak Can you resolve the branch conflicts?

**Comment by realVinayak** [comment]
what do you mean, can I not just force-push everything /s?

**Review by realVinayak — APPROVED** [review]

**Review by lexiclevenger — APPROVED** [review]
Looks good! The issues regarding both trees and timestampmodified are still fixed.

**Comment by realVinayak** [comment]
Can we merge this to production, and then possibly https://github.com/specify/specify7/pull/5036? I noticed tree counts take forever to load on jerusalem's geo database (but load quickly with tree stat changes)

**Pull request merged**
