### PR TITLE
Change icon of Update RSS Feed in User Tools

### LINKED ISSUE #4083: Change `RSS Icon` in User Tools from Cloud to RSS
In the User Tools section the RSS Feed icon is actually a cloud rather than the RSS icon. We're changing that. Especially since there already is a heroicon with the correct icon.
Screenshot 2023-10-06 at 2 24 51 PM
Screenshot 2023-10-06 at 2 24 36 PM

### PR DESCRIPTION
**Pull request by carlosmbe**
Fixes #4083. This PR Changes the Icon of Update RSS Feed in user tools from the Cloud to the RSS Icon.

### CODE REVIEW

**Review by maxxxxxdlp — APPROVED** [review]
👍

**Review by melton-jason — APPROVED** [review]
Nice PR! :partying_face: 
Now only need ux testing!

**Review by grantfitzsimmons — APPROVED** [review]
:+1: Looks good! I removed the cloud icon since it is no longer used.

**Comment by grantfitzsimmons** [comment]
@carlosmbe Can you update the documentation to match?

https://discourse.specifysoftware.org/t/user-tools-menu/536
and
https://discourse.specifysoftware.org/t/how-to-update-your-rss-feed/567
and
https://discourse.specifysoftware.org/t/dwca-data-exporting-in-specify-7/568

**Comment by carlosmbe** [comment]
@grantfitzsimmons All 3 links have had their documentation updated

**Comment by grantfitzsimmons** [comment]
> @grantfitzsimmons All 3 links have had their documentation updated

👏💯

Thank you!

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-2-release-announcement/1452/1

**Pull request merged**
