### PR TITLE
Move attachment gallery icon to the left of the slider

### LINKED ISSUE #4081: Move record attachment gallery view button in header
The paginator buttons should be on the far right of the dialog. Moving the gallery button to the other side is more consistent with the other areas. 

Screenshot 2023-10-06 at 1 05 00 PM

Reported by: @grantfitzsimmons

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4081

### CODE REVIEW

**Review by maxxxxxdlp — APPROVED** [review]
👍

**Review by bronwyncombs — CHANGES_REQUESTED** [review]
For forms with wide subviews, the gallery button shifts to the left side of the header. Can we have this right-aligned and grouped with the right set of buttons? 

**wide subview:**
Screenshot 2023-10-11 at 9 51 00 AM

---
these look good -

**icon dialog:**
Screenshot 2023-10-11 at 9 49 36 AM

**subview fewer colspan:**
Screenshot 2023-10-11 at 9 49 17 AM

**Review by carlosmbe — APPROVED** [review]
Two things: 

1. Following up on @bronwyncombs 's review. The Wide Subview has been fixed
2. Side Note, this was fixed in another branch but it was possible to click on the button when there is no attachments which led to an infinite loading progress bar.

Screenshot 2023-10-12 at 1 17 45 PM

**Comment by CarolineDenis** [comment]
Fixed in https://github.com/specify/specify7/pull/4105
(Used correct root branch)

**Pull request closed without merging**
