### PR TITLE
Enable close button only when changes saved, display close and cancel

### LINKED ISSUE #4746: Unsaved changes are retained in qcbx edit dialogs
**Describe the bug**

On a form, qcbx edit dialogs (pencil icon) retain changes that aren't saved. In some cases, Saving is then blocked upon attempting to revert to the original data 

> ^^ This exists in production

 

For Taxon specifically, I noticed that simply pasting the original text back in the field still results in a save block.

> ^^ This does not!! For `7.9.4`, we just need to address the save block upon trying to revert the data.

**To Reproduce**

1. Go to existing Collection Object
2. Click on pencil icon by taxon qcbx with data already entered
3. Remove text from required field in this dialog
4. Click cancel
5. Click pencil again
6. See invalid form, paste original name
7. See error with save block and message 

**Expected behavior**

Unsaved changes to a field should not be maintained i.e. if a field is emptied but not saved, the next time you open that record it should have the original data preserved

For `7.9.4`, restoring original data should validate the form again

**Screenshots**

**Example with Agent:**

https://github.com/specify/specify7/assets/135047322/d72eeae6-9b78-48fa-b7bd-8732d28c2b9e

**Example with Taxon:**

https://github.com/specify/specify7/assets/135047322/e79087b9-54f6-4426-ae44-630d154b84cd

VS Production: 

https://github.com/specify/specify7/assets/135047322/15c46327-6f87-415d-b6df-940b01d56c9e

**Crash Report**

[Specify 7 Crash Report - 2024-04-05T16_40_36.695Z.txt](https://github.com/specify/specify7/files/14887970/Specify.7.Crash.Report.-.2024-04-05T16_40_36.695Z.txt)

- `pripaleo` w/ testuser on Chrome
- `edge`

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4746

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Go to existing Collection Object
- Click on pencil icon by a qcbx with data already entered (i.e Cataloger) 
- Make a change in the Agent overlay dialog 
- Save
- Reopen the Agent dialog with the edit button 
- [ ] Verify the changes are present 
- Don't make any changes 
- [ ] Verify you can close the dialog and no message is being displayed 
-  Reopen the Agent dialog with the edit button 
- Make a change 
- Click Cancel 
- [ ] Verify a pop up dialog opens with a warning for unsaved changes 
- Click Cancel 
- [ ] Verify that you go back to the Agent overlay dialog  
- Click Cancel 
- The overlay dialog with unsaved warning opens 
- Click Leave btn 
- [ ] Verify that you are going back to the main form 
- Reload the page 
- [ ] Verify that you lost your changes in Agent edit form

### CODE REVIEW

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]
so you are no longer allowed to revert your changes if you don't want to save them?
(other than reloading the page - which is not intuitive, and would the user to lose unsaved changes they might have behind the dialog)

also, not being allowed to close a dialog is an accessibility issue - unclosable dialogs should be only used when dialog response is essential for app to continue (i.e like a crash report dialog) - otherwise all dialogs should be closable

**Comment by CarolineDenis** [comment]
> Should we instead rename the Close button to Cancel?
That could be good. 
So keep current production behavior but rename button? 
@maxpatiiuk @grantfitzsimmons

**Comment by grantfitzsimmons** [comment]
I don't want the "Close" button to be removed as the solution! I just want the close button to warn you there are unsaved changes before you can proceed with closing it, so either save or lose them.

There should always be a close button. I don't see a need to rename it "Cancel"

**Comment by CarolineDenis** [comment]
NOTES: 
- open record with pencil 
- make changes 
- click save => saves changes and close dialog 
- click cancel => open dialog to let user know there is unsaved changes (2 bans, 1 continue 1 cancel)
- click cancel, go back to overlay record dialog 
- click continue, go back to record and discard changes made in overlay record

**Comment by maxpatiiuk** [comment]
sounds good - Cancel or Close button labels are good
as long as dialog is closable and user isn't forced to save against their will (or delete their computer 🤡)  it's all good

@CarolineDenis we already have a dialog that shows up when you try to leave the page with unused changes - see if you can reuse that dialog

**Comment by CarolineDenis** [comment]
NOTES: 
After meeting with @grantfitzsimmons, 
- open record with pencil
- make changes
- click save => saves changes and close dialog
- click cancel => open dialog to let user know there is unsaved changes (2 btns, 1 leave - 1 cancel)
- click cancel, go back to overlay record dialog
- click continue, go back to record and keep changes without saving them (same behavior as in 9.3)
- a second phase where we 'erase' the changes in the overlay dialog when clicking leave will be done in the future in a new pr

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

- Go to existing Collection Object
- Click on pencil icon by a qcbx with data already entered (i.e Cataloger) 
- Make a change in the Agent overlay dialog 
- Save
- Reopen the Agent dialog with the edit button 
- [x] Verify the changes are present 
- Don't make any changes 
- [x] Verify you can close the dialog and no message is being displayed 
-  Reopen the Agent dialog with the edit button 
- Make a change 
- Click Cancel 
- [x] Verify a pop up dialog opens with a warning for unsaved changes 
- Click Cancel 
- [x] Verify that you go back to the Agent overlay dialog  
- Click Cancel 
- The overlay dialog with unsaved warning opens 
- Click Leave btn 
- [x] Verify that you are going back to the main form 
- Reload the page 
- [x] Verify that you lost your changes in Agent edit form 

This does not fix the original issue in #4746 with the taxon but it does work with cataloger. Is this an issue with this pr or does it have to do with the tree issues we've been having? 


https://github.com/specify/specify7/assets/150940840/810ca93e-4645-4b67-85fd-2d4e7575fefb

**Comment by CarolineDenis** [comment]
@emenslin, the issue with the parent taxon is another issue. Here you can test the fact that you have the warning dialog when you leave a pop up with unsaved changes

**Review by emenslin — APPROVED** [review]

**Review by lexiclevenger — APPROVED** [review]
- Go to existing Collection Object
- Click on pencil icon by a qcbx with data already entered (i.e Cataloger)
- Make a change in the Agent overlay dialog
- Save
- Reopen the Agent dialog with the edit button

- [x] -  Verify the changes are present

- Don't make any changes

- [x] -  Verify you can close the dialog and no message is being displayed

- Reopen the Agent dialog with the edit button
- Make a change
- Click Cancel

- [x] -  Verify a pop up dialog opens with a warning for unsaved changes

- Click Cancel
-  Verify that you go back to the Agent overlay dialog
- Click Cancel
- The overlay dialog with unsaved warning opens
- Click Leave btn

- [x] -  Verify that you are going back to the main form

- Reload the page

- [x] -  Verify that you lost your changes in Agent edit form

Looks good!

**Review by maxpatiiuk — APPROVED** [review]
love that it's such a small code change!

**Pull request merged**
