### PR TITLE
Display tooltip on top of combo boxes

### LINKED ISSUE #3401: Modern tooltip covering QCBX
**Reported By:** RBGE

> We have been finding that the position of the pop up for Query Combo Boxes which lists ‘Searched Fields’ is getting in the way of the dropdown:
>  
> image

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3401

### CODE REVIEW

**Review by maxxxxxdlp — APPROVED** [review]

**Review by carlosmbe — COMMENTED** [review]
Getting some strange behaviour on this branch  in `Coldfish` not replicable on 7.8.10
Observe video below
https://coldfish-issue-3401.test.specifysystems.org/specify/

1. Record Set being highlighted despite choosing data entry
2. Crash when entering a taxon


**On Normal Branch**
[Specify 7 Crash Report - 2023-05-04T21_17_00.084Z.txt](https://github.com/specify/specify7/files/11401647/Specify.7.Crash.Report.-.2023-05-04T21_17_00.084Z.txt)
[Specify 7 Crash Report - 2023-05-04T21_17_00.084Z (1).txt](https://github.com/specify/specify7/files/11401648/Specify.7.Crash.Report.-.2023-05-04T21_17_00.084Z.1.txt)



https://user-images.githubusercontent.com/53784701/236332202-3b07e775-e95a-426a-8691-800a15a112d9.mov

**On Normal 7.8.10**

https://user-images.githubusercontent.com/53784701/236332438-60429ae1-98f0-4531-a68c-c2d18f34a40f.mov

**Comment by CarolineDenis** [comment]
@carlosmbe these issues are related to the PR (https://github.com/specify/specify7/pull/3296)
@maxxxxxdlp do we want the side bar menu to be set on record set or do we want to keep data entry? 
For the error message, need to investigate

**Comment by maxxxxxdlp** [comment]
This branch did not touch anything other than query combo box tooltip. The crashes and other bugs are not related and are likely reproducable on production too (unless they have already been fixed on production and this branch is just behind).

> do we want the side bar menu to be set on record set or do we want to keep data entry?
Feel free to look into this. Can be fixed along with https://specifydev.slack.com/archives/D04ELKCBK39/p1676050644146859. But create a separate pull request for that

**Review by carlosmbe — APPROVED** [review]
Works fine.
Screenshot 2023-05-05 at 1 19 47 PM

**Pull request merged**
