### PR TITLE
New Header Heroicons

### LINKED ISSUE #4055: Update heroicons in various dialog headers
**Choose Collection:**
Screenshot 2023-09-29 at 10 35 10 AM
Add Heroicon: Archive

**Notifications:**
Screenshot 2023-09-29 at 10 37 01 AM
New Heroicon: Bell

**Search:**
Screenshot 2023-09-29 at 10 38 40 AM
New Heroicon: Search

**QCBX search:**
Screenshot 2023-09-29 at 10 47 40 AM
New Heroicon: Search

**Embedded Query Builder:**
Screenshot 2023-09-29 at 10 39 07 AM
New Heroicon: Document Search

### PR DESCRIPTION
**Pull request by carlosmbe**
Fixes #4055 

Adds and Changes the Header Icons for: Choose Collection, Embedded Query Builder, Query Combo Box, Simple Search, Notification Dialog

### CODE REVIEW

**Comment by carlosmbe** [comment]
To UX test, 

Go to the following sections and confirm that the new Heroicon is very pretty, aesthetic and is overall slaying. Original icons can be found in #4055 :


Choose Collection
Screenshot 2023-10-08 at 12 54 09 PM

Embedded Query Builder
Screenshot 2023-10-09 at 3 16 21 PM

Query Combo Box
Screenshot 2023-10-09 at 3 16 31 PM

Simple Search
Screenshot 2023-10-09 at 3 17 55 PM


Notification Dialog
Screenshot 2023-10-09 at 3 17 49 PM

**Review by CarolineDenis — APPROVED** [review]

**Review by melton-jason — APPROVED** [review]
Nice work! :partying_face:

**Review by maxxxxxdlp — APPROVED** [review]
💯

**Review by grantfitzsimmons — APPROVED** [review]

**Comment by melton-jason** [comment]
Can this be merged?

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-2-release-announcement/1452/1

**Pull request merged**
