### PR TITLE
New library for XML<-->JSON two way sync / xml-editor

### LINKED ISSUE #515: Add Gifts Without Preps
Michigan requested ability to add gifts without preps

### LINKED ISSUE #805: Need to add a way for users to be able to see rank specific information on forms
Edinburgh has mentioned they need to have a way to see the family # and genus # for their determinations, ideally on the determination form.  The issue is there is no easy way to do that because there may be ranks in between family and genus or genus and species, so even in a query, you couldn't reliably get back the number for all objects because it goes based on parent or parent of parent, rather than rank, so if the parent is subgenus rather than genus, you don't get the number.  And currently, there is no way to add a field that shows taxon information for ranks other than the lowest determined node.

### LINKED ISSUE #1659: [a11y] Trying to edit a picklist should open a new tab rather than exit the current instance
Editing the picklist should be done in a new tab so I don't have to lose my progress when modifying the schema.

image

Can be circumvented with a middle-click or open in new tab. Should be default behavior

### LINKED ISSUE #1977: Bust cached app resource on changes
If a user edited an app resource, need to tell the browser to bust the cached app resource.

If this is done on the front-end, it can be done for the current user only. If it is done on the back-end (though `ETag` or some other solution), this would clear the cache for all users

---

From @grantfitzsimmons:

> When updating the schema configuration, it automatically clears your cache. 
>
> The same behavior should happen when updating a views file! Bonus points if it can also preserve the current URL.

### LINKED ISSUE #2955: Clicking and holding on the attachment size slider leads to an infinite loop
https://user-images.githubusercontent.com/37256050/217329319-e3c3c581-4507-44e2-b51b-b58132935716.mp4

`Firefox`

### LINKED ISSUE #3170: Aggregator Editor: Error upon login
Getting this error as soon as I log in (`xml-editor`). Does not happen on `edge`.

image

[Specify 7 Crash Report - 2023-03-14T14_40_38.389Z.txt](https://github.com/specify/specify7/files/10969946/Specify.7.Crash.Report.-.2023-03-14T14_40_38.389Z.txt)

### LINKED ISSUE #3171: Add a way to always use query builder for query combo box search
Add a way to always use query builder for query combo box search instead of using Specify 6's search dialogs

Edit:
added a Form -> Query Combo Box - >Always use Query Builder prop to disable search dialogs entirely as their usefulness is questionable.

See also #3173

### LINKED ISSUE #3173: Stop using "DialogDefs" app resource
To break away from sp6

It was only used by sp7 to get the search view name.

For every table except for GeologicTimePeriod, the search view name is `<tableName>Search`.

Thus, not need for an app resource.

If users wish to customize this, added a `searchView` prop to the `initialize=""` attribute of the query combo box - see docs

Also added a Form -> Query Combo Box - >Always use Query Builder prop to disable search dialogs entirely as their usefulness is questionable.

### LINKED ISSUE #3176: Add UI for editing WebLinks
- [x] Add UI for editing WebLinks
- [x] Allow using relationships in web links
- [x] Allow editing WebLinks that are not scoped to a table
- [x] Allow using formatters in web links
- [x] Add support for "prompt" fields

### LINKED ISSUE #3194: `xml-editor`: Formatters are deleted when using the visual editor
To clarify, making **any** change and saving results in this issue.

## **Before the edit made using the visual editor:**

```xml
    <format
        name="Address"
        title="Address"
        class="edu.ku.brc.specify.datamodel.Address"
        default="true"
        >
        <switch single="true">
            <fields>
                <field>address</field>
                <field sep=" ">address2</field>
                <field sep=", ">city</field>
                <field sep=", ">state</field>
                <field sep=" ">postalCode</field>
            </fields>
        </switch>
    </format>
```

image

## **After the edit made using the visual editor:**

```xml
	<format name="Address" title="Address" class="edu.ku.brc.specify.datamodel.Address" default="true"/>
```

image

It completely deleted the fields and switch statement.

---

[BeforeAndAfter.zip](https://github.com/specify/specify7/files/10993954/BeforeAndAfter.zip)

### PR DESCRIPTION
**Pull request by maxpatiiuk**
EDIT:
Because this PR is getting long, I created a milestone to track remaining issues: https://github.com/specify/specify7/milestone/49
If you discover an new issue, please add it to that milestone

---

Begins fixing https://github.com/specify/specify7/issues/1156
Begins fixing https://github.com/specify/specify7/issues/884
Fixes https://github.com/specify/specify7/issues/1961

Create a library that parses XML into JSON, and in the process validates it and makes it type-safe. In addition, on any changes to JSON, the original XML is automatically modified to reflect the changes. At the same time, unsupported attributes, unsupported child types, and comments are preserved in the original XML.

Then, use this library to implement UI for edting Data Object Formatters and Aggergators.
This paves the way for adding UIs for all other XML resources, including form definitions

### Formatters

Open `DataObjFormatters` app resource (if there are multiple in the database, open any of them - you can easily find all such files by disabling all but `Record Formatters` in the app resource filters).
If there is a syntax error in XML, and you go to "Visual Editor" tab, it should tell you what the error is.
Otherwise:
- Before making any edits, download the XML file. Test viewing/creating/deleting formatters/aggregators. After making the edits, download the XML file again. Reformat both files (i.e, using a tool like https://www.freeformatter.com/xml-formatter.html#before-output). Then, compare the files (i.e, using a tool like https://www.diffchecker.com/text-compare/). Make sure that the XML file was edited in a way you would expect (it should reflect the edits you made in the UI + if there were some required attributes missing, they should be added).
- After making edits in sp7, try making edits in sp6 (check sp6 can still read the formatters). Then, open it again in sp7 to see if things still work.
- On any edits, the preview section of the editor should update. You should also be able to select custom elements for preview (both in formatter and aggregator editors)
- Try making more than one formatter/aggregator a default - it should automatically unset "Is Default" from the other formatter
- Test putting comments in the XML file (or commenting out some nodes) and making edits - the comments should be preserved in the XML. Similarly, try adding unknown arguments to elements (i.e `abc="test"`) or unknown elements (`<test ><a /></test>`) - they should all be preserved upon edits
- Test opening/closing full-screen mode. Test using back/forward browser buttons
- The `CollectingEventDetail` formatter in the `CollectingEvent` table should not be fully editable - test that an error message is displayed (it's not editable in sp6 either - it's yet another sp6 special hacky thing). There are about default 4 formatters like this - just testing this one is good enough
- If you try to edit `DataObjFormatters` app resource that is from a different collection than the one you are in right now, a warning should be displayed. The warning should look good both in light mode and dark mode
- Try out the editor with a user that does not have edit access - everything should still work, but be read-only
- Try breaking the XML (but without the syntax errors). Examples: replace the file with a single `<text />` node. remove `class=""` and other important attributes from formatters. Make typos in field names and table names - the editor should handle ALL of these cases the best it can. If you open the console, there should be human-friendly warnings and errors about all the errors in the XML file - those errors will be displayed in the UI in the future
- Should be able to open the aggregator/formatter editor from inside of Schema Config
  - Note, for now, you can only open the editor in a new tab (right-click on the `+` or pencil and "Open in new tab"). Once `agent-merging` is merged (it has some code changes that are necessary here), then you can just click on the `+`, and it will open an editor in a dialog.
- Fixes #3170
- Fixes #3176
- Fixes https://github.com/specify/specify7/issues/3185
- Fixes #3194
- Fixes #1977

### General testing

A lot of code refactoring and bug fixing was done as part of this pull request.

- Do general testing of everything
  - With focus on Record Formatters, Aggregators, Field Formatters, Web Links, TypeSearches (used in query combo boxes), Search Dialog definitions and the Form System (XML parsing).
- Do complete testing of the WorkBench editor
- Fixes #2955
- Fixes #515
- Fixes #805
- Fixes #1659
- Fixes #3171.  Fixes #3173

### CODE REVIEW

**Review by chanulee1 — CHANGES_REQUESTED** [review]
See issues #3070, #3096, #3097, #3098, #3122, #3137, #3138, #3142, #3145, #3146.

**Comment by maxxxxxdlp** [comment]
Please also do complete testing of workbench editor as it's undergone big code refactor on this branch

**Comment by maxxxxxdlp** [comment]
Fixed all except for #3146 - which is waiting on agent merging to be merged

**Comment by maxxxxxdlp** [comment]
Fixes #1659 - please test

**Comment by maxxxxxdlp** [comment]
Fixes #3170
Fixes #3176

**Comment by maxxxxxdlp** [comment]
Fixes #3184
Fixes #3182
Fixes #3179
Fixes #3178

**Comment by maxxxxxdlp** [comment]
Added a way to edit XML resources as JSON (see the new `JSON editor` tab)

(old XML:)

Screenshot 2023-03-15 at 21 36 31

(nice JSON:)

Screenshot 2023-03-15 at 21 36 34

Any changes to JSON are be applied to XML right away.

Feel free to use this for general testing of the JSON<-->XML alongside the visual editor - but the logic for converting between the formats is the same as what's used behind the scenes by the visual editor. It might just be quicker/easier to test extreme cases by editing JSON (plus, you can copy+paste easily)

**Comment by maxxxxxdlp** [comment]
Added live XML validation:

https://user-images.githubusercontent.com/40512816/225801416-ebed11b1-e5f9-4025-a29e-797b407d636e.mp4

As soon as forms are refactored to use the syncer library, #884 will be fixed

**Comment by maxxxxxdlp** [comment]
Fixes #3185
Fixes #3194

**Comment by maxxxxxdlp** [comment]
Fixes #3187
Fixes #3188
Fixes #3171
Fixes #3191

**Comment by maxxxxxdlp** [comment]
Fixes #3234
Fixes #3266
Fixes #3186

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons @chanulee1 
Since this pull request has grown to be way way too large, I have created a milestone to keep track of all the issues related to this branch - https://github.com/specify/specify7/milestone/49
I added all existing issues to that milestone. Going forward, for any new issues for things related to the `xml-editor` branch, please add them to that milestone.

**Comment by maxxxxxdlp** [comment]
@chanulee1 All of the bugs in the https://github.com/specify/specify7/milestone/49 milestone are now fixed (with exception of https://github.com/specify/specify7/issues/3192 - that requires merging with agent merging branch - will try to do that next week)

Feel free to go over all fixed bugs to verify the fixes and do more testing (and not just testing of newly added features, but also general testing)

**Comment by CarolineDenis** [comment]
NOTES AFTER 1st MERGE: 
**Files that have NOT been merged (accept current changes)**
- lib/components/DataModel/__tests__/businessRules.test.ts
- lib/components/DataModel/businessRuleDefs.ts
- lib/components/DataModel/businessRules.ts
- lib/components/DataModel/schema.ts
- lib/components/DataModel/uniquness_rules.json
- lib/components/DataModel/resourceApi.js
- lib/components/Statistics/hooks.tsx
- lib/components/Merging/autoMerge.ts
- lib/components/Merging/CompareSubView.tsx
- lib/components/Merging/index.tsx
- lib/components/Forms/dataObjFormatters.ts

**Files that need double checks**
- lib/utils/ajax/throttledPromise.ts
- lib/components/Security/User.tsx
- lib/components/Leaflet/layers.ts
- lib/components/Merging/Compare.tsx
- lib/components/Forms/Save.tsx

**File with errors**
-  lib/components/FormCells/index.tsx

**Extra notes**
- need to clean the localized strings that are unused 
- need to add back the issue https://github.com/specify/specify7/issues/3768

**Comment by grantfitzsimmons** [comment]
> * need to add back the issue [Add Clone, Add, and Save to the fullscreen resource editor #3768](https://github.com/specify/specify7/issues/3768)

Yes, please! That has been a huge quality of life increase. It's especially useful on this branch and I noticed it was gone today

**Pull request merged**
