### PR TITLE
Remove front-end pick list size limit checks

### LINKED ISSUE #3482: Remove size limit enforcement for pick lists
Today, the size limit had a bug related to it, and that refocused our attention on whether the size limit is useful at all. The limit should just be removed if it only serves as a vessel for bugs!

from @maxxxxxdlp:
> Size limit was useful in sp6 as pick list items were added automatically
> not useful in sp7 at all
> and like Ben said, it's an "antifeature"

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
It was buggy (see #3482) and didn't serve a purpose anymore. Also, back-end already removed these checks.

Fixes #3482

### CODE REVIEW

**Comment by maxxxxxdlp** [comment]
Note, there is still one place where size limit is used. See https://github.com/specify/specify7/issues/2136#issuecomment-1545897213

**Comment by chanulee1** [comment]
How do I test this?

**Comment by maxxxxxdlp** [comment]
1. Create a pick list with size limit of 5
2. Make pick list not read only
3. Add 6 items to the pick list using the pick list form
4. Add the pick list field to the form
5. In the pick list field, enter a value that does not exist and see that the "Add" option is available
6. Click on "Add", save changes, and next time you use the field, the newly added value should be visible among pick list items

**Review by carlosmbe — APPROVED** [review]
Based on the test left in the comment. It works from a UX Pov

**Review by CarolineDenis — APPROVED** [review]

**Pull request merged**
