### PR TITLE
Add tool to remove unmapped lines

### LINKED ISSUE #1732: Delete row in Workbench mapping when not matched to a spreadsheet column
Reported by edinburgh
When creating a workbench mapping from scratch, there is no way to entirely remove a line added.  You can remove the mapping by clicking the x but it doesn't remove the line, which can quickly lead to clutter.
It would be nice if when a line represents a blank space rather than a spreadsheet column, if the line would disappear when you click the x, so where the line then says "New Column x" it would just get deleted.
image

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #1732 

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Open WB 
- Create new mapping 
- Add rows
- Map some rows and leave some unmapped 
- Click on the bottom of the screen the tool 'clear unmaped' 
- [ ] Verify that all unmapped lines have been removed

### CODE REVIEW

**Comment by CarolineDenis** [comment]
@maxpatiiuk , 

Is this what you had in mind?

**Review by maxpatiiuk — APPROVED** [review]
Don't think this "feature" is needed or useful IMHO, but the code looks good.

The empty mapping lines don't clutter up the dataset since we remove all unmapped newly added "New Column" lines when you save the mapping.

**Review by pashiav — APPROVED** [review]
### Testing instructions

- Open WB 
- Create new mapping 
- Add rows
- Map some rows and leave some unmapped 
- Click on the bottom of the screen the tool 'clear unmaped' 
- [X] Verify that all unmapped lines have been removed 
---

Looks great!!

https://github.com/user-attachments/assets/a8b21f2a-4526-449c-a5a8-49a04a6267e9

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

- Open WB 
- Create new mapping 
- Add rows
- Map some rows and leave some unmapped 
- Click on the bottom of the screen the tool 'clear unmaped' 
- [ ] Verify that all unmapped lines have been removed 

Only clears mappings that are completely unmapped, does not clear mappings even if they are partially unmapped 

https://github.com/user-attachments/assets/ea2b5562-3ee3-4e48-b83b-f420d00e59e2



https://github.com/user-attachments/assets/deace75c-4a3b-421c-974c-854d24a8fc33

**Review by sharadsw — APPROVED** [review]

**Comment by emenslin** [comment]
Even though this button should only clear the fully unmapped columns I have some concerns about the button itself. I feel like having a 'Clear Mappings' button and a 'Clear unmapped' button could be very confusing even if they are in different places. I think at the very least this button should be renamed, maybe something like 'remove empty columns' to make it more obvious what it does and to differentiate it from the 'clear mappings' button. I feel like workbench can already be pretty confusing so having two buttons that have very similar names but do very different things could be even more confusing.

**Comment by CarolineDenis** [comment]
@alesan99 
I like the suggestion: disabled for imports

**Comment by bronwyncombs** [comment]
I agree that "clear unmapped" would create confusion with the "clear mappings" button also in the UI. 

I also agree that "column" is a more consistent term for the UI but I think the button should read `Delete Unmapped` since "Delete Unmapped Columns" is a bit long. "Delete" and "Remove" are rather interchangeable, but Delete is a bit of a shorter word with a more concise meaning/easier to juxtapose with "Clear" in the "Clear Mappings" button.  

I also like the idea of the trashcan icon when a row is eligible for deletion, however, I understand this may be out of the scope of this PR.

**Comment by CarolineDenis** [comment]
@emenslin @alesan99 
String changed and button remove when columns are saved or dataset comes from upload

**Review by emenslin — APPROVED** [review]
### Testing instructions

- Open WB 
- Create new mapping 
- Add rows
- Map some rows and leave some unmapped 
- Click on the bottom of the screen the tool 'clear unmaped' 
- [x] Verify that all unmapped lines have been removed

**Review by alesan99 — APPROVED** [review]
### Testing instructions

- Open WB 
- Create new mapping 
- Add rows
- Map some rows and leave some unmapped 
- Click on the bottom of the screen the tool 'clear unmaped' 
- [x] Verify that all unmapped lines have been removed 

I can't delete imported columns anymore and the new wording is clear👍👍👍

**Pull request merged**
