### PR TITLE
Fix QCBX's not working on relationship search fields

### LINKED ISSUE #2014: Query Comboboxes no longer respecting criteria set in query combobox editor
Discovered by Calvert Marine Museum (hosted by us in Cloud)

They reported that their paleo context query combobox was no longer searching for paleo context records based on lithostrat.fullName, which they were able to do a few weeks ago.

I checked their database in 7.6.1 and 7.7 and confirmed that in 7.6.1, they could search on the term "calvert" and results would populate in the drop down list, but in 7.7, no results were returned.

https://user-images.githubusercontent.com/12532430/185995209-624771d9-6d1d-4cd8-a9f4-2b284231d7ef.mp4

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #2014, hopefully for good

To test:
Besides testing that that bug is fixed, please also do:
1. Comprehensive testing for query combo box
2. Very light testing for a workbench, workbench mapper, query builder and 2-3 big forms (just check that they open and there are no unexpected errors in the console)

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
image

Works fine on `edge`, not on `issue-2014-2`
https://calvert-issue-2014-2.test.specifysystems.org/specify/workbench/3/

**Comment by maxxxxxdlp** [comment]
It was checking for your permissions to the `CollectingEventTreeDef` table. Apparently, you don't have access to that table [🤷](https://emojipedia.org/person-shrugging/)

**Comment by grantfitzsimmons** [comment]
> It was checking for your permissions to the `CollectingEventTreeDef` table. Apparently, you don't have access to that table 🤷

image

**Comment by maxxxxxdlp** [comment]
Fixed. Please do light general testing again

**Comment by grantfitzsimmons** [comment]
image

Still can be very slow but the intended functionality is great!

**Comment by maxxxxxdlp** [comment]
Slow because it is returning almost a thousand records. Why do they need so many duplicates?

**Comment by grantfitzsimmons** [comment]
From what I can tell, this issue looks to be resolved!

**Comment by maxxxxxdlp** [comment]
Awesome. Please do general testing on this branch a bit because it changed some critical code

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/192340400-21675d13-8da3-46be-8109-2ca1747249a1.mov

QCBX behavior is a little unexpected. I would expect the text I enter to persist after the options load, but that is not the case. Is this a separate issue or does this need to be resolved in this issue?

**Comment by maxxxxxdlp** [comment]
> Screen.Recording.2022-09-26.at.12.19.23.PM.mov 
> QCBX behavior is a little unexpected. I would expect the text I enter to persist after the options load, but that is not the case. Is this a separate issue or does this need to be resolved in this issue?

This is not independent behavior. Unfortunately, I am unable to replicate it

https://calvert-issue-2014-2.test.specifysystems.org/specify/view/collectionobject/new/
User: spadmin
Collection: Vertebrates
Tried in Chrome and Safari on macOS

Steps:
1. Open CO form
2. Add new Determination
3. Start typing `Asa` into the field
4. Search results load, `Asa` is still in the search field

Same behavior even if mouse is hovering over the items

@grantfitzsimmons could you try to replicate again? Can you give more detailed steps? What browser/user are you using?

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp 

You can see my keystrokes on screen in this recording:

https://user-images.githubusercontent.com/37256050/192413450-dcaa5790-3b2e-4d71-86c1-de212fd6917d.mov

https://calvert-issue-2014-2.test.specifysystems.org/specify/view/collectionobject/new/
User: spadmin
Collection: Vertebrates
Tried in Chrome on macOS

I have a theory that it has something to do with whether the assigned result is present in the list that is returned, but I'm not sure. I can't recreate every time but its clear this behavior is not functioning exactly as I would expect

**Comment by maxxxxxdlp** [comment]
Ah, that bug has already been fixed in a separate PR - https://github.com/specify/specify7/pull/2203
Please test it so that we can get it merged!

**Review by grantfitzsimmons — APPROVED** [review]

**Pull request merged**
