### PR TITLE
Error rendering form component for collection information

### PR DESCRIPTION
**Pull request by NHMD**
When entering a new collection object (view: /specify/view/collectionobject/new/), the form component for adding collecting information didn´t render due to an error.
Maybe this is related to Issue #27

### CODE REVIEW

**Comment by benanhalt** [comment]
Can you send me the XML of the form that is causing this error? The easiest way is just to open the view URL in a browser and copy and paste the response. E.g. http://demo7.specifysoftware.org/context/view.json?name=CollectingEvent

**Comment by NHMD** [comment]
Hi Ben,

I think the issue origins from the searchfield-attribute in this line in typesearch_def.xml:

<typesearch tableid="32"  name="PaleoContext"           searchfield="paleoContextName,cs.fullName,ls.fullName" displaycols="paleoContextName,cs.fullName,cse.fullName,ls.fullName" format="%s, %s, %s, %s"
        dataobjformatter="PaleoContext”>


Below is the response of http://127.0.0.1:8000/context/view.json?name=CollectingEventSub


{"viewdefs": {"CollectingEventSub": "<viewdef class=\"edu.ku.brc.specify.datamodel.CollectingEvent\" gettable=\"edu.ku.brc.af.ui.forms.DataGetterForObj\" name=\"CollectingEventSub\" settable=\"edu.ku.brc.af.ui.forms.DataSetterForObj\" type=\"form\">\n            <desc>Collecting Event</desc>\n\n            <columnDef>100px,2px,210px,5px,75px,2px,210px,5px,90px,2px,126px,0px,p:g</columnDef>\n            <columnDef os=\"lnx\">115px,2px,210px,5px,105px,2px,210px,5px,125px,2px,136px,0px,p:g</columnDef>\n            <columnDef os=\"mac\">130px,2px,260px,5px,85px,2px,260px,5px,115px,2px,166px,0px,p:g</columnDef>\n            <columnDef os=\"exp\">p,2px,p:g,5px:g,p,2px,p:g,5px:g,p,2px,p:g(2),0px</columnDef>\n            <rowDef auto=\"true\" cell=\"p\" sep=\"2px\" />\n            \n            <rows>\n                <row>\n                    <cell labelfor=\"5\" type=\"label\" />\n                    <cell id=\"5\" name=\"stationFieldNumber\" type=\"field\" uitype=\"text\" />\n                    <cell labelfor=\"3\" type=\"label\" />\n                    <cell id=\"3\" name=\"method\" type=\"field\" uitype=\"combobox\" />\n                    <cell label=\"\" type=\"label\" />\n                    <cell id=\"1\" initialize=\"align=right;btn=true;icon=CollectingEventAttachment\" name=\"collectingEventAttachments\" type=\"subview\" viewname=\"ObjectAttachment\" />\n                </row>\n                <row>\n                    <cell labelfor=\"7\" type=\"label\" />\n                    <cell id=\"7\" initialize=\"name=PartialDateUI;df=startDate;tp=startDatePrecision\" name=\"this\" type=\"field\" uifieldformatter=\"Date\" uitype=\"plugin\" />\n                    <cell labelfor=\"8\" type=\"label\" />\n                    <cell id=\"8\" initialize=\"name=PartialDateUI;df=endDate;tp=endDatePrecision\" name=\"this\" type=\"field\" uifieldformatter=\"Date\" uitype=\"plugin\" />\n                    <cell labelfor=\"13\" type=\"label\" />\n                    <cell colspan=\"2\" id=\"13\" name=\"verbatimDate\" type=\"field\" uitype=\"text\" />   \n                </row>\n                <row>\n                    <cell labelfor=\"pcsh\" type=\"label\" />\n                    <cell colspan=\"10\" id=\"pcsh\" initialize=\"name=PaleoContext\" name=\"paleoContext\" type=\"field\" uitype=\"querycbx\" />\n                </row> \n                <row>\n                    <cell labelfor=\"4\" type=\"label\" />\n                    <cell colspan=\"10\" id=\"4\" initialize=\"name=Locality;title=Locality;clonebtn=true\" name=\"locality\" type=\"field\" uitype=\"querycbx\" /> \n                </row>\n                <row>\n                    <cell labelfor=\"6\" type=\"label\" />\n                    <cell colspan=\"10\" id=\"6\" name=\"remarks\" rows=\"2\" type=\"field\" uitype=\"textareabrief\" />\n                </row>\n                <row>\n                    <cell colspan=\"12\" id=\"12\" name=\"collectors\" rows=\"3\" type=\"subview\" viewname=\"Collectors\" />\n                </row>\n            </rows>\n        </viewdef>\n\n        "}, "altviews": {"CollectingEventSub Edit": {"mode": "edit", "name": "CollectingEventSub Edit", "viewdef": "CollectingEventSub"}, "CollectingEventSub View": {"default": "true", "mode": "view", "name": "CollectingEventSub View", "viewdef": "CollectingEventSub"}}, "name": "CollectingEventSub", "viewsetLevel": "UserType", "busrules": "edu.ku.brc.specify.datamodel.busrules.CollectingEventBusRules", "viewsetName": "Vertpaleo Views", "viewsetSource": "disk", "class": "edu.ku.brc.specify.datamodel.CollectingEvent", "resourcelabels": "false”}


Best,

Thomas Stjernegaard

On 02 Feb 2015, at 19:21, Ben Anhalt <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you send me the XML of the form that is causing this error? The easiest way is just to open the view URL in a browser and copy and paste the response. E.g. http://demo7.specifysoftware.org/context/view.json?name=CollectingEvent

**Comment by benanhalt** [comment]
Hi Thomas,

You are correct. The problem stems from that typesearch_def.xml which controls the query combo box element on forms. I think the ability for the combo box to query multiple fields (separated by columns) is a new addition in Specify 6. In Specify 7 the query combo box code is in querycbx.js and will need to be updated to also support the multiple search fields. Let me investigate it a little more, and I will get back to you.

Thanks,

Ben

**Comment by benanhalt** [comment]
I created a branch that should fix this problem, I think:

https://github.com/specify/specify7/tree/querycbx_multi_search

It is not perfect, because it just runs a separate query for each search field and then concatenates the results. This means there could be duplicates and they may not be in the order the user expects. A complete fix will require adjusting the query module to support 'OR' conjunctions between predicates.

Let me know if it works for you.

**Comment by NHMD** [comment]
Hi Ben
Thanks for your swift reply. I tried running the new branch but the form component failed again. This time the variable f was undefined on line 94 of querycbx.js, hence reading f.model blew it up.

Best
Thomas Stjernegaard Jeppesen
Software Architect

Natural History Museum of Denmark
Collections
University of Copenhagen
Universitetsparken 15
DK-2100 Copenhagen

t.stjernegaard@snm.ku.dk<mailto:t.stjernegaard@snm.ku.dk>


[cid:B4A03463-1BEE-4188-8467-61950C3E54A6@science.domain]

On 05 Feb 2015, at 00:33, Ben Anhalt <notifications@github.com<mailto:notifications@github.com>> wrote:


I created a branch that should fix this problem, I think:

https://github.com/specify/specify7/tree/querycbx_multi_search

It is not perfect, because it just runs a separate query for each search field and then concatenates the results. This means there could be duplicates and they may not be in the order the user expects. A complete fix will require adjusting the query module to support 'OR' conjunctions between predicates.

Let me know if it works for you.

**Comment by benanhalt** [comment]
Hmm. Can you set a break point at line 92 and tell me the value of `searchFieldStrs`? If `f` is `null` on line 95 indicates, that `relatedModel.getField(...)` failed for one of the strings. But looking at the `typesearch_def.xml` you pasted above, all the field names look valid. Did you back out the changes from this pull request? In particular, the change on line 46 of `specifymodel.js` would be a problem.

**Comment by NHMD** [comment]
Hi Ben, you are right - apparently I didn´t back the changes out properly. It works now, Thanks!

**Comment by benanhalt** [comment]
Great! I did have to make some changes to that fix on Friday, because it wasn't quite right. You should make sure you have gotten the latest commit on that branch. Thanks for your help!

**Pull request closed without merging**
