### PR TITLE
don't designate collection relationship tables as "system" tables.

### PR DESCRIPTION
**Pull request by benanhalt**
So that they can be uploaded to through the work bench.

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp It looks like the CoR was not established.

https://freshfish-colrelationship-tables-not-sys.test.specifysystems.org/specify/workbench/6/

image

image

image

**Comment by grantfitzsimmons** [comment]
A more resonable upload:

image

image

image


Am I uploading this incorrectly?

**Comment by maxxxxxdlp** [comment]
No. `CO` can not be a base table. See https://github.com/specify/specify7/issues/2090#issuecomment-1251089744 for explanation.

Collection Relationship Item should be the base table

**Comment by maxxxxxdlp** [comment]
That is, unless you are expecting to create new Collection Objects

**Comment by grantfitzsimmons** [comment]
> That is, unless you are expecting to create new Collection Objects

I want to create a new collection object with a relationship to an existing record in this instance.

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons  The mapping was wrong.

Here is the correct mapping: https://freshfish-colrelationship-tables-not-sys.test.specifysystems.org/specify/workbench/8/
And the created CO with a relationship: https://freshfish-colrelationship-tables-not-sys.test.specifysystems.org/specify/workbench-plan/8/

**Review by maxxxxxdlp — APPROVED** [review]
Uploading though WB worked for me

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-3-release-announcement/774/1

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1

**Pull request merged**
