### PR TITLE
Fix PartialDateUi not updating on precision change

### LINKED ISSUE #3075: "Year" in date picker non-functional in 7.8.7
https://user-images.githubusercontent.com/37256050/222444898-a54ad7be-ef08-46ef-bd6a-0723cd626931.mov

https://sp7demofish.specifycloud.org/specify/view/collectionobject/1112/?recordsetid=20

This applies to **all deployments** using 7.8.7

image

In summary, this needs to be fixed ASAP

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #3075

Caused by me when limiting max year for date pickers to 9999

### CODE REVIEW

**Review by chanulee1 — CHANGES_REQUESTED** [review]
Format for Mon/Year not displaying correctly.

https://user-images.githubusercontent.com/103299204/222513389-5f8e52f3-5fcd-4895-bce8-1b5a5604e482.mp4

**Comment by maxxxxxdlp** [comment]
> Format for Mon/Year not displaying correctly.

this seems like expected behavior

we didn't show the month/year format before unless custom picker is not supported (i.e, in firefox)

**Review by grantfitzsimmons — APPROVED** [review]

**Comment by grantfitzsimmons** [comment]
@chanulee1 That looks to be expected behavior

**Comment by chanulee1** [comment]
Ah, I see!

**Review by chanulee1 — APPROVED** [review]

**Pull request merged**
