### PR TITLE
Prompt the user with interaction dialog when adding a new prep

### LINKED ISSUE #4523: Can't add preparations to existing Gift records
**Describe the bug**

In `v7.9.3.1`, this is an existing issue for loans but was not a problem with gifts. 

In `edge`, adding a new preparation to an interaction record doesn't prompt the Add Items dialog on a Loan or Gift record and instead adds a read-only preparation record. On a gift record with a preparation added, adding the 

**To Reproduce**

1. Go to new Gift
2. Click on "Without Preparations"
3. Scroll down to Gift Preparations and click the `+`

**Expected behavior**

Should open Add Items dialog 

**Screenshots**

https://github.com/specify/specify7/assets/135047322/b39ea1d2-2dfe-44e4-af67-57c1bc71f650

Gift with prep already added: 
Screenshot 2024-02-12 at 10 00 10 AM

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name: `fwri_1_9_24`

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4523

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

Go to new Gift
Click on "Without Preparations"
Scroll down to Gift Preparations and click the +
See that the interaction dialog opens
Use different options to add new prep 
Do the same for loans

Can you check if it fixe #4078

### CODE REVIEW

**Review by maxpatiiuk — COMMENTED** [review]
sorry, I am a bit confused
looking at https://github.com/specify/specify7/issues/4523, it seems like there was a feature, and it stoped working, so we need to fix that
but this PR looks like it's adding a new feature
could you please check what code was responsible before for that dialog being displayed, and what happened to that code?
i.e did some code get lost, or is the code still there just not getting activated when it should be, and this PR is adding duplicated code?

**Comment by CarolineDenis** [comment]
@maxpatiiuk , yes the code was removed during a refactoring of the subview cell renderer. We need to add back certain parts of what as been deleted in order to fix this issue (issue that is happening since the refactoring)

**Comment by CarolineDenis** [comment]
@maxpatiiuk, indeed the code was lost during one of the merge. I rectified it. 
(ref to the refactoring code during which we added the interactionDialog in integratedRecordSelector that was lost https://github.com/specify/specify7/pull/3659)

**Comment by maxpatiiuk** [comment]
thank you for investigating - that sounds good
just wanted to make sure we don't add the same code twice

**Review by maxpatiiuk — APPROVED** [review]

**Review by emenslin — APPROVED** [review]
Looks good, both gift and loan preparations open the right dialog. 

https://github.com/specify/specify7/assets/150940840/2f839bb1-e581-4cdf-9def-201705716cf7

**Review by grantfitzsimmons — APPROVED** [review]

**Pull request merged**
