### PR TITLE
Fixes infinite calls for attachment page + fixes scroll + loading icons

### LINKED ISSUE #2751: Attachments scroll detection does not work correctly
When using a large screen (zoomed out) Specify messes up 

image

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #2751

### CODE REVIEW

**Review by maxxxxxdlp — APPROVED** [review]

**Comment by realVinayak** [comment]
I'm seeing this error sometimes when switching between tables 
Screenshot (58)
The crash report: 
[Specify 7 Crash Report - 2023-03-29T15_59_13.176Z.txt](https://github.com/specify/specify7/files/11102847/Specify.7.Crash.Report.-.2023-03-29T15_59_13.176Z.txt)

**Comment by realVinayak** [comment]
Also, can you combine this with branch https://github.com/specify/specify7/tree/issue-2999 and make a combined pull request? I'm concerned about any bugs that might come up when they are used together (which will be in production)

**Comment by maxxxxxdlp** [comment]
@realVinayak this should be merged soon to go into the release next week
#2999 won't be merged till after stats page

**Review by chanulee1 — CHANGES_REQUESTED** [review]
See above.

**Comment by realVinayak** [comment]
> @realVinayak this should be merged soon to go into the release next week #2999 won't be merged till after stats page

Ah I see

**Review by chanulee1 — APPROVED** [review]
Cannot replicate error on table change. Everything appears to be working.

**Pull request merged**
