### PR TITLE
Fix Table Aggregation Separator being set to undefined if it matches default "; "

### LINKED ISSUE #5154: ALL Table Aggregation separators with a space ` ` at the end or beginning are ERASED after any changes to DataObjFormatters
**Describe the bug**
If you make any changes to the Record Formatters file and save, all table aggregators with a separator set to "; " (A semicolon with a space after) will have the separator erased.
Apparently this has been happening for a while and multiple databases have been affected already.

The same separator works in table format however.

**To Reproduce**

1. Go to App Resources -> Record Formatters -> Table Aggregation
2. Edit Accession Agent Table Aggregation
3. Set the Separator to "; "
4. Close
5. Click Save
6. Go back to Accession Agent Table Aggregation
7. Check the Separator

**Expected behavior**
This separators should be supported as it is in Table Formats.

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge (7.9.7), 7.9.6, 7.9.5, 7.9.4
- Database Name: kubirds & sp7demofish
- User Name: spbirdadmin

### PR DESCRIPTION
**Pull request by alesan99**
Fixes #5154 

Table Aggregation Separators should no longer be getting set to undefined during serialization if they match the default ("; ").

All previously affected databases will need to have their separators restored separately. Though it is safe to assume all blanks were originally "; ".

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions

- Go to App Resources -> Record Formatters -> and open any Table Aggregation
- Set the separator to "; "
- Save
- [ ] Verify the separator is still there and isn't blank.

### CODE REVIEW

**Review by pashiav — APPROVED** [review]
- [X] Verify the separator is still there and isn't blank.
---

Working as expected. Good job!

`edge`

https://github.com/user-attachments/assets/e8adc161-6e93-4fbe-9d37-8b9667e55d0a

`pr`


https://github.com/user-attachments/assets/abe6eb2a-61c6-4fb9-a536-9731cc8cbca6

**Review by Areyes42 — APPROVED** [review]
### Testing instructions

-   Go to App Resources -> Record Formatters -> and open any Table Aggregation
-   Set the separator to "; "
-   Save
-   [x] Verify the separator is still there and isn't blank.
***
Separator gets retained now, nice job!
Screenshot 2024-08-26 at 4 21 14 PM

**Review by maxpatiiuk — APPROVED** [review]
👍

**Review by grantfitzsimmons — APPROVED** [review]

**Review by emenslin — APPROVED** [review]
### Testing instructions




- Go to App Resources -> Record Formatters -> and open any Table Aggregation
- Set the separator to "; "
- Save
- [x] Verify the separator is still there and isn't blank.

Looks good, separator doesn't get deleted

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-7-release-announcement/1979/1

**Pull request merged**
