### PR TITLE
Fix new record set text

### PR DESCRIPTION
**Pull request by grantfitzsimmons**
Solves #4303

## Before:
image

## After:
image

### CODE REVIEW

**Review by pashiav — CHANGES_REQUESTED** [review]
Still says "Creating new record".
issue-4303

https://fwri6123-issue-4303.test.specifysystems.org/specify/view/collectionobject/492741/

**Comment by grantfitzsimmons** [comment]
> Still says "Creating new record".

When I launch that deployment, it shows this commit identifier: 
https://github.com/specify/specify7/commit/83d1d50944601146c8d0f79ec9b7575c2cffb13c
This is prior to completing the changes. I'm updating the branch in the hope of completing the update.

Thank you!

**Comment by grantfitzsimmons** [comment]
@pashiav Now that the Dockerize action has succeeded, it is working as expected!

image

**Review by emenslin — APPROVED** [review]
Says the correct thing now.
Screenshot 2023-12-21 142144

**Review by CarolineDenis — APPROVED** [review]

**Review by melton-jason — APPROVED** [review]

**Pull request merged**
