### PR TITLE
add api to create RS from WB upload instead of just doing it.

### PR DESCRIPTION
**Pull request by benanhalt**
This commit removes the automatic creation of a record set of uploaded
records during a data set upload.

It adds a new endpoint /api/workbench/create_recordset/{ds_id}/ that
accepts a name parameter and creates a record set of that name from
the upload results of data set with the given id.

It adds a new permission check for resource = '/workbench/dataset'
action = 'create_recordset'.

It adds a data migration to automatically grant said permission to any
user or role currently possessing permission on resource
'/workbench/dataset' action 'upload'.

### CODE REVIEW

**Comment by benanhalt** [comment]
@maxxxxxdlp This PR is ready for UI to be added.

**Comment by maxxxxxdlp** [comment]
To test:
- Upload a data set, and click on "Creaate Record Set"
- Open the results side panel and click on "Create Record Set"
- General WorkBench changes (I did legacy code refactoring)
   - Validate/Upload/Unupload
   - Disambiguate/Disambiguate All
   - Delete data set
   - GeoMap
   - GeoLocate
   - Coordinate Convertor
   - Change Owner
   - Rename data set

**Review by maxxxxxdlp — APPROVED** [review]
Back-end changes are tested. Looks good.

Someone still needs to test the front-end changes.

**Comment by grantfitzsimmons** [comment]
image

https://newmexico-issue-1848.test.specifysystems.org/specify/workbench/11/

404 error

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
404 trying to create a record set from an uploaded data set

**Comment by maxxxxxdlp** [comment]
Fixed
@grantfitzsimmons can you try this again?

**Comment by grantfitzsimmons** [comment]
image

[Specify 7 Crash Report - 2022-12-29T16_28_26.952Z.txt](https://github.com/specify/specify7/files/10320461/Specify.7.Crash.Report.-.2022-12-29T16_28_26.952Z.txt)

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/209981894-81e4fbdf-b344-4a86-bcac-9d719ab59c91.mov

"Are you sure you want to leave this page?" appearing for an uploaded record set with no changes

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
Some small issues

**Comment by maxxxxxdlp** [comment]
The variety taxon rank error is probably not connected to this. Can you reproduce it on another branch?

**Comment by grantfitzsimmons** [comment]
That's not the issue– is unreleated. the unsaved changes dialog needs to be fixed :-)

**Comment by maxxxxxdlp** [comment]
Fixed the false unload protect error

**Comment by maxxxxxdlp** [comment]
Merged this with changes from production. Ready for testing once again

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons @melton-jason could both of you please test this so that we can merge it?

This PR is the first step onto an eventual WB refactor (for React and TypeScript)

Testing steps: https://github.com/specify/specify7/pull/1857#issuecomment-1366151442

**Comment by grantfitzsimmons** [comment]
@melton-jason Not really– I would do an export of a query and try to disambiguate it from there.

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/212179932-66a510af-dc1f-4d73-bd24-e335e616f501.mp4

https://herbrbge6802-issue-1848.test.specifysystems.org/specify/workbench/41/

`rcubey` is the user

**Comment by grantfitzsimmons** [comment]
image

For disambiguating the agent that failed above, I had success & no issues.

https://herbrbge6802-issue-1848.test.specifysystems.org/specify/workbench/41/

For disambiguating a tree item, also no problems, until I attempted to upload. This might be beyond the scope of this PR, but the API to create a RS is triggered even when the upload failed

https://user-images.githubusercontent.com/37256050/212956800-25afdc6d-5fa7-4d8d-99bd-83848b726beb.mp4

This seems to be a somewhat major issue. The error was particularly not useful, seeing as it reported the following:

```
OperationalError(1065, 'Query was empty')"
```

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
There is a chance this record set creation dialog is being called in error from another bug. 

You should not be able to create a record set if there is no data uploaded

**Comment by grantfitzsimmons** [comment]
Seems to be the same underlying issue as https://github.com/specify/specify7/issues/2828

**Comment by maxxxxxdlp** [comment]
The "Query is empty" error is indeed caused by #2828 and should be fixed now.
The "Upload Completed with No Errors" is a workbench bug that existed prior to this change - it's because the upload failed, but the back-end returned 0 error cells. Opened

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons besides that issue, is there anything else, or is this ready to be merged? 🎉

**Review by grantfitzsimmons — APPROVED** [review]
👍 Looks like it's ready to go.

**Pull request merged**
