### PR TITLE
Improve Form Definition Validation

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes [#2688](https://github.com/specify/specify7/issues/2666)
Paves the way for #2110

### CODE REVIEW

**Comment by maxxxxxdlp** [comment]
Ready for testing

**Comment by grantfitzsimmons** [comment]
on `herb_rbge_6802`:

```xml
<cell type="subview" viewname="Determination" id="6" name="determinations" defaulttype="table" colspan="13" rows="5" initialize="sortField=-isCurrent"/>
```

image

left: `edge`
right: `xml-validation`

The sort order for `isCurrent` in the subview is not being recognized.

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
sort order for a subview not respected

**Comment by grantfitzsimmons** [comment]
image

It's clear that forms _will_ look different after this change, but I am not convinced it is a bad thing.

See that the field labels and field widths are very different between versions.

**Comment by grantfitzsimmons** [comment]
This also does not fix #2714.

Try to view this link:
https://umichmollusks20221222-xml-validation.test.specifysystems.org/specify/view/collectionobject/49429/

with the user `xmlform` who has permisison to read Collection Object and Determination tables.

image

**Comment by grantfitzsimmons** [comment]
image

In this case, it's clear the `edge` (left) behavior is better than the `xml-validation`. The QCBX is much wider and more useful on `edge`

**Comment by grantfitzsimmons** [comment]
- [x] Putting plugins on unsupported forms

   
    image


- [x] Putting commands on unsupported forms

    image


- [x] Invalid weblink names

    image

    Form not display anything, reports to the console.

- [x] Invalid field names

    Reports to the console

- [x] Invalid viewdef name

image

image

Did not report errors in a friendly way when I use a bad viewname.

- [x] Invalid formatter names
- [x] Any other weird forms you seen. @grantfitzsimmons you are probably an expert on this)
     - [x] `keherbariumvascular`
     - [x] `herb_rbge_6802` 
     - [x] `coldFish`
     - [x] `sanbibiobank`

**Comment by maxxxxxdlp** [comment]
> on `herb_rbge_6802`:
> 
> ```
> <cell type="subview" viewname="Determination" id="6" name="determinations" defaulttype="table" colspan="13" rows="5" initialize="sortField=-isCurrent"/>
> ```
> 
> image
> 
> left: `edge` right: `xml-validation`
> 
> The sort order for `isCurrent` in the subview is not being recognized.

Fixed

**Comment by maxxxxxdlp** [comment]
Added the following error to the console for 404 errors when fetching the view definition:

> Unable to find a view definition for the "{name}" view

**Comment by maxxxxxdlp** [comment]
Another intentional change:

(can be seen on accession form in herbrbge6802)

Before: 

Screenshot 2023-01-05 at 10 13 04

After:

Screenshot 2023-01-05 at 10 12 51

If you render a date field as a Text field, it displays the date picker, but without the precision picker. This way there is now a way to hide the precision picker if it's not needed.

Similarly, a new attribute has been added to the PartialDateUI definition: https://github.com/specify/specify7/wiki/Form-System#:~:text=precision%20to%20use.-,canChangePrecision,-(true%20%7C%20false%2C%20optional

**Comment by maxxxxxdlp** [comment]
This branch also updated react-router. Looks like newer version removed the workaround we were using to implement UnloadProtect (they removed official way to block navigation in v6 😠 )

Looks like they are working on adding newer solution: https://github.com/remix-run/react-router/pull/9709

If they are not finished by the time we need to merge this, I will just revert the react router update

**Comment by maxxxxxdlp** [comment]
Another change:
previously it was displaying fields with invalid field names.
Now it only displays fields with invalid field names if:
 - Field has a default value (this way fields can be used to display messages on a form)
 - Field is a plugin (many plugins don't require a field name; weblink plugin even encourages invalid field names)

**Comment by maxxxxxdlp** [comment]
> image
> 
> It's clear that forms _will_ look different after this change, but I am not convinced it is a bad thing.
> 
> See that the field labels and field widths are very different between versions.

Caused by a bug. Fixed (the date pickers rendered differently)

**Comment by maxxxxxdlp** [comment]
Ah, #2714 won't be fixed by this. It's a back-end limitation. See https://github.com/specify/specify7/issues/2714#issuecomment-1373035008

**Comment by maxxxxxdlp** [comment]
Please also test if this fixes #1949

**Comment by grantfitzsimmons** [comment]
It seems to fix https://github.com/specify/specify7/issues/1949 by making the field read-only
image

**Comment by grantfitzsimmons** [comment]
image

Cannot add a determination
https://herbrbge6802-xml-validation.test.specifysystems.org/specify/view/collectionobject/1178914/?recordsetid=322

https://herbrbge6802-xml-validation.test.specifysystems.org/specify/view/collectionobject/1178914/?recordsetid=322

[Specify 7 Crash Report - 2023-01-11T17 29 49.929Z.txt](https://github.com/specify/specify7/files/10394633/Specify.7.Crash.Report.-.2023-01-11T17.29.49.929Z.txt)

**Comment by maxxxxxdlp** [comment]
Fixed.
This was caused by the following fields:
```xml
<row>
                    <cell type="label" labelfor="familyNumber" label="Family No." />
                    <cell type="field" id="familyNumber" name="taxon.text11" uitype="label" />
                    <cell type="label" labelfor="genusNumber" label="Genus No." />
                    <cell type="field" id="genusNumber" name="taxon.text12" uitype="label" />
                </row>
```

It was crashing because newly added determination does not have taxon resource.

Fixed by not rendering the fields until Determination has Taxon resource.
Would a better fix be to render the fields as disabled and without a value until there is a Taxon resource?

When testing, please test setting/unsetting taxa and switching between Determinations in a subview and making sure the fields display correct value in all those cases.

Also, while loading, I believe it currently shows the old value

**Comment by maxxxxxdlp** [comment]
FYI: the bug would have been caught earlier if not for the legacy unsafe backbone code

Who knows how many more bugs like this are in the codebase.
Desperately need to rewrite backbone code

**Comment by grantfitzsimmons** [comment]
> Response to https://github.com/specify/specify7/pull/2725#issuecomment-1379729071
> 
> If you have time, can you please check if this is fixed on `xml-validation` branch? (it includes a fix for the routing bug)

This is solved on this PR

**Comment by grantfitzsimmons** [comment]
Screenshot 2023-01-12 at 3 54 13 PM

>  Would a better fix be to render the fields as disabled and without a value until there is a Taxon resource?

Yes! No field at all is a bit shocking.

**Comment by maxxxxxdlp** [comment]
> Yes! No field at all is a bit shocking.

Fixed. Though, you would need to do general testing of forms again as this change affected every form component.

**Comment by maxxxxxdlp** [comment]
This is ready for testing now once again.

To test:
General testing of all forms
Unload protect (it's when you have unsaved changes and it asks you to confirm before going to a different page)

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
Attachments form is not displaying


https://user-images.githubusercontent.com/37256050/213965561-a688ebdd-c31f-47bf-8dc7-028ff58b7e0c.mov

Firefox, macOS

**Review by grantfitzsimmons — APPROVED** [review]

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1

**Pull request merged**
