### PR TITLE
Display same form before and after attachement saved

### LINKED ISSUE #3328: Collection Object attachment form used before save, Attachment form used after save
> Wrong visualization in the data stored. The captions are in english [image.png](https://trello.com/1/cards/642185694e84959a8e961cba/attachments/642186d099b8f6caa779f3f0/download/image.png) and also don’t show all the custom fields.

Uploading to the test panel as `mcnb_4_11_23`, `spadmin`, `Invertebrate non-arthropod` collection

## New record, before saving

image

## Record after saving

image

**Reported By:** [Barcelona on Trello](https://trello.com/c/OY5qYzcC/51-specify-attachments)

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3328

### CODE REVIEW

**Review by maxpatiiuk — APPROVED** [review]

**Comment by maxxxxxdlp** [comment]
For future reference:
This pull request fixes a bug that has been present in specify for a long time, however it did not manifest itself until now

**Review by chanulee1 — CHANGES_REQUESTED** [review]
Now uses the Attachment form before and after the attachment is saved instead of the CollectionObjectAttachment form. Expected?


https://user-images.githubusercontent.com/103299204/234354662-7d5b9dba-f7b6-4f63-934f-3d1a81edf4d5.mp4

https://mcnb41123-issue-3328.test.specifysystems.org/specify/view/collectionobject/1350712/

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
On `edge` when creating a new record:
image
https://mcnb41123-edge.test.specifysystems.org/specify/view/collectionobject/1350713/

On `issue-3328` when creating a new record:
image
https://mcnb41123-issue-3328.test.specifysystems.org/specify/view/collectionobject/1350713/

While this does indeed make them show the same form before and after, most people want to see the `ObjectAttachment Form` that they defined both before and after, not the regular Attachment form.

For reference, lines 4064 – 4148 in the `mcnb_4_11_23` database:
https://mcnb41123-edge.test.specifysystems.org/specify/resources/view-set/178/

```xml
        <view name="ObjectAttachment"
            class="edu.ku.brc.specify.datamodel.ObjectAttachmentIFace"
            busrules="edu.ku.brc.specify.datamodel.busrules.AttachmentBusRules"
            resourcelabels="false">
            <desc><![CDATA[The Object-Attachment View.]]></desc>
            <altviews>
                <altview name="ObjectAttachment Icon View"  viewdef="ObjectAttachment IconView" mode="view"/>
                <altview name="ObjectAttachment Icon Edit"  viewdef="ObjectAttachment IconView" mode="edit"/>
                <altview name="ObjectAttachment Table View" viewdef="ObjectAttachment Table"    mode="view" />
                <altview name="ObjectAttachment Table Edit" viewdef="ObjectAttachment Table"    mode="edit"/>
                <altview name="ObjectAttachment Form View"  viewdef="ObjectAttachment Form"     label="Form" mode="view" default="true"/>
                <altview name="ObjectAttachment Form Edit"  viewdef="ObjectAttachment Form"     label="Form" mode="edit"/>
            </altviews>
        </view>
```

```xml
        <viewdef
            type="form"
            name="ObjectAttachment Form"
            class="edu.ku.brc.specify.datamodel.ObjectAttachmentIFace"
            gettable="edu.ku.brc.af.ui.forms.DataGetterForObj"
            settable="edu.ku.brc.af.ui.forms.DataSetterForObj"
            useresourcelabels="true">
            <desc><![CDATA[The ObjectAttachment form.]]></desc>
            
            <columnDef>p,2px,p:g</columnDef>
            <rowDef auto="true" cell="p" sep="2px"/>
    		<rows>
                <row>
                    <cell type="label" labelfor="origFilename" label="Nom Arxiu Original"/>
                    <cell type="field" id="origFilename" name="attachment.origFilename" initialize="editoncreate=true" uitype="browse" isrequired="true"/>
                </row>
                <row>
                	<cell type="label" labelfor="title"  label="Titol"/>
                	<cell type="field" id="title" name="attachment.title" uitype="text" isrequired="true"/>
               </row>
                <row>
                	<cell type="label" labelfor="ispub" label=""/>
                	<cell type="field" id="ispub" name="attachment.isPublic" uitype="checkbox" label="Imatge web"/>
                </row>
                <row>
                    <cell type="label" labelfor="type" label="Tipus"/>
                    <cell type="field" id="type" name="attachment.type" uitype="combobox" picklist="attachment tipus"/>
                </row>
                <row>
                    <cell type="label" labelfor="subtype" label="Subtipus"/>
                    <cell type="field" id="subtype" name="attachment.subtype" uitype="combobox" picklist="subtipus"/>
                </row>
                <row>
                    <cell type="label" labelfor="mimeType" label="Extensio"/>
                    <cell type="field" id="mimeType" name="attachment.mimeType" uitype="combobox" picklist="extensio"/>
                </row>
				<row>
                    <cell type="label" labelfor="attachmentLocation" label="Ubicacio"/>
                    <cell type="field" id="attachmentLocation" name="attachment.attachmentLocation" uitype="text"/>
                </row>
				<row>
		            <cell type="label" labelfor="remarks" label="Observacions"/>
                    <cell type="field" id="remarks" name="attachment.remarks" uitype="text"/>			
				</row>
				<row>
					<cell type="label" labelfor="captureDevice" label="Metode d'obtencio"/>
                    <cell type="field" id="captureDevice" name="attachment.captureDevice" uitype="combobox" picklist="metode dobtencio"/>	
				</row>
                <row>
                    <cell type="label" labelfor="1" label="Lloc de produccio"/>
                    <cell type="field" id="1" name="attachment.dateImaged" uitype="combobox" picklist="lloc de produccio"/>
                </row>
				<row>
					<cell type="label" labelfor="fileCreatedDate" label="Data de produccio"/>
                    <cell type="field" id="fileCreatedDate" name="attachment.fileCreatedDate" uitype="text"/>	
				</row>
				<row>
					<cell type="label" labelfor="creator" label="Autor (adreca)"/>
					<cell type="field" id="creator" name="attachment.creator" uitype="querycbx" initialize="name=Agent" />
                </row>
                <row>
                    <cell type="label" labelfor="copyrightHolder" label="Copyright"/>
                    <cell type="field" id="copyrightHolder" name="attachment.copyrightHolder" uitype="combobox" picklist="copyright"/>
				</row>
                <row>
                    <cell type="label" labelfor="copyrightDate" label="Data copyright"/>
                    <cell type="field" id="copyrightDate" name="attachment.copyrightDate" uitype="text"/>
                </row>
				<row>
					<cell type="label" labelfor="credit" label="Credits"/>
                    <cell type="field" id="credit" name="attachment.credit" uitype="combobox" picklist="credits"/>	
				</row>
                <row>
                    <cell type="label" labelfor="2" label="Llicencia"/>
                    <cell type="field" id="2" name="attachment.license" uitype="combobox" picklist="llicencia"/>
                </row>
                <row>
                    <cell type="label" labelfor="so" label="Precisions"/>
                    <cell type="field" id="so" name="attachment.subjectOrientation" uitype="text"/>
                </row>
    		 <!--   <row>
    		        <cell type="subview" id="metadata" name="attachment.metadata" viewname="AttachmentMetadata" colspan="3"/>
    		    </row> -->
    		</rows>
		</viewdef>
```

This is what 6 shows in the application. We want 7 to show this both before and after saving instead **if it is user-defined in the forms** (as it is here).

**Review by maxpatiiuk — APPROVED** [review]

**Review by chanulee1 — CHANGES_REQUESTED** [review]
Attempting to upload an agent attachment results in this:

https://user-images.githubusercontent.com/103299204/236268230-dca9e927-1e53-4f60-8178-379efd2fa7f8.mp4

Seems to happen for attachment subforms rendered as buttons. Could not replicate on `edge`.

https://mcnb41123-issue-3328-2.test.specifysystems.org/specify/view/agent/new/

**Comment by maxxxxxdlp** [comment]
> Attempting to upload an agent attachment results in this

It recursively renders the same form at infinite, until it eventually will crash the webpage

**Review by maxpatiiuk — APPROVED** [review]

**Review by chanulee1 — CHANGES_REQUESTED** [review]
Object Attachment form displayed before and after save, but text fields in form are missing.

https://github.com/specify/specify7/assets/103299204/c3598d9b-997c-46ae-b506-b3bca76e686f

Also, Agent attachments is not using ObjectAttachment form either.

https://github.com/specify/specify7/assets/103299204/ef24ec33-9adc-4b9a-a720-8b4eae5f12b1

**Comment by CarolineDenis** [comment]
@maxxxxxdlp if you have some time, could you give your input on this issue?

**Comment by maxxxxxdlp** [comment]
Yes, sorry for delay. Will try to get to this on the weekend

**Comment by CarolineDenis** [comment]
@grantfitzsimmons @chanulee1 could you send me a detailed explanation of what is expected for this?

**Comment by maxxxxxdlp** [comment]
From the last video Chanu sent, it looks like AgentAttachment form is being used instead of ObjectAttachment.
In this case it leads to undesirable result.

In the code we look at the form in the following places (in order of priority):
1. If <TableName>Attachment view exists in the app resources, use that
2. If ObjectAttachment view exists in the app resources, use that
3. If <TableName>Attachment view exists among the default sp6 views, use that
4. If ObjectAttachment view exists among the default sp6 views, use that
5. If none else exist, use the autogenerated view (I belive the <TableName>Attachment autogenerated view would be used, but would have to double check)

Is this the logic we want to follow? If it doesn't work in some cases, we might be forced to have to modify it.
Can someone check how does this logic compares to sp6 behavior?

**Comment by grantfitzsimmons** [comment]
> From the last video Chanu sent, it looks like AgentAttachment form is being used instead of ObjectAttachment. In this case it leads to undesirable result.
> 
> In the code we look at the form in the following places (in order of priority):
> 
> 1. If Attachment view exists in the app resources, use that
> 2. If ObjectAttachment view exists in the app resources, use that
> 3. If Attachment view exists among the default sp6 views, use that
> 4. If ObjectAttachment view exists among the default sp6 views, use that
> 5. If none else exist, use the autogenerated view (I belive the Attachment autogenerated view would be used, but would have to double check)
> 
> Is this the logic we want to follow? If it doesn't work in some cases, we might be forced to have to modify it. Can someone check how does this logic compares to sp6 behavior?

As I mentioned previously,
> most people want to see the ObjectAttachment Form that they defined both before and after, not the regular Attachment form.

In my opinion, it should follow this process:

> 1. If ObjectAttachment view exists in the app resources, use that
> 2. If Attachment view exists in the app resources, use that
> 4. If ObjectAttachment view exists among the default sp6 views, use that
> 3. If Attachment view exists among the default sp6 views, use that
> 5. If none else exist, use the autogenerated view


Once we have this set up, I'd like to test it with Barcelona's database to make sure it behaves as they would expect.

**Comment by maxxxxxdlp** [comment]
makes sense. should be just a one line change. @CarolineDenis

**Comment by CarolineDenis** [comment]
> makes sense. should be just a one line change. @CarolineDenis

Could you add a comment in the code to know which line does what? Or give me some explanation regarding which variable correspond to which tables or sp7/6?

**Comment by maxxxxxdlp** [comment]
<details><summary>Hint</summary>
<p>

Look at the code that you added that does the fetching of form definition and especially where it decides which of the fetched view definitions to use

</p>
</details> 

<details><summary>Solution</summary>
<p>

Swap these two array items:
https://github.com/specify/specify7/pull/3342/files#diff-b7a5d73a17dfeea6bd070f174f3d8620cbc6205b8074f029f6d7cbde6b67629bR87

</p>
</details>

**Review by bronwyncombs — APPROVED** [review]
Working as expected!

https://github.com/specify/specify7/assets/135047322/46c09827-145b-45f2-b156-a8968758d96b

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
`issue-3328`:
https://mcnb62923-issue-3328.test.specifysystems.org/specify/view/collectionobject/1350734/

# 🤨

The form is strangely unusable

image

---

`edge`:
https://mcnb62923-edge.test.specifysystems.org/specify/view/collectionobject/new/

image

**Comment by CarolineDenis** [comment]
There's also an issue with collection event attachment. There is an infinite loop

**Comment by grantfitzsimmons** [comment]
Jordi is still dealing with this issue

**Comment by bronwyncombs** [comment]
Jordi requested another update on resolving this issue

**Pull request closed without merging**
