### PR TITLE
Display color picker in safari

### LINKED ISSUE #2215: Color picker not working in Safari
image

Color picker in user preferences is not working in Safari on macOS Monterey

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixed #2215

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
This is still showing as a blank white screen to me 😢

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons can you please review this again? It is working for me now

**Comment by grantfitzsimmons** [comment]
image

Initially could not open preferences

[Specify 7 Crash Report - 2023-03-07T15_43_58.047Z.txt](https://github.com/specify/specify7/files/10911263/Specify.7.Crash.Report.-.2023-03-07T15_43_58.047Z.txt)


image

Looks great after a reload!

**Review by grantfitzsimmons — APPROVED** [review]
Nice!

**Review by maxxxxxdlp — APPROVED** [review]

**Pull request merged**
