### PR TITLE
Turn top menu into a side menu

### LINKED ISSUE #1462: The navigation menu should be vertical
https://user-images.githubusercontent.com/37256050/167481768-2ced2c3f-de59-45c4-b5a1-cba28ee124f8.mov

It better utilizes available space, since most of the time you don't have anything on the left or the right side of the screen, while vertical screen estate is very precious.

### LINKED ISSUE #1640: Improve header menu items
Swap the username and current collection in the header bar
Swap search box and notifications
Add a gear icon to make it easier to find user tools
Replace "Notifications" button with a bell icon
Suggested by @beach53

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Redesign of the top menu to better use screen estate, use less space on smaller screens.
Also fixes the ugly overflow of items (when menu items are in two rows on all but most wide screens)

Fixes #1462
Fixes #1640

Screenshot 2023-01-02 at 23 02 07

Screenshot 2023-01-02 at 22 57 52

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/210360760-8cf7cb43-3a96-41e8-a74b-5a72537e4aef.mov

Simple search does not have a text entry field and causes a crash when clicked

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/210369400-8acce078-60b0-48cd-b25a-9dfc61613377.mov

Some small issues with the User Preferences page when the window is occupying half the width of my screen

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
Besides that issue, I have several requests that may be reasonable or a lot of work, just let me know.

- Maintain the height and padding of the Specify logo when expanded.
- Add an animation when expanding and collapsing the sidebar
- Make the sidebar collapse/expand button more obvious to the user (maybe make it wider with a grab handle)
- Make icons consistent with the items when expanded (e.g. show the gear icon next to the username and show the archive icon next to the collection selector)

**Comment by grantfitzsimmons** [comment]
I spend some time looking into how this works and got lost trying to understand all of the code in Specify 7. Going to need to do some bootcamp on React and TypeScript before I continue...

**Comment by maxxxxxdlp** [comment]
Another change to test:
The search results page now displays the splash screen image (or taxon tiles) until you enter search query

**Comment by maxxxxxdlp** [comment]
> Screen.Recording.2023-01-03.at.7.45.21.AM.mov 
> Some small issues with the User Preferences page when the window is occupying half the width of my screen

Unable to replicate, but fixed a related issue with the aside menu. Please test this to check if it happens again. If so, please provide more details (browser version, zoom level, screen size)

**Comment by maxxxxxdlp** [comment]
> Besides that issue, I have several requests that may be reasonable or a lot of work, just let me know.
> 
> * Maintain the height and padding of the Specify logo when expanded.
> * Add an animation when expanding and collapsing the sidebar
> * Make the sidebar collapse/expand button more obvious to the user (maybe make it wider with a grab handle)
> * Make icons consistent with the items when expanded (e.g. show the gear icon next to the username and show the archive icon next to the collection selector)

3 variants of logo padding:
Screenshot 2023-01-03 at 10 41 04
Screenshot 2023-01-03 at 10 41 09
Screenshot 2023-01-03 at 10 49 38

or do you also want to the logo larger and increase the size of the side bar?

**Comment by maxxxxxdlp** [comment]
If we are going to add animation, then the menu should probably be an overlay. Otherwise, animating the menu width would cause performance issues with the workbench and taxon tiles

**Comment by maxxxxxdlp** [comment]
Added a handle to the menu:

Screenshot 2023-01-03 at 10 44 33

**Comment by grantfitzsimmons** [comment]
image

Menu items should be a scrollable list and the bottom elements should be fixed

**Comment by maxxxxxdlp** [comment]
Fixes #2418

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/211960440-418f7d28-2d68-4dee-85b0-a6a3b8bc4c3c.mov

See when a dialog is opened that the lighting is not consistent. This is at half speed.

**Comment by maxxxxxdlp** [comment]
I think this is actually caused by the router bug I talked about (present since 7.8)
You should be able to replicate this on production too.

If you have time, can you please check if this is fixed on `xml-validation` branch? (it includes a fix for the routing bug)

**Comment by grantfitzsimmons** [comment]
> I think this is actually caused by the router bug I talked about (present since 7.8) You should be able to replicate this on production too.
> 
> If you have time, can you please check if this is fixed on `xml-validation` branch? (it includes a fix for the routing bug)



> If you have time, can you please check if this is fixed on `xml-validation` branch? (it includes a fix for the routing bug)

It is resolved!

**Comment by maxxxxxdlp** [comment]
Also fixes #2820

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons can you send me a list of thnngs you want to change in the first release before this goes out?

Do you want to have https://github.com/specify/specify7/issues/2840, https://github.com/specify/specify7/issues/2839 and https://github.com/specify/specify7/issues/2838 fixed before this goes into production? Or should we not delay this any futher and push it into production to get more feedback from users?

**Comment by grantfitzsimmons** [comment]
We should consider keeping it permanently collapsed and have it expand with an animation only when trying to view the labels (like gmail folders upon hover).

I don’t think we should push to production as-is, and I can compile a full list later. I’m on my phone at the moment.

Let’s consider adding the dialogs for the elements that need to be expanded (dialog for collection switcher, search)

**Comment by maxxxxxdlp** [comment]
Additional things to test:
Menu collapsed on narrow screens
Stress test the menu items customization (in use preferences under "Top Menu Items")
Test different menu positions (customizable in user preferences)

**Comment by chanulee1** [comment]
Looks great to me! Side menu is definitely an improvement in my opinion.

**Review by grantfitzsimmons — APPROVED** [review]

**Pull request merged**
