### PR TITLE
Fetch attachments once gallery icon is clicked

### LINKED ISSUE #4261: Infinite loop with uniqueness checking rule
Seems like a pretty critical issue due to the infinite loop sending a ton of network requests.

Replication (on production branch in ku fish):

https://github.com/specify/specify7/assets/40512816/200543de-9e72-4236-af26-5e563f7d2600

Seems like just opening the Accession form is enough, but showed other steps just in case it makes a difference

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4261

### CODE REVIEW

**Review by maxpatiiuk — APPROVED** [review]
oh, cool that it's that simple!
my solution was going to be worse...

**Review by pashiav — APPROVED** [review]
Works as expected. Looks good!

**Review by emenslin — APPROVED** [review]
Looks good, and works as expected.

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-3-release-announcement/1499/1

**Pull request merged**
