### PR TITLE
Hide header title and trash icon when no table

### LINKED ISSUE #4647: Hide header title and trash icon in formatter dialog

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4647

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

- go in app resources
- choose record formatter 

- [ ] verify that the titles and trash icon are correct when condition 
- [ ] verify that the titles and trash icon are correct when no condition 
- [ ] verify that the titles and trash icon are correct when condition and no expansion 
- [ ] verify that the titles and trash icon are correct when condition and expansion 
- [ ] verify that there is no titles and no trash icon when creating a new formatter before clicking for the first time the add button

### CODE REVIEW

**Comment by CarolineDenis** [comment]
Before: 
Screenshot 2024-03-13 at 10 23 06 AM
Now: 
Screenshot 2024-03-13 at 10 22 24 AM

**Review by emenslin — APPROVED** [review]
### Testing instructions

- go in app resources
- choose record formatter 

- [x] verify that the titles and trash icon are correct when condition 
- [x] verify that the titles and trash icon are correct when no condition 
- [x] verify that the titles and trash icon are correct when condition and no expansion 
- [x] verify that the titles and trash icon are correct when condition and expansion 
- [x] verify that there is no titles and no trash icon when creating a new formatter before clicking for the first time the add button 
Looks good!
Screenshot 2024-03-13 125618

**Review by bronwyncombs — CHANGES_REQUESTED** [review]
- [ ] verify that the titles and trash icon are correct when condition 
**Can we remove the "Expand" title, this feels unnecessary
How it was in 6:**
Screenshot 2024-03-14 at 9 04 29 AM

- [X] verify that the titles and trash icon are correct when no condition 

- [X] verify that the titles and trash icon are correct when condition and no expansion 
**Good except for the Expand title. No trashcan icon, I believe this is correct based on the PR screenshots**
- however, at the end of this you'll see a recording where the trash icons are present, unsure
Screenshot 2024-03-14 at 9 31 54 AM

- [ ] verify that the titles and trash icon are correct when condition and expansion 
**If no fields, the conditional content is centered when expanded:**
Screenshot 2024-03-14 at 9 23 30 AM

https://github.com/specify/specify7/assets/135047322/61670bc9-aff9-4f75-812c-02bc85a81254

**Also, when new conditional added the `Add Field` button expands vertically:**
Screenshot 2024-03-14 at 9 08 20 AM


- [X] verify that there is no titles and no trash icon when creating a new formatter before clicking for the first time the add button 
**Good**
Screenshot 2024-03-14 at 9 22 49 AM

This vid shows the general behavior when adding and deleting conditional formats. Notice the button sizing, presence and absence of trash icon, centering issue, etc.

https://github.com/specify/specify7/assets/135047322/69e40e0e-c676-4276-bd8b-078297f40601

**Review by bronwyncombs — APPROVED** [review]
- [x] verify that the titles and trash icon are correct when condition 
- [x] verify that the titles and trash icon are correct when no condition 
- [x] verify that the titles and trash icon are correct when condition and no expansion 
- **When condition, the trash icon will appear in collapsed view once a field is added. I believe this is the expected behavior. Looks good.**
- [x] verify that the titles and trash icon are correct when condition and expansion 
- **`Add Field` button growing is fixed! The expanded content center align issue also resolved!**
- [x] verify that there is no titles and no trash icon when creating a new formatter before clicking for the first time the add button

**Pull request merged**
