### PR TITLE
Avoid throwing errors on workbench validation for undefined treedefid

### LINKED ISSUE #5313: `Multiple treedefitems found for rank Continent` when validating data set
**Describe the bug**
This happens only in `v7.9.7` or later (incl. `production` as of https://github.com/specify/specify7/commit/92c94292c6d70fb867994d88ca503ea56572ea8f) . This does not happen in `v7.9.6.2`.

**To Reproduce**

1. Go to https://ojsmnh20241003wb-production.test.specifysystems.org/specify/workbench/254/ (`v7.9.7` or `production`), logged in as `spadmin` in the Ichthyology collection
2. Validate the data set
3. See the following error:
	```
	{
	  "uploaderstatus": {
	    "operation": "validating",
	    "taskid": "26f94f3b-f6e8-42a8-812e-1ba8e7e2775e"
	  },
	  "taskstatus": "FAILURE",
	  "taskinfo": "ValueError('Multiple treedefitems found for rank Continent')"
	}
	```
5. Go to https://ojsmnh20241003wb-v7962.test.specifysystems.org/specify/workbench/254/ (`v7.9.6.2`), logged in as `spadmin` in the Ichthyology collection
6. Validate the same data set
7. See no error

**Expected behavior**
This data set mapping is valid and should be validated without any issues.

**Screenshots**

https://github.com/user-attachments/assets/b970376a-a888-43f6-b906-f70fd1c7805b

**Crash Report**
macOS, Windows
db: `ojsmnh_2024_10_03_WB`
user: `spadmin`
collection: `Ichthyology`

**Reported By**
Paul at OJSMNH

### PR DESCRIPTION
**Pull request by acwhite211**
Fixes #5313

Fix the issue of workbench upload validation by avoiding error throwing due to the treedefid not being specified.

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions

1. Create a workbench upload mapping to multiple treedefitems.
2. Check that the validation runs successfully

Here is a specific DB to try out (ojsmnh_2024_10_03):
1. Go to https://ojsmnh20241003wb-production.test.specifysystems.org/specify/workbench/254/ (`v7.9.7` or `production`), logged in as `spadmin` in the Ichthyology collection
3. Validate the data set
4. See the following error:
	```
	{
	  "uploaderstatus": {
	    "operation": "validating",
	    "taskid": "26f94f3b-f6e8-42a8-812e-1ba8e7e2775e"
	  },
	  "taskstatus": "FAILURE",
	  "taskinfo": "ValueError('Multiple treedefitems found for rank Continent')"
	}
	```
5. Go to https://ojsmnh20241003wb-v7962.test.specifysystems.org/specify/workbench/254/ (`v7.9.6.2`), logged in as `spadmin` in the Ichthyology collection
6. Validate the same data set
7. See no error

### CODE REVIEW

**Comment by CarolineDenis** [comment]
When validating the dataset I have now an error "MultipleRanksInRow" on Taxon, I do not know if it's the expected behavior

**Review by emenslin — CHANGES_REQUESTED** [review]
Using the same db in the example I don't get that error message in this pr but, there is different validation behavior between this pr and 7.9.6.2. I don't know if this is expected or not so I wanted to point it out in case it is unintentional. 

7.9.6.2:

https://github.com/user-attachments/assets/c6db46ad-3e3c-42b8-9073-8390cbd530e5


This branch: 

https://github.com/user-attachments/assets/9e3dc4d9-c491-442c-9316-682c1aa73225

**Comment by acwhite211** [comment]
Ya, we made a decision in designing the new tree ranks upload code that a user could only upload data to one tree rank (aka. treedefitem) per row.  @grantfitzsimmons is this example WB upload from OJSMNH https://ojsmnh20241003wb-production.test.specifysystems.org/specify/workbench/254/ an old existing upload plan that we need to support, or is this a new upload plan that was recently created and they were just unaware of the one rank per row rule?

It seems maybe the confusion is that in this example OJSMNH upload plan, they are adding all the taxon ranks in the hierarchy path, when they really just need to set the final treedefitem name that the taxon belongs in.  Should we redesign the multiple taxon trees WB upload functionality to allow for multiple tree ranks to be set per row, as long as they follow a valid hierarchy path?

image

image

**Review by CarolineDenis — APPROVED** [review]

**Comment by acwhite211** [comment]
@specify/testing  Testing Note: the "MultipleRanksInRow" is expected to occur for now.  Supporting multiple ranks in a multi tree WB upload will be addressed in a different PR.  This PR is just for addressing the suppression of the ""Multiple treedefitems found for rank" error.

**Review by emenslin — APPROVED** [review]

**Comment by grantfitzsimmons** [comment]
>is this example WB upload from OJSMNH https://ojsmnh20241003wb-production.test.specifysystems.org/specify/workbench/254/ an old existing upload plan that we need to support, or is this a new upload plan that was recently created and they were just unaware of the one rank per row rule?

@acwhite211 This is an existing plan that we need to support. There is no existing rule that restricts each row in the WorkBench to creating only a single taxon record

**Review by sharadsw — APPROVED** [review]

**Review by Areyes42 — APPROVED** [review]

**Pull request merged**
