### PR TITLE
MOTs: Add frontend picklist for COType

### LINKED ISSUE #5169: MOTs: Create a frontend picklist for CollectionObjectType
`CollectionObjectType` needs to have a frontend picklist containing the names of all types in the CollectionObjectType table. This picklist will be used in the workbench - similar to how the Preptype picklist works for Preparations.

The frontend-only picklist will be used in the workbench when mapping a column to `CollectionObjectType -> name`

### PR DESCRIPTION
**Pull request by sharadsw**
Fixes #5169 

NOTES:
~Yay more MOTs~
Added a frontend picklist similar to the preptype picklist. All columns in the workbench mapped to CoType -> name should use this.

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions
- Create a workbench dataset with base table CollectionObjectType
- Map a column to `CollectionObjectType -> name`
- Click save
- [ ] Verify the column you mapped is a picklist containing all CollectionObjectTypes that exist in your db
- [ ] Re-run the same test with CollectionObject as the base table and mapping a column to `CollectionObject -> CollectionObjectType -> name`

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions
- Create a workbench dataset with base table CollectionObjectType
- Map a column to `CollectionObjectType -> name`
- Click save
- [x] Verify the column you mapped is a picklist containing all CollectionObjectTypes that exist in your db
- [x] Re-run the same test with CollectionObject as the base table and mapping a column to `CollectionObject -> CollectionObjectType -> name`

Cannot actually validate the dataset if it contains collectionobjecttype 

https://github.com/user-attachments/assets/7f9f4b4c-1d41-46bd-b0e3-21506acb5ad9

Also the table does not have an icon in the dataset  
Screenshot 2024-08-01 124028

**Comment by sharadsw** [comment]
@emenslin Thanks for testing! Opened a new issue #5175 for the validation error as it seems to involve fixing some backend logic. The icons should be fine when #2864 is fixed. Gonna open a new PR for that one.

**Review by emenslin — APPROVED** [review]
### Testing instructions
- Create a workbench dataset with base table CollectionObjectType
- Map a column to `CollectionObjectType -> name`
- Click save
- [x] Verify the column you mapped is a picklist containing all CollectionObjectTypes that exist in your db
- [x] Re-run the same test with CollectionObject as the base table and mapping a column to `CollectionObject -> CollectionObjectType -> name`

Looks good!

**Review by alesan99 — APPROVED** [review]
### Testing instructions
- Create a workbench dataset with base table CollectionObjectType
- Map a column to `CollectionObjectType -> name`
- Click save
- [x] Verify the column you mapped is a picklist containing all CollectionObjectTypes that exist in your db
- [x] Re-run the same test with CollectionObject as the base table and mapping a column to `CollectionObject -> CollectionObjectType -> name`

The picklist is working well on my db 👍👍

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-7-release-announcement/1979/1

**Pull request merged**
