### PR TITLE
Stop cloning the `barcode` field 

### LINKED ISSUE #3787: Cloned records should erase values from unique fields
**Describe the bug**
Consider the case of Preparation `barcode`. It must be unique at the collection level, yet when you clone a record (and its associated preparations), the barcode value is preserved. When saving, you then see a destructive error dialog saying that the barcode is not unique to the collection.

These fields need to be cleared when cloning to prevent situations like this one from taking place!

### PR DESCRIPTION
**Pull request by grantfitzsimmons**
Fixes #3787

**Steps to test:**
1. Go to a record that has a barcode value on the preparation form
2. Clone the record
3. Verify that the barcode is not being cloned

Tested locally and it seems to do the job.

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
Seems like this should also include `uniqueIdentifier`, no?

**Comment by melton-jason** [comment]
Yes this works! 
Although, it shouldn't be an issue in the first place, at least for uniqueIdentifier :sweat_smile: 
Can you check and see if uniqueIdentifier is able to be cloned on the models which now have it as a uniqueness rule (Collection Object, Collecting Event, Locality)? If it _is_ able to be cloned, then it means there was some issue from my commit: https://github.com/specify/specify7/commit/d0e5c75ae11153cc37b1a0c1f29293ee09a71322

This is because Specify does not use the `uniqueFields` Array to directly determine whether a resource can Clone a particular field. The entire logic is found in the `getUniqueFields` function. 

https://github.com/specify/specify7/blob/eb0a310bbc59089dfe840e94a842a29b7a18cecf/specifyweb/frontend/js_src/lib/components/DataModel/resource.ts#L270-L289
- - - 

This change is fine for `barcode`  because no other Model has a field directly called `barcode`, so this would only apply to Preparation.barcode. 
If you wanted to, you can include a comment stating _why_ barcode is in the Array in the first place (see https://github.com/specify/specify7/issues/2061#issuecomment-1439391935)

Alternatively, we can add barCode as a uniqueness to Preparation in `uniqueness_rules.json`. 
Maybe not the best solution, as it would have no effect _other_ than to be included in the Preparation uniqueness rules when calling `getUniqueFields`

**Comment by grantfitzsimmons** [comment]
@melton-jason Thanks for your comment Jason! 

Feel free to change how this is implemented any way you'd like, I just got tired of accidentally cloning barcodes. 😆

**Review by maxxxxxdlp — CHANGES_REQUESTED** [review]
While this might fix it, it is probably not a correct solution.

Is barcode a unique field?

If not, then make it into a unique field - that will fix this issue.

If it is a unique field, the a programmer needs to review the code that determines if field is unique - that will fix this issue. That will fix it not just for this field, but for all fields like this in the future

**Comment by maxxxxxdlp** [comment]
Of course, if you are looking for a very-short term solution, like something sp6 would go for, then what you did would work

**Comment by maxxxxxdlp** [comment]
Reading the previous comments, I would be for editing the `uniqueness_rules.json` to designate the field as unique.

> Maybe not the best solution, as it would have no effect other than to be included in the Preparation uniqueness rules when calling getUniqueFields

@melton-jason can you explain why? If you designate a field as unique as far as front-end aware, then the uniqueness business rule will be active (in addition to fixing the clone issue)

You might have already mentioned it in https://github.com/specify/specify7/issues/2061#issuecomment-1439391935
If so, can you please double-check if this field is really the only one that handles uniqueness in this way?

Also, I heard you were working on ability to mark any field unique - would that feature create a better solution for this issue?

**Pull request closed without merging**
