### PR TITLE
Remove unecessary styling in fromatter table

### LINKED ISSUE #4622: Table format dialog does not expand when the fields grid-table goes beyond the view area.
**Describe the bug**
The table format dialog does not expand when the fields grid-table goes beyond the view area.

**To Reproduce**

1. Log into `umherb_1_10_24` as `HerbAdmin`
1. Go to https://umherb11024-issue-1959.test.specifysystems.org/specify/resources/app-resource/92/formatter/Determination/61
2. Create a new table format for "Determination"
3. Add a field
4. See that the line is wider than the dialog, resulting in a scrollbar

**Expected behavior**
When a new field is added, the dialog should become wider to ensure there is room to display the entire field line, or it should not escape the dialog width.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/bdfcf18d-9412-4023-b8c5-9ab93f5ff70c

image

If you remove the `min-w-[35rem]` class, it also appears correctly in the dialog. This could also be a solution:

https://github.com/specify/specify7/assets/37256050/693a5ae5-6588-4296-9b17-2cb99e2168fc

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4622

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

go in app resources
select record formatters
create a new table format or select an existing one
add a fields
reduce the dialog to its minimum width

- [ ] Verify that the lines are not wider than the dialog at opening
- [ ] If you resize the dialog, the div containing the lines should have a scroll bar

### CODE REVIEW

**Review by pashiav — APPROVED** [review]
### Testing instructions

go in app resources
select record formatters
create a new table format or select an existing one
add a fields
reduce the dialog to its minimum width

- [X] Verify that the lines are not wider than the dialog

Looks good!
edge | pr
Screen Shot 2024-03-11 at 4 25 56 PM

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

go in app resources
select record formatters
create a new table format or select an existing one
add a fields
reduce the dialog to its minimum width

- [ ] Verify that the lines are not wider than the dialog

When you try to map a field the line expands outside of the window.
Also when you map a longer field name with the window expanded to the minimum width the field name does not fit properly in the box. 
A good solution to this could be to make the minimum window length bigger so it can't be shrunk down to this size. 

https://github.com/specify/specify7/assets/150940840/53c7fa81-9fc3-429e-91ad-84af5ac06bb3

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

go in app resources
select record formatters
create a new table format or select an existing one
add a fields
reduce the dialog to its minimum width

- [ ] Verify that the lines are not wider than the dialog at opening
- [x] If you resize the dialog, the div containing the lines should have a scroll bar

When you make a new table format it opens with the minimum size and is hard to navigate. 

https://github.com/specify/specify7/assets/150940840/35b11c73-f931-4a69-a5a6-2363fc3c030e

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

go in app resources
select record formatters
create a new table format or select an existing one
add a fields
reduce the dialog to its minimum width

- [ ] Verify that the lines are not wider than the dialog at opening
- [ ] If you resize the dialog, the div containing the lines should have a scroll bar
Looks the same as it does in edge 

https://github.com/specify/specify7/assets/150940840/428dc892-e5e9-43d8-b904-7b144f618df5

**Comment by CarolineDenis** [comment]
cannot reproduce issue anymore

**Comment by maxpatiiuk** [comment]
@CarolineDenis, this is a small thing, but when you close a PR unmerged, could you also delete the branch by clicking on this button?

Screenshot 2024-03-16 at 09 20 32

Don't worry - deleting the branch does not delete the commits right away - even if branch is deleted, you would still be able to see what changes were made in an unmerged PR and re-apply those changes in the future if necessary

We have 146 branches right now, which is way too much and should be cleaned up regularly - https://github.com/specify/specify7/branches

**Pull request closed without merging**
