### PR TITLE
Add ageCitations

### LINKED ISSUE #5340: Relative and Absolute Age do not link to corresponding citation tables in the data model
## How it is currently

See that there is not a `relativeAgeCitations` and `absoluteAgeCitations` relationship

image

image

## How it should be

image

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #5340

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- [ ] verify age citations (for both relative and absolute) are present in the data-model tab 
- [ ] verify you can add it to view def

### CODE REVIEW

**Comment by CarolineDenis** [comment]
TODO: 
- rename migration once the other ones in 9.8 are merged in prod

**Review by sharadsw — APPROVED** [review]
Looks good! Just a reminder: when you pull production and rename the migration later, make sure to regenerate the frontend types as prod will have new frontend types at that point.

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

- [x] verify age citations (for both relative and absolute) are present in the data-model tab 
- [ ] verify you can add it to view def 

The age citations relationships are not present in the schema config for absolute and relative age, however, in the age citations you can see the absolute or relative age relationship. I know this wasn't a check but I assume it should be present in the schema config if it is present in the data model and one side of the relationship shows it. 

https://github.com/user-attachments/assets/3257c7e2-90df-418e-a8fe-cf857298acb4

**Review by emenslin — APPROVED** [review]
### Testing instructions

- [x] verify age citations (for both relative and absolute) are present in the data-model tab 
- [x] verify you can add it to view def 

Looks good, the citations are now present in the schema config as well.

**Review by alesan99 — APPROVED** [review]
### Testing instructions

- [x] verify age citations (for both relative and absolute) are present in the data-model tab 
- [x] verify you can add it to view def

Tested on `kubirds_8_25_23`. They appear everywhere including schema config 👍👍👍

**Review by acwhite211 — APPROVED** [review]

**Pull request merged**
