### PR TITLE
Move side bar pref to ui + rename

### LINKED ISSUE #4305: Remove redundancy in the sidebar background preference
image

The caption for this preference is:
`Light sidebar background in light mode`

There are two items to choose from:
```
Dark
Match theme color
```

This is not communicated well and is redundant. It would

### **Solution:**
The caption should be:
`Sidebar theme`

The items to choose from should be:
```
Light (in light mode)
Dark
```

This should also probably be under 'Theme' in the User Interface area, not under Appearance. This is essentially an extension of that, so we should group them together logically.

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4305

### CODE REVIEW

**Comment by CarolineDenis** [comment]
Screenshot 2024-01-03 at 1 33 37 PM

**Review by maxpatiiuk — APPROVED** [review]
@grantfitzsimmons can we mention in the release notes that if they had this pref set, they would have to set it again since it has been moved?

or is it important enough for us to provide a small migration for this?

**Review by emenslin — CHANGES_REQUESTED** [review]
The sidebar theme button is not there, I checked under ui and appearance and I did not see it. 
Screenshot 2024-01-04 100709
Screenshot 2024-01-04 100721

**Comment by CarolineDenis** [comment]
@emenslin, it's because it's available only for light mode

**Review by emenslin — APPROVED** [review]
Looks good now!
Screenshot 2024-01-04 111948

**Review by bronwyncombs — APPROVED** [review]
Working as expected, looks good!

Screenshot 2024-01-04 at 11 47 08 AM

**Comment by grantfitzsimmons** [comment]
> can we mention in the release notes that if they had this pref set, they would have to set it again since it has been moved?

I think we'll just mention this in the release notes. I don't want to do a migration for it, and only one user that I know of has configured this since it's a very new feature.

**Pull request merged**
