### PR TITLE
Unhide all geo tables

### PR DESCRIPTION
**Pull request by sharadsw**
Reverts specify/specify7#5236

### Checklist
- [x] Self-review the PR after opening it to make sure the changes look good and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions
- Verify geo tables (CollectionObjectGroup, CollectionObjectType, CollectionObjectGroupType, CollectionObjectGroupJoin) are visible in:
   - [ ] Data Entry
   - [ ] Queries
   - [ ] Workbench
   - [ ] Schema Config
   - [ ] Uniqueness Rules mapper (the relations involving geo tables should be visible when creating uniqueness rules)

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Review by CarolineDenis — APPROVED** [review]

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions
- Verify geo tables (CollectionObjectGroup, CollectionObjectType, CollectionObjectGroupType, CollectionObjectGroupJoin) are visible in:
   - [x] Data Entry
   - [x] Queries
   - [x] Workbench
   - [x] Schema Config
   - [ ] Uniqueness Rules mapper

In the uniqueness rules mapper the fields do not show up properly whether any of the geo tables are being used as the base table or as the scope. 

https://github.com/user-attachments/assets/1fb4ae96-59d2-4686-a9ac-5bdc097cec3c


Screenshot 2024-10-03 103157

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions
- Verify geo tables (CollectionObjectGroup, CollectionObjectType, CollectionObjectGroupType, CollectionObjectGroupJoin) are visible in:
   - [x] Data Entry
   - [x] Queries
   - [x] Workbench
   - [x] Schema Config
   - [ ] Uniqueness Rules mapper (the relations involving geo tables should be visible when creating uniqueness rules)

The fields and relationships in uniqueness rules for the 4 new tables are still broken and just show up as empty

https://github.com/user-attachments/assets/cd41f862-5761-493e-a408-93278ec0f086


Also when you add a new COT uniqueness rule you can type into the field that should be read only. I checked in the other tables and it doesn't happen so I think it has to do with the fields being blank and there being a duplicate error 

https://github.com/user-attachments/assets/020c234c-0abd-4eaa-96c1-428836ab6faa

**Review by emenslin — APPROVED** [review]
### Testing instructions
- Verify geo tables (CollectionObjectGroup, CollectionObjectType, CollectionObjectGroupType, CollectionObjectGroupJoin) are visible in:
   - [x] Data Entry
   - [x] Queries
   - [x] Workbench
   - [x] Schema Config
   - [x] Uniqueness Rules mapper (the relations involving geo tables should be visible when creating uniqueness rules)

Looks good, all fields are showing up and no more weird behavior!

**Review by Areyes42 — APPROVED** [review]
### Testing instructions

-   Verify geo tables (CollectionObjectGroup, CollectionObjectType, CollectionObjectGroupType, CollectionObjectGroupJoin) are visible in:
    -   [x] Data Entry
    -   [x] Queries
    -   [x] Workbench
    -   [x] Schema Config
    -   [x] Uniqueness Rules mapper (the relations involving geo tables should be visible when creating uniqueness rules)
***
Tables are viewable and look good in all forms, great job! 👍

**Pull request merged**
