### PR TITLE
Don't set scope for existing resources

### LINKED ISSUE #3104: Not all resources are displaying in the sidebar
image

Saw on the `unitec` Specify Cloud deployment, can be recreated on the test panel.

image

See that Global Prefs is not displaying in the app resources sidebar, this is on my local machine

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #3104

### CODE REVIEW

**Comment by chanulee1** [comment]
How do I test this?

**Comment by maxxxxxdlp** [comment]
If #3104 does not happen anymore, this is fixed (make sure global app resources are shown)

**Review by chanulee1 — CHANGES_REQUESTED** [review]
Resources created at global level not displayed in sidebar.

https://herbrbge11723-issue-3104.test.specifysystems.org/specify/resources/app-resource/78/

Also, creating a resource at discipline level automatically places it under a collection.

https://user-images.githubusercontent.com/103299204/223857998-5472993e-9027-4e31-baea-f937cc97e5b2.mp4

https://coldfish-issue-3104.test.specifysystems.org/specify/resources/

**Review by chanulee1 — APPROVED** [review]
Looks good.

**Review by melton-jason — APPROVED** [review]
Everything seems good! tested on `willemCatNo` and could not recreate the issues @chanulee1 discovered earlier in the PR. 
Every App Resource and View Set seems to be displayed in the side bar

pr_3111

**Pull request merged**
