### PR TITLE
Restore the missing border for query select items in the report query dialog

### LINKED ISSUE #5149: In light mode field outline is missing in report query
**Describe the bug**
When opening a report and then clicking query the outlines for the fields are missing 

**To Reproduce**

1. Go to reports in the navigation bar
2. Click on any report/label 
3. Select query 

**Expected behavior**
They should have the backgrounds like they did in 7.9.5

**Screenshots**
edge: 
Screenshot 2024-07-26 151809

7.9.5:
Screenshot 2024-07-26 152305

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: kufish2_12
- Collection name: voucher
- User Name: spfishadmin

### PR DESCRIPTION
**Pull request by grantfitzsimmons**
Fixes #5149

It should appear as they did in `v7.9.5`, before the change in https://github.com/specify/specify7/commit/8c80571775465202b166463b0a5b4c209457319c
The borders for query items should **not** be extra bold as it was https://github.com/specify/specify7/issues/4287

> **Describe the bug**
> When opening a report and then clicking query the outlines for the fields are missing 
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to reports in the navigation bar
> 2. Click on any report/label 
> 3. Select query 
> 4. See error
> 
> **Expected behavior**
> They should have the backgrounds like they did in 7.9.5
> 
> **Screenshots**
> edge: 
> Screenshot 2024-07-26 151809
> 
> 7.9.5:
> Screenshot 2024-07-26 152305

**Testing Instructions:**
- [ ] Verify that query lines have appropriately sized borders in 
   - [ ] Query Builder in light mode
   - [ ] Query Builder in dark mode
   - [ ] Report/Label Query Dialogs in light mode
   - [ ] Report/Label Query Dialogs in dark mode

### CODE REVIEW

**Review by alesan99 — APPROVED** [review]
- [x] Verify that query lines have appropriately sized borders in 
   - [x] Query Builder in light mode
   - [x] Query Builder in dark mode
   - [x] Report/Label Query Dialogs in light mode
   - [x] Report/Label Query Dialogs in dark mode
   
   Works! The borders appear as they should and Queries and Reports match up 👍👍👍

**Review by emenslin — APPROVED** [review]
**Testing Instructions:**
- [x] Verify that query lines have appropriately sized borders in 
   - [x] Query Builder in light mode
   - [x] Query Builder in dark mode
   - [x] Report/Label Query Dialogs in light mode
   - [x] Report/Label Query Dialogs in dark mode

Borders look good 🎉

**Review by CarolineDenis — APPROVED** [review]

**Review by melton-jason — COMMENTED** [review]
Nice work!

https://github.com/specify/specify7/blob/526a059135792405f390ae76736688f60c75348a/specifyweb/frontend/js_src/lib/components/WbPlanView/CustomSelectElement.tsx#L591

One small comment here, can this line be removed? 
Pretty sure it is redundant now, as the component always has the `border border-gray-500` class.

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-7-release-announcement/1979/1

**Pull request merged**
