### PR TITLE
Allow running query with invalid search parameters

### LINKED ISSUE #2185: Invalid query search parameters should not prevent running query
Query builder's search filters may be considered invalid because of a bug, a limitation of the validation system or because user is looking for invalid data. (see #1283 for an example)

Searching with invalid fields does not corrupt data (unlike saving records with invalid data), thus the validation system should not prevent running a query that has invalid filters

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #2185

Entering invalid parameters still shows that they are invalid, but does not prevent running the query

### CODE REVIEW

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
The query ignores the invalid search term:

image

You can try it here:
https://kufish-issue-2185.test.specifysystems.org/specify/query/42/

user: `abentley`

**Comment by maxxxxxdlp** [comment]
Looks like it didn't like invalid values and used send empty strings instead. Fixed.

Though, now the back-end is complaining about invalid values:

Screen Shot 2022-09-20 at 12 55 38

@benanhalt

**Comment by benanhalt** [comment]
I fixed the backend choking on values that don't match the formatter. I'm seeing "format doesn't match" popup though that doesn't scroll with the rest of the page.
image

**Comment by maxxxxxdlp** [comment]
The popup is generated by your browser. Unless the issue get's fixed by Firefox, there isn't much we can do

**Comment by benanhalt** [comment]
This should fix https://github.com/specify/specify7/issues/1283#issuecomment-1256589366

**Comment by grantfitzsimmons** [comment]
image

**Review by grantfitzsimmons — APPROVED** [review]

**Pull request merged**
