### PR TITLE
Allow catalogNumber format to be determined by CollectionObjectType

### LINKED ISSUE #5232: Implement Catalog Numbering Configurations Based on COT
**Description:**  
We need to develop a system that allows for multiple catalog number formats based on either the collection or COT. This includes options for auto-numbering based on type and shared formats across multiple COTs.

**Acceptance Criteria:**
-  Users can set a single catalog number format for all COs within a collection (`CatalogFormatNumName` in the `collection` table, this is already supported)
-  Users can define multiple formats for COs within a specific COT (done in the XML app resource `UIFieldFormatters`)
-  Implement auto-numbering based on the selected type for each COT.
-  Allow multiple COTs to share the same catalog number format (they can use the same `CatalogFormatNumName` across multiple COTs, and auto-numbering should be shared)
-  Update the `CollectionObjectType` table to include a `CatalogFormatNumName`.

**Default numbering behavior:**
We need to also establish a default logic for assigning catalog numbers. If a COT does not have a specific series set, it should default to the collection’s catalog number format.

**Acceptance Criteria:**
-  If no COT-specific format is set, the system defaults to the collection’s format.
-  Ensure that the default settings are clearly documented and accessible to users.

### PR DESCRIPTION
**Pull request by melton-jason**
Fixes #5232, #5233 
See #5234

⚠️ **Note:** This PR affects database migrations. See [migration testing instructions](https://specify.github.io/testing/pull_requests.html#prs-tagged-with-label-migration).

Aside from implementing #5232 and #5233, there are some other improvements in this PR!

**Schema Config**

- When selecting a Field Format in the Schema Configuration tool, Specify now groups field formatters for the field they selected (Field Formats that explicitly reference the field in `fieldName=fieldname`) above the rest

Screenshot 2024-12-03 at 3 08 19 PM

**Migrations**
There were some bugs in other migrations which used the functions defined in [specifyweb/specify/update_schema_config.py](https://github.com/specify/specify7/blob/production/specifyweb/specify/update_schema_config.py). These bugs have been fixed in this PR, and a migration has been written to fix these bugs for databases already affected: [specify/0017_schemaconfig_fixes.py](https://github.com/specify/specify7/blob/issue-5232/specifyweb/specify/migrations/0017_schemaconfig_fixes.py)

**UIFormatter picklists for Collection -> catalogNumFormatName and CollectionObjectType -> catalogNumberFormatName**
- Everywhere in the application*, these fields will now appear as a picklist whose items are the names of `CO -> catalogNumber` Field Formatters

Screenshot 2024-12-03 at 3 21 02 PM

*on the DataEntry Form, they will only appear as a PickList if `uitype="combobox"` is used on the form definition

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions

- Define a Field Format for `Collection Object -> catalogNumber` which is different than the current `Collection -> Catalog Num Format Name`
  - An example field format called `Rocks` is provided below:  
```xml
<format system="false" name="Rocks" class="edu.ku.brc.specify.datamodel.CollectionObject" fieldname="catalogNumber" default="false">
	<autonumber>edu.ku.brc.af.core.db.AutoNumberGeneric</autonumber>
	<field type="constant" size="4" value="ROCK"/>
	<field type="separator" size="1" value="-"/>
	<field type="numeric" size="6" inc="true"/>
</format>
```
- Go to the Data Entry form to create a new Collection Object Type
- [ ] Ensure the Catalog Number Format Name picklist shows all Catalog Number Field Formats 
- Save the Collection Object Type with a Catalog Number Format Name that is different than the Collection -> catalogNumFormatName
- Make sure `collectionObjectType` is on the Collection Object form 
- Go to the Data Entry form to create a new Collection Object 
- Change the Collection Object Type of the Collection Object to be that which you previously saved
- [ ] Ensure the Catalog Number of the Collection Object is replaced with the pattern of the new 
- (If needed) Modify the Catalog Number so that it matches the format of formatter
- [ ] Save the Collection Object with the new format

### CODE REVIEW

**Review by alesan99 — CHANGES_REQUESTED** [review]
### Testing instructions

- Define a Field Format for `Collection Object -> catalogNumber` which is different than the current `Collection -> Catalog Num Format Name`
  - An example field format called `Rocks` is provided below:  
- Go to the Data Entry form to create a new Collection Object Type
- [x] Ensure the Catalog Number Format Name picklist shows all Catalog Number Field Formats 
- Save the Collection Object Type with a Catalog Number Format Name that is different than the Collection -> catalogNumFormatName
- Make sure `collectionObjectType` is on the Collection Object form 
- Go to the Data Entry form to create a new Collection Object 
- Change the Collection Object Type of the Collection Object to be that which you previously saved
- [x] Ensure the Catalog Number of the Collection Object is replaced with the pattern of the new 
- (If needed) Modify the Catalog Number so that it matches the format of formatter
- [ ] Save the Collection Object with the new format

Functionality wise it seems to be working 👍👍

On the CO form it looks like the form needs an extra update in order to be okay with the new format.
Clicking the save button twice does the trick, or typing in the new catalog number manually.

https://github.com/user-attachments/assets/549ed44c-06a0-4a2d-864a-39790fb2eef1

The issue also persists if you switch to a different CO of a different type in the same tab.

**Comment by CarolineDenis** [comment]
@alesan99 
for 

> On the CO form it looks like the form needs an extra update in order to be okay with the new format.
> Clicking the save button twice does the trick, or typing in the new catalog number manually.

That is good for this pr :+1:

**Review by CarolineDenis — APPROVED** [review]

**Review by alesan99 — APPROVED** [review]

**Review by bronwyncombs — COMMENTED** [review]
- Define a Field Format for `Collection Object -> catalogNumber` which is different than the current `Collection -> Catalog Num Format Name`
  - An example field format called `Rocks` is provided below:  
- Go to the Data Entry form to create a new Collection Object Type
- [X] Ensure the Catalog Number Format Name picklist shows all Catalog Number Field Formats 
- Save the Collection Object Type with a Catalog Number Format Name that is different than the Collection -> catalogNumFormatName
- Make sure `collectionObjectType` is on the Collection Object form 
- Go to the Data Entry form to create a new Collection Object 
- Change the Collection Object Type of the Collection Object to be that which you previously saved
- [X] ** Ensure the Catalog Number of the Collection Object is replaced with the pattern of the new 
- (If needed) Modify the Catalog Number so that it matches the format of formatter
- [X] Save the Collection Object with the new format

Catalog Number Format Name list appears correctly on COT form and in schema config. COT pick list on CO also displays correctly. Format switch in field functions normally other than needing to click elsewhere on the form to dismiss initial save block. 

** I noticed that the CO form header, that displays the catalog number format before a catalog number is saved to the form, does not reflect the format chosen with the COT picklist. If there are two COTs available, this header is consistently opposite of the one on the form. 

https://github.com/user-attachments/assets/7ba80b73-9ccb-4387-a3a1-c4d16e0295ae

I also saw this on the catalog number field after saving: 
Screenshot 2024-12-05 at 1 06 31 PM

**Review by combs-a — CHANGES_REQUESTED** [review]
### Testing instructions

- Define a Field Format for `Collection Object -> catalogNumber` which is different than the current `Collection -> Catalog Num Format Name`
  - An example field format called `Rocks` is provided below:  
- Go to the Data Entry form to create a new Collection Object Type
- [X] Ensure the Catalog Number Format Name picklist shows all Catalog Number Field Formats 
- Save the Collection Object Type with a Catalog Number Format Name that is different than the Collection -> catalogNumFormatName
- Make sure `collectionObjectType` is on the Collection Object form 
- Go to the Data Entry form to create a new Collection Object 
- Change the Collection Object Type of the Collection Object to be that which you previously saved
- [X] Ensure the Catalog Number of the Collection Object is replaced with the pattern of the new 
- (If needed) Modify the Catalog Number so that it matches the format of formatter
- [X] Save the Collection Object with the new format

Had a brief strange thing happen where it wasn't switching the format, but seems to have fixed itself on a reload (without clearing cache) so probably okay. Same thing as Alejandro where there's a save blocker incorrectly placed, but clicking anywhere on the form and not just the save blocker clears it.

I didn't run into Bronwyn's second issue, but I did see the same thing with the header. I do remember there being issues with the header update being a bit slow so maybe it's something like that. Will this be addressed in this PR?

Good work Jason! Everything looks good besides the small header thing. :tada:

**Comment by melton-jason** [comment]
There is an Issue already about the header being 'slow' to update: #3579. 
Although it can probably be renamed, as it's not just contained to Tree forms 😅

**Review by combs-a — DISMISSED** [review]
See above comments for approval reason; header lag is the separate issue that Jason linked 👍

**Review by maxpatiiuk — APPROVED** [review]

**Pull request merged**
