### PR TITLE
Add draggable feature in query builder using @shopify/draggable library 

### LINKED ISSUE #1282: Bring back drag sort in Query Builder
Add a draggable region to query lines like this:
image

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixed #1282

### CODE REVIEW

**Review by chanulee1 — CHANGES_REQUESTED** [review]
Reordering query lines does not seem to affect the order of fields in query results. Also, the query lines seem to contain an extra bullet point when dragged.

https://user-images.githubusercontent.com/103299204/224768747-6b0a234b-6123-4e5d-8859-2e55a9910869.mp4

**Review by maxxxxxdlp — APPROVED** [review]

**Review by chanulee1 — CHANGES_REQUESTED** [review]
Dragged row is not highlighted after dropping. Only clicking can highlight lines. Issue?

**Comment by maxxxxxdlp** [comment]
Good idea - that would be nice
@CarolineDenis just calling the callback that focuses a line with newIndex after calling handleFieldsChange should do it

@chanulee1 could you also test trying to move a line when it has one of the combo boxes open? do combo boxes close, or get dragged alone? 😄

**Comment by chanulee1** [comment]
Moving a line that has a combo box open closes the combo box.

**Comment by maxxxxxdlp** [comment]
Awesome

**Review by maxxxxxdlp — APPROVED** [review]

**Comment by realVinayak** [comment]
Weird edge case when using this feature in a dialog
Screenshot (47)

**Comment by maxxxxxdlp** [comment]
> Weird edge case when using this feature in a dialog

What is the issue? Please provide more information.
Please also open a new issue for that as this pull request is already closed

**Pull request merged**
