### PR TITLE
Extend Batch Attachment Uploader support to more tables

### LINKED ISSUE #5331: Add Preparation / Barcode to the Batch Attachment Uploader
> ...the path chooser in the **Batch Attachment Uploader** is rather limited:
> 
> * `Collection Object/Cat #`
> * `Collection Object/Prev/Exch #`
> * `Taxon/Full Name`
> * `Collecting Event/GUID`
> * `Collecting Event/Field #`
> * `Loan/Loan #`
> * `Accession/Accession #`
> * `Gift/Gift #`
> * `Borrow/Invoice #`
> 
> I reckon it was a matter of including most useful/used/requested attachment tables.
> 
> :question: what if one would like to upload and match attachments to another table?
> 
> In French Guiana Herbarium (CAY) we have digitalized most dried sheets and named them accordingly to the **preparation barcode**. Therefore it would be straightforward to link them as `Preparation Attachments`. Should we send a *feature request* to update the `B.A.U.` ?

**Requested by:** Philippe Verley at IRD on the [Speciforum](https://discourse.specifysoftware.org/t/extend-batch-attachment-uploader/2040)

### PR DESCRIPTION
**Pull request by grantfitzsimmons**
Fixes #5331/#5252

image

Adds support for uploading bulk attachments for the following tables:
* Storage (Full Name)
* Preparation (Barcode, GUID)
* Treatment Event (FieldNumber)
* Exchange In (ExchangeInNumber)
* Exchange Out (ExchangeOutNumber)
* Reference Work (Title, GUID)
* Locality (UniqueIdentifier, GUID)
* Permit (PermitNumber)
* Agent (GUID)
* Collecting Trip (CollectingTripName)
* Deaccession (DeaccessionNumber)

### Testing Instructions

- [ ] Upload attachments using the Batch Attachment Uploader to the following tables:
   - [ ] Storage (Full Name)
   - [ ] Preparation (Barcode, GUID)
   - [ ] Treatment Event (FieldNumber)
   - [ ] Exchange In (ExchangeInNumber)
   - [ ] Exchange Out (ExchangeOutNumber)
   - [ ] Reference Work (Title, GUID)
   - [ ] Locality (UniqueIdentifier, GUID)
   - [ ] Permit (PermitNumber)
   - [ ] Agent (GUID)
   - [ ] Collecting Trip (CollectingTripName)
   - [ ] Deaccession (DeaccessionNumber)
- [ ] Test rolling back the uploads

### CODE REVIEW

**Comment by realVinayak** [comment]
Is it about time to just make it generic, with using any field from any table that supports attachments? Trivial for fields. It's a bit involved to span relationships (to-manys are a no-go. to-ones, maybe --- but at that point, might as well support in workbench).

**Comment by grantfitzsimmons** [comment]
> Is it about time to just make it generic, with using any field from any table that supports attachments? Trivial for fields. It's a bit involved to span relationships (to-manys are a no-go. to-ones, maybe --- but at that point, might as well support in workbench).

💯 Absolutely, but we need a full-time or student developer to do that. This is as far as I can take it (in my working hours), so it would be great to see if we can make that change into the future.

**Comment by grantfitzsimmons** [comment]
@CarolineDenis Whenever we have a moment, it would be great to include this ASAP, as RBGE and others need to upload preparation attachments by barcode.

**Review by maxpatiiuk — APPROVED** [review]

**Review by CarolineDenis — APPROVED** [review]

**Review by pashiav — CHANGES_REQUESTED** [review]
Leaving this comment for now until I complete the review.

When trying to upload to Storage (Full Name), the upload says it is interrupted and this peculiar timer pops up: 
https://cuic22024-issue-5331.test.specifysystems.org/specify/attachments/import/3

https://github.com/user-attachments/assets/f2edee99-d2dd-41a4-bf57-79970dec529b

**Comment by grantfitzsimmons** [comment]
@pashiav The issue here is that in that database there is only one Storage node– `Site`.

It does not have a parent (required for a tree node), therefore the record cannot be saved. You can see the same issue if you try to add the attachment to that node. I could recreate this with Taxon Full Name if you name it "Life".

Here's the traceback:
```
Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/specify7/specifyweb/specify/views.py", line 35, in wrapped
    return view(request, *args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/opt/specify7/specifyweb/specify/views.py", line 71, in view
    return dispatch_func(request, *args, **kwargs)
  File "/opt/specify7/specifyweb/specify/api.py", line 175, in resource_dispatch
    obj = put_resource(request.specify_collection,
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/specify7/specifyweb/specify/api.py", line 720, in put_resource
    return update_obj(collection, agent, name, id, version, data)
  File "/opt/specify7/specifyweb/specify/api.py", line 743, in update_obj
    obj.save(force_update=True)
  File "/opt/specify7/specifyweb/specify/models.py", line 22, in custom_save
    save_auto_timestamp_field_with_override(super(self.__class__, self).save, args, kwargs, self)
  File "/opt/specify7/specifyweb/specify/model_timestamp.py", line 28, in save_auto_timestamp_field_with_override
    return save_func(*args, **new_kwargs)
  File "/opt/specify7/specifyweb/specify/tree_extras.py", line 85, in save
    "parentid": self.parent.id,
AttributeError: 'NoneType' object has no attribute 'id'
```

This should be written up as a separate issue, though I imagine it is a low priority.

**Review by emenslin — APPROVED** [review]
### Testing Instructions

- [x] Upload attachments using the Batch Attachment Uploader to the following tables:
   - [x] Storage (Full Name)
   - [x] Preparation (Barcode, GUID)
   - [x] Treatment Event (FieldNumber)
   - [x] Exchange In (ExchangeInNumber)
   - [x] Exchange Out (ExchangeOutNumber)
   - [x] Reference Work (Title, GUID)
   - [x] Locality (UniqueIdentifier, GUID)
   - [x] Permit (PermitNumber)
   - [x] Agent (GUID)
   - [x] Collecting Trip (CollectingTripName)
   - [x] Deaccession (DeaccessionNumber)
- [x] Test rolling back the uploads

Looks good, I could successfully upload and roll back all tables

**Review by alesan99 — APPROVED** [review]
### Testing Instructions

- [x] Upload attachments using the Batch Attachment Uploader to the following tables:
   - [x] Storage (Full Name)
   - [x] Preparation (Barcode, GUID)
   - [x] Treatment Event (FieldNumber)
   - [x] Exchange In (ExchangeInNumber)
   - [x] Exchange Out (ExchangeOutNumber)
   - [x] Reference Work (Title, GUID)
   - [x] Locality (UniqueIdentifier, GUID)
   - [x] Permit (PermitNumber)
   - [x] Agent (GUID)
   - [x] Collecting Trip (CollectingTripName)
   - [x] Deaccession (DeaccessionNumber)
- [x] Test rolling back the uploads

Everything is working as expected 👍👍

**Review by pashiav — APPROVED** [review]
### Testing Instructions

- [X] Upload attachments using the Batch Attachment Uploader to the following tables:
   - [X] Storage (Full Name)
   - [X] Preparation (Barcode, GUID)
   - [X] Treatment Event (FieldNumber)
   - [X] Exchange In (ExchangeInNumber)
   - [X] Exchange Out (ExchangeOutNumber)
   - [X] Reference Work (Title, GUID)
   - [X] Locality (UniqueIdentifier, GUID)
   - [X] Permit (PermitNumber)
   - [X] Agent (GUID)
   - [X] Collecting Trip (CollectingTripName)
   - [X] Deaccession (DeaccessionNumber)
- [X] Test rolling back the uploads

---
Ran into an issue where `Storage (full name)` was not matched to anything, but it is a separate issue. 

Looks good!

**Pull request merged**
