### PR TITLE
Increase fetch limit for tree search

### LINKED ISSUE #3053: Taxon Tree search only returns 20 results and hides all others
_Edit: See [this comment](https://github.com/specify/specify7/issues/3053#issuecomment-2140938307) for conclusion of what the issue is._

image

image

>Thanks for taking a look. We are finding that synonyms are coming up when we search in the taxon tree e.g. Allania insignis is in the tree
>
>But when searching on just the species epithet, we are not seeing it in the search results

**Expected Behavior:**

image

Just as you can search for synonymized Genus records, you should be able to search for synonymized Species

**Reported By:** Robyn at RBGE

Use a copy of the RBGE database with the following tree location:

```
/specify/tree/taxon/?conformation=%7E%7E1%7E309038-%7E6%7E87-%7E309042%7E1355%7E8043%7E208193--%7E16844%7E100816--%7E9689%7E64193--%7E12594--%7E1596%7E20415--%7E1668%7E10855%7E153340--%7E21596--%7E1684%7E13290----%7E2%7E18-%7E82-%7E34%7E346%7E679%7E6808%7E258876-----%7E38-%7E13-%7E306361-%7E65-%7E70-%7E74%7E1736%7E2897----%7E5%7E35%7E305318%7E138%7E1063-------
```

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3053

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Open tree viewer 
- Search for a string 
- [ ] verify that the results are not limited to a list of 20 anymore. 
- [ ] search for  insignis in herb_rbge and verify Allania insignis is returned

### CODE REVIEW

**Review by combs-a — APPROVED** [review]
### Testing instructions

- Open tree viewer 
- Search for a string 
- [X] verify that the results are not limited to a list of 20 anymore. 
- [X] search for  insignis in herb_rbge and verify Allania insignis is returned 

Allania insignis is returned now when you look up insignis! 🎉 Also worked with the other nodes that I found had the same problem in the issue.

**Review by emenslin — APPROVED** [review]
### Testing instructions

- Open tree viewer 
- Search for a string 
- [x] verify that the results are not limited to a list of 20 anymore. 
- [x] search for  insignis in herb_rbge and verify Allania insignis is returned 

Looks good! 

--- 

Cannot consistently recreate so I will not request changes but I am running into an issue that I cannot seem to recreate in edge so I want to make note of it. Sometimes after searching one thing (e.g. insignis) and then starting another search (e.g. sla) the results for the previously searched term will appear and the current search is disregarded. Once again I cannot consistently recreate in this branch or in edge so for now I am just making note of it 

Start of video was when I discovered the issue

https://github.com/user-attachments/assets/58693beb-8389-42a5-ab66-cee82e267d65

**Review by sharadsw — APPROVED** [review]

**Review by maxpatiiuk — APPROVED** [review]
this is ok, but long-term we need to implement a mechanism similar to what query results has, where it fetches only small number initially, but then more as you scroll down

increasing the limit comes with two disadvantages:
- there is still a limit, meaning valid use cases could be cut off
- at the same time, if you type something like "a", it's going to return a bunch of records (200), which both puts needless pressure on the back-end and freezes the UI for a moment - bad

always taking the easy solution is not a viable long-term strategy, as sometimes a bit more effort is needed to develop a good solution

this issue is partially related to https://github.com/specify/specify7/issues/1761 as query combo boxes are affected by the same issue (since they also use the Autocomplete component)

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-7-release-announcement/1979/1

**Pull request merged**
