### PR TITLE
Allow query line drop down to flow outside its container

### LINKED ISSUE #3941: Query field drop-down mapper is confined to scroll in the mapped fields height
**Describe the bug**
Using the drop-down field mapper to change an already-mapped field is now confined to scrolling in just the height of the line of the mapped field.

**Screenshots**

https://github.com/specify/specify7/assets/135047322/3cdfc78e-e5fe-4642-a31b-60f7d7b617c7

**Desktop:**
 - macOS, Chrome, v7.9-dev, `herb_rbge_7_14_23`

**Additional context**
Came from PR #3877

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3941

### CODE REVIEW

**Comment by CarolineDenis** [comment]
please test in various size of windows

**Comment by carlosmbe** [comment]
Looks promising. Going to request @bronwyncombs to take a look to as they opened the issue.
Also, is it a technical limitation that we can not change the mapping in Basic View?

**Review by maxxxxxdlp — COMMENTED** [review]
looks good, but can you look back at the commit/pull request that introduced that `overflow-auto` to see why it was added? it might have been there for good reason

i.e it might have been there for narrow screens

**Comment by melton-jason** [comment]
> Blank space between mapper and results is fixed!
> 
> Part of the problem: Firefox allows the window to get smaller than our longer field names (i.e. Collecting Event Attachments, Reference Work Attachments) which causes the staggered button appearance. I'm not sure how we would want work around that.
> 
>  Screen.Recording.2023-08-15.at.9.51.50.AM.mov


More specifically, it was added to address the problem on https://github.com/specify/specify7/pull/3877#pullrequestreview-1578734136.

The cause of #3941 happens with `overflow-scroll` and `overflow-auto`. 
Maybe a more constrained overflow may work? 
Would `overflow-y-visible` work?

**Comment by CarolineDenis** [comment]
> looks good, but can you look back at the commit/pull request that introduced that `overflow-auto` to see why it was added? it might have been there for good reason
> 
> i.e it might have been there for narrow screens

Yes I added it in the past but couldn't reproduce  a case when it was needed. Hence the ask to test in various screen sizes. (Added at first for the shift of the lines in small narrow screen)

**Comment by CarolineDenis** [comment]
> > Blank space between mapper and results is fixed!
> > Part of the problem: Firefox allows the window to get smaller than our longer field names (i.e. Collecting Event Attachments, Reference Work Attachments) which causes the staggered button appearance. I'm not sure how we would want work around that.
> > Screen.Recording.2023-08-15.at.9.51.50.AM.mov
> 
> More specifically, it was added to address the problem on [#3877 (review)](https://github.com/specify/specify7/pull/3877#pullrequestreview-1578734136).
> 
> The cause of #3941 happens with `overflow-scroll` and `overflow-auto`. Maybe a more constrained overflow may work?
> 
> Would `overflow-y-visible` work?
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y It should allow the drop down to display outside of the container

Overflow-y-visible allows the drop down to display outside the container but brings back the shift of the line: 
Screenshot 2023-08-25 at 7 03 54 AM

**Comment by CarolineDenis** [comment]
with overflow-auto: 
- no shifting of the lines in narrow screen 
- drop down inside the div instead of outside 
without overflow-auto: 
- shifting of the lines in narrow screen 
- drop down outside the div like expected 

Not ideal but why not add overflow-auto only for small screens? 
That would result in: 
sm: no shifting - dropdown inside 
md and >: no shifting - dropdown outside 

@grantfitzsimmons @melton-jason

**Review by grantfitzsimmons — APPROVED** [review]

**Review by bronwyncombs — APPROVED** [review]
drop down scroll only on very small screens is working. tested firefox, chrome, safari

https://github.com/specify/specify7/assets/135047322/59643d9b-a422-412b-a2b7-1b70e4f44a02

**Review by melton-jason — APPROVED** [review]
I am not the biggest fan of this solution. 
Although I can not come up with a better solution without some better knowledge of css. 

This will probably have to do for now

**Comment by maxxxxxdlp** [comment]
related issue that can resolve this bug once and for all - https://github.com/specify/specify7/issues/2602
while also reducing how much code we have to maintain

**Pull request merged**
