### PR TITLE
Fix race condition with pick list fetching

### LINKED ISSUE #2144: Race condition when fetching pick list items
Happens in the CSIRO database. Probably can happen in other places too.

To fix:
if pick list is already being fetched, return the same promise, rather than start fetching again.

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #2144

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp How can I test this?

**Comment by maxxxxxdlp** [comment]
I was able to replicate the bug locally and check that the fix fixes the bug

The only thing remaining to test:
Can you please check that places in sp7 that use pick lists still work? (the change affected pick list fetching)

**Comment by grantfitzsimmons** [comment]
image

I'm not running out of resources like before, but the query results are not showing. 

https://anfc-issue-2144.test.specifysystems.org/specify/query/76/

username: `pae008`

Should I request changes or is this another bug?

**Comment by maxxxxxdlp** [comment]
the bug should be reproducible on `production`, but not reproducible on `issue-2144`.

which branch is your screenshot from?

**Comment by grantfitzsimmons** [comment]
> the bug should be reproducible on `production`, but not reproducible on `issue-2144`.
> 
> which branch is your screenshot from?

`issue-2144`

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
Try the query

**Comment by maxxxxxdlp** [comment]
Sorry, I misread your message. Yes, this is a bug

**Comment by maxxxxxdlp** [comment]
After investigation, turned out that the database had a circular dependency. Fixing that fixed the issue.

See #2160 for more details.

**Review by grantfitzsimmons — APPROVED** [review]
image

**Pull request merged**
