### PR TITLE
Add live validation to XML and JSON app resources

### LINKED ISSUE #499: Validate XML resources when uploading.

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #499

### CODE REVIEW

**Review by grantfitzsimmons — DISMISSED** [review]
image

**The live validation is really helpful and works with the several XML resources I've imported.** There is a piece of text that claims to provide a rendering of the page up to the first error but no such rendering exists. This should be corrected to prevent issues with users.

**Comment by maxxxxxdlp** [comment]
Fixed

**Review by grantfitzsimmons — APPROVED** [review]

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Is this feature still available?

**Comment by maxxxxxdlp** [comment]
I have just cherry-picked this onto a11y

**Pull request closed without merging**
