### PR TITLE
Don't enforce strict mode for regex

### LINKED ISSUE #3028: `SyntaxError` regarding regular expression catalog number
```
SyntaxError: invalid identity escape in regular expression

Me@https://mcnb22123-edge.test.specifysystems.org/static/js/main.321a0fa8e9d1c6ede8e6.bundle.js:2:492489
B@https://mcnb22123-edge.test.specifysystems.org/static/js/main.321a0fa8e9d1c6ede8e6.bundle.js:2:508822
N@https://mcnb22123-edge.test.specifysystems.org/static/js/main.321a0fa8e9d1c6ede8e6.bundle.js:2:509307
m@https://mcnb22123-edge.test.specifysystems.org/static/js/main.321a0fa8e9d1c6ede8e6.bundle.js:2:429987
T@https://mcnb22123-edge.test.specifysystems.org/static/js/main.321a0fa8e9d1c6ede8e6.bundle.js:2:509136
Suspense
```

You cannot even create a new Collection Object:

image

https://mcnb22123-edge.test.specifysystems.org/specify/view/collectionobject/new/

image

The field does not even display.

`spadmin`

---

The catalog number field uses a regular expression:
`MZB (\d{2}|\d{4})\-\d{4}(-[A-Z])?`

This pattern matches a string that starts with "MZB ", followed by either two or four digits, then a hyphen, then four digits, and optionally a hyphen followed by a single uppercase letter.

This pattern would match strings such as "MZB 12-3456", "MZB 1234-5678", and "MZB 12-3456-A".

---

I can recreate this error consistently when I navigate to https://mcnb22123-edge.test.specifysystems.org/specify/query/26/

[Specify 7 Crash Report - 2023-02-21T15 27 28.055Z.txt](https://github.com/specify/specify7/files/10794951/Specify.7.Crash.Report.-.2023-02-21T15.27.28.055Z.txt)

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
If regex is coming from the user

Fixes #3028

### CODE REVIEW

**Review by grantfitzsimmons — APPROVED** [review]
Works great for CSIC! I reverted the catalog number regex back to the original and was able to create objects, run queries, and do all of the standard operations.

**Review by melton-jason — APPROVED** [review]
This is the case in current production, but could we use the pattern over the regex expression in validation messages? 

`Value 'x' doesn't match formatter MZB (\d{2}|\d{4})\-\d{4}(-[A-Z])?`

pr_3042

Regardless, the intent of the error is still (somwhat) clear, and this is already in production, so I would not consider this as a blocker to the PR.

**Comment by maxxxxxdlp** [comment]
Showing regex to users is not very user friendly - but it's something both sp6 and sp7 are guilty of
Opened #3061 for it

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-release-announcement/1079/1

**Pull request merged**
