### PR TITLE
Use a backend solution for synonym concat

### LINKED ISSUE #5067: Tree uses so much memory it crashes
**Describe the bug**
Every time you open the Vascular Plants tree in the `hujinnhc` and navigate to 'Orchidaceae' and expand it, the browser runs out of memory.

There are 386,143 nodes in this taxon tree.

**To Reproduce**

1. Log into a test panel copy of `hujinnhc` as `spadmin` and select `Vascular` as the collection
2. Go to `/specify/tree/taxon/?conformation=~~4~3643485~3643486~3655819~3693849~3704974~3732987--------` in the tree (or 'Orchidaceae') and expand species children
3. Wait and see crash

**Expected behavior**
It should not crash.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/4bef9cda-82d4-4b94-a3d5-5b1e83f54d37

**Crash Report**
[Specify 7 System Information - 2024-07-03T17_11_21.670Z.txt](https://github.com/user-attachments/files/16088443/Specify.7.System.Information.-.2024-07-03T17_11_21.670Z.txt)

macOS, Arc, `v7.9.6`

image
image

Chrome, Windows, `v7.9.6`

>Meanwhile, a new and possibly related bug has appeared in the taxon tree. In some genera (I suspect those with more species) when you try to unfold the species list the system thinks for a while (showing a clock icon on the node) and then crashes:
>
> This happens in more than one machine to different users. It's much more problematic the the geography issue because it hangs the whole site and severely affects the workflow.

**Reported By**
Eyal Ben-Hur at The Hebrew University of Jerusalem

### PR DESCRIPTION
**Pull request by realVinayak**
Fixes #5067 

Moves the logic for concatenating syn's full names on the backend rather than the frontend. 

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions

**Synonyms**
Same for https://github.com/specify/specify7/pull/4704.
go to any tree
hover over a node that has synonyms

**Tree stats**
Same as in https://github.com/specify/specify7/pull/3613#issuecomment-1792814457
1. go to any tree node
2. tree stats should appear faster than they do in producton

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
@realVinayak Testing instructions?

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

**Synonyms**
Same for https://github.com/specify/specify7/pull/4704.
go to any tree
hover over a node that has synonyms

**Tree stats**
Same as in https://github.com/specify/specify7/pull/3613#issuecomment-1792814457
1. go to any tree node
2. tree stats should appear faster than they do in producton

Trees seem to be running faster than production and large ones no larger crash however synonyms are not shown when hovering

**Comment by realVinayak** [comment]
^could you add a video / link?

**Comment by emenslin** [comment]
@realVinayak 

https://github.com/user-attachments/assets/403e20f0-132b-4b5a-8230-f206f65b21d1

https://hujinnhc20240701-issue-5067.test.specifysystems.org/specify/tree/taxon/?conformation=%7E%7E4%7E3643485%7E3643486%7E3742412%7E3794807%7E3800718%7E3801087%7E3801147%7E5776383---%7E3803021%7E3803042-%7E5776384---------

**Comment by CarolineDenis** [comment]
works for me :+1:

**Comment by realVinayak** [comment]
me too....
image

**Review by CarolineDenis — APPROVED** [review]

**Comment by lexiclevenger** [comment]
### Testing instructions

**Synonyms**
Same for https://github.com/specify/specify7/pull/4704.
go to any tree
hover over a node that has synonyms

**Tree stats**
Same as in https://github.com/specify/specify7/pull/3613#issuecomment-1792814457
1. go to any tree node
2. tree stats should appear faster than they do in producton
---
Looks good! 👍

**Review by lexiclevenger — APPROVED** [review]

**Review by emenslin — APPROVED** [review]
Synonym display when hovering had inconsistent behavior before so it was not caused by this pr

**Comment by realVinayak** [comment]
Need another dev to look over and that should be it @specify/dev-testing

**Comment by grantfitzsimmons** [comment]
Closing this in favor of #5115

**Pull request closed without merging**
