### PR TITLE
Recalculate WB search function when utils changes

### LINKED ISSUE #4931: Search functionality not working in WorkBench
**Describe the bug**
The Search functionality for cells in the WorkBench is not properly finding cells

**To Reproduce**

1. Go to any WorkBench Dataset 
2. Search for a value in any cell
3. See that the cell is never matched and no search results are returned

**Expected behavior**
The search functionality in `production` should match that of `v7.9.4`

`v7.9.4`: 

https://github.com/specify/specify7/assets/64045831/aa7cb6f4-ffe6-421d-8da2-1803d7dbbced

`production`: 

https://github.com/specify/specify7/assets/64045831/eb3c46da-0b7d-4b22-a018-65b263323045

- OS: macOS Sonoma 14.3
- Browser: Chrome
- Specify 7 Version: `production`
- Database Name: KUFish_5_16_23
- Collection name: KU Fish Voucher
- User Name: spfishadmin

Tested on [KUFish_5_16_23](https://kufish51623-edge-2.test.specifysystems.org/specify/workbench/15/) (`spfishadmin`, KU Fish Voucher) and [KUBirds_8_25_23](https://kubirds82523-edge.test.specifysystems.org/specify/workbench/15/) (`spbirdadmin`)

Additional Context: 

Here is the Search Configuration options for `KUFish`: 

Screenshot 2024-05-20 at 9 49 25 AM

### PR DESCRIPTION
**Pull request by melton-jason**
Fixes #4931

Related to #4637 

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions
For a large dataset (such as [FishTissueData](https://kufish51623-edge-2.test.specifysystems.org/specify/workbench/29/) (user `spadmin`, collection `KUFishVoucher`), and a small dataset (such as those listed in https://github.com/specify/specify7/issues/4931#issue-2306126437): 
- [ ] Ensure the search functionality is consistent with ` v7.9.4` with multiple search configurations

### CODE REVIEW

**Review by emenslin — APPROVED** [review]
### Testing instructions
For a large dataset (such as [FishTissueData](https://kufish51623-edge-2.test.specifysystems.org/specify/workbench/29/) (user `spadmin`, collection `KUFishVoucher`), and a small dataset (such as those listed in https://github.com/specify/specify7/issues/4931#issue-2306126437): 
- [x] Ensure the search functionality is consistent with ` v7.9.4` with multiple search configurations

Looks great, search function is working! 
Screenshot 2024-05-20 122654

**Review by sharadsw — APPROVED** [review]

**Review by Areyes42 — APPROVED** [review]
### Testing instructions

For a large dataset (such as [FishTissueData](https://kufish51623-edge-2.test.specifysystems.org/specify/workbench/29/) (user `spadmin`, collection `KUFishVoucher`), and a small dataset (such as those listed in [#4931 (comment)](https://github.com/specify/specify7/issues/4931#issue-2306126437)):

-  [x]  Ensure the search functionality is consistent with `v7.9.4` with multiple search configurations
***
Great job, search functionality works as intended!
Screenshot 2024-05-20 at 12 57 53 PM

**Review by alesan99 — APPROVED** [review]
### Testing instructions
For a large dataset (such as [FishTissueData](https://kufish51623-edge-2.test.specifysystems.org/specify/workbench/29/) (user `spadmin`, collection `KUFishVoucher`), and a small dataset (such as those listed in https://github.com/specify/specify7/issues/4931#issue-2306126437): 
- [X] Ensure the search functionality is consistent with ` v7.9.4` with multiple search configurations

Searching works automatically, and the search configurations are respected like they are in v7.9.4 👍

As a note, there has been a change in behavior (An improvement imo)

Previously, pressing enter after typing something into the search bar would bring you directly to edit mode on the first found cell. Pressing the arrows on the hightlight buttons would then simply select the next cells (not edit)
Now, pressing enter simply selects the first found cell.
If you can get the search function to work in the original React Workbench PR, this is also the case there, so its not entirely related to this PR's changes.

Left: `v7.9.4` Right: This PR 

https://github.com/specify/specify7/assets/8108710/e139173e-ee20-42f4-8e1e-45578111842b

**Comment by melton-jason** [comment]
Sorry about this, but could this be briefly tested again? 

Did a slight optimization change which _shouldn't_ have changed any functionality, but worth going over once again to make sure!

**Review by Areyes42 — APPROVED** [review]
### Testing instructions

For a large dataset (such as [FishTissueData](https://kufish51623-edge-2.test.specifysystems.org/specify/workbench/29/) (user `spadmin`, collection `KUFishVoucher`), and a small dataset (such as those listed in [#4931 (comment)](https://github.com/specify/specify7/issues/4931#issue-2306126437)):

-  [x]  Ensure the search functionality is consistent with `v7.9.4` with multiple search configurations

* * *

Everything still looks good! I tested different search configurations, and they functioned as expected. Additionally, I was able to replicate the enter selection behavior change that @alesan99 noticed. I also agree that it's an improvement compared to the behavior in `v7.9.4`.
Screenshot 2024-05-20 at 2 02 50 PM

**Comment by sharadsw** [comment]
Another improvement here: Live search works as expected now. In `7.9.4` it behaves inconsistently unless 'Find entire cells only' is disabled.

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-5-release-announcement/1751/1

**Pull request merged**
