### PR TITLE
Fix isPrimary for Consolidated COGs

### LINKED ISSUE #5458: Can save a COG when no CO child is marked as 'isPrimary'
**Describe the bug**
If you make a consolidated COG, add a child, save, delete the child, then add one back you can save without any child being marked as 'isPrimary'. Related to #5449, I could not recreate any of the issues reported in that PR, however, I know Alejandro reported being able to save a consolidated COG without a childCO marked as 'isPrimary' in the checklist so there are potentially other ways this can happen.

**To Reproduce**

1. Create a COG with a consolidated type
2. Add childCO 
3. Mark as 'isPrimary'
4. Save 
5. Delete childCO 
6. Save
7. Add childCO 
8. See you can save without setting childCO as primary

**Expected behavior**
Save should be blocked. 

**Screenshots**

https://github.com/user-attachments/assets/c8f68c47-e753-4d26-a8bf-e19b725da134

Please fill out the following information manually:
- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: Production 
- Database Name: ojsmnh
- Collection name: Fossil Invertebrates
- User Name: spadmin
- URL: https://ojsmnh20241003wb-production.test.specifysystems.org/specify/

### PR DESCRIPTION
**Pull request by sharadsw**
Fixes #5458

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions

- Create a COG with a consolidated type
-Add childCO
- Mark as 'isPrimary'
- Save
- Delete childCO
- Save
- Add childCO
- [ ] Verify save is blocked as no primary CO exists

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Review by emenslin — COMMENTED** [review]
- [x] Verify save is blocked as no primary CO exists

This is not necessarily a problem but I want to make sure this is the intended behavior before approving. If you add a consolidated parentCOG to a CO (through the CO form) save is now blocked on the CO form when you open the COG. This behavior is different from production so I just want to make sure this is the new intended behavior 

This branch: 

https://github.com/user-attachments/assets/c2d399d7-ffc6-40ca-9b89-ef85cd5c7bec



Production:

https://github.com/user-attachments/assets/dfdbf557-2248-45d8-9c95-97c31f31e82d

**Comment by sharadsw** [comment]
@emenslin @grantfitzsimmons Changed the behavior now so that any saved Consolidated COG without a primary CO child, will have its first CO child marked as primary. 

Opening the parent COG dialog in the above case now will not block save automatically and the co child will already be marked as primary. However, if the child is then unmarked as primary you'll still see the blocker and it would still get carried over to the CO form if the user chooses to do nothing about it

**Comment by sharadsw** [comment]
@grantfitzsimmons I couldn't test it as COGs don't seem to be working well on the WB. We should add this to #5418 

However, going solely by the current code, the behavior for those cases should be:
- User creates a new consolidated COG with 3 children, but no child has isPrimary set to true
  - The first child should get set as primary
- User creates a new consolidated COG with 3 children, but 2 children have isPrimary set to true
  - The second child that was marked as primary should stay primary and other children would be unset

**Review by emenslin — APPROVED** [review]
- [x] Verify save is blocked as no primary CO exists

Looks good, 'isPrimary' gets automatically checked on consolidated COGs through the CO form.

**Review by Areyes42 — APPROVED** [review]
- [x] Verify save is blocked as no primary CO exists

Fixes look good!

**Review by alesan99 — COMMENTED** [review]
(whoops wrong pr disregard)

**Pull request merged**
