### PR TITLE
ES Modules

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Update to babel 7 and core-js 3
Update other development dependencies
Improve webpack config
Improve source maps
Use ES Modules instead of common js
Use import() instead of deprecated require.ensure()

### CODE REVIEW

**Comment by maxxxxxdlp** [comment]
@benanhalt Development dependencies have been updated
Production dependencies remain unchanged, so this PR should be more or less stable

**Comment by benanhalt** [comment]
What prompted you to make these changes?

**Comment by maxxxxxdlp** [comment]
> What prompted you to make these changes?

This PR fixes a few dependabot alerts, speeds up webpack, updates to the newest import syntax, makes codebase more consistent and makes it easier for my IDE to infer types of imported modules

Though, it looks like back-end localization is not yet merged into production. Would need to do that first

**Comment by benanhalt** [comment]
Do these changes depend on the backend localization?

**Comment by maxxxxxdlp** [comment]
It didn't initially, but I rebased it of `next-release`, which has backend-localization merged into it

**Comment by benanhalt** [comment]
I can separate the commits from the next-release branch unless it actually depends on them. If they are independent changes I would prefer to do that.

**Comment by maxxxxxdlp** [comment]
Sure, go ahead. They are indepentent.

These are the commits you need to keep:
Screen Shot 2021-11-19 at 4 14 05 PM

Everything before this one can be dropped:
```
2481ea20 Max Patiiuk 4 months ago Replace deprecated code splitting method
```

**Comment by benanhalt** [comment]
It seems like webpack is not generating the `manifest.py` file on this branch.

**Comment by maxxxxxdlp** [comment]
I see the issue
I told webpack to clean previous build artifacts (to prevent disk space leaks). Apparently, it was also deleting manifest.py in the process
Should be fixed now

**Comment by maxxxxxdlp** [comment]
Merged into a11y

**Pull request closed without merging**
