### PR TITLE
Schema editor

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Schema editor is available in the User Tools menu

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
schema_6
schema_7
There are some big schema configurator inconsistences between 6 and 7. I highlighted tables that appear in each version but not in the other. Is this intentional behavior?
_freshfish database_

**Review by grantfitzsimmons — COMMENTED** [review]
Adding a language to a database, making changes, and saving has no effect. Navigating to Schema Config does not show the added language.

**Comment by grantfitzsimmons** [comment]
The Schema Configurator is missing the ability to create a new table format or table aggregation. These functions are present in Specify 6.

**Comment by grantfitzsimmons** [comment]
No Seperation between user and system picklists
When selecting a Pick List, there is no separation between system and user-defined ones. There is no easy way to create a new Pick List without needing to navigate back through the Schema Configuration tool after saving, nor the ability to import or export one.
picklist6

**Comment by grantfitzsimmons** [comment]
prepType_7
prepType_6

The Pick List editor shows pick lists that are inaccessible in 6 and non-functional in 7. The size limit being -1 is invalid when trying to save and continue configuration, and if you try to add pick list items, this error occurs:

picklistlimit
_Screenshot from a different picklist_

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons 
1. > There are some big schema configurator inconsistences between 6 and 7

   Removed some system tables (treedef, treedefitem)
   Some of the remaining tables should be hidden in Sp6

2. > Adding a language to a database, making changes, and saving has no effect. Navigating to Schema Config does not show the added language. 

    Fixed Schema Config not fetching all languages properly

3. > The Schema Configurator is missing the ability to create a new table format or table aggregation

   > nor the ability to import or export one.

    Maybe for next release

4. > In 6, the Table Format defaults to the correct format.
  The Field Format pick list is restricted to None.

    Click on that pick list and there would be an option to change it's value to something other than none

5. > The Field Format options allow for the isLoanable field to be used as a web link, pick list, or in another format

    Also, from Andy:

    > I did notice that you can set formatted, weblink or pick list fields for non-text fields like integer fields.

    Fixed. Only text fields can be weblinks. Though, it's debatable whether numeric fields or yes/no files are to be allowed to be set as picklists

6. > When selecting a Pick List, there is no separation between system and user-defined ones
   
    Fixed

7. > There is no easy way to create a new Pick List without needing to navigate back through the Schema Configuration tool after saving

   You can open the link in the new tab. Keep in mind though, that newly added picklists won't appear in the list until the page is refreshed.

8.  > The size limit being -1 is invalid when trying to save and continue configuration,

    That's an issue with form definition. See https://github.com/specify/specify7/issues/1025

9. > ... and if you try to add pick list items, this error occurs:
 
    Known Issue. See https://github.com/specify/specify7/issues/108

**Comment by maxxxxxdlp** [comment]
Merged into a11y

**Pull request merged**
