### PR TITLE
Restore bad tree structure saveBlocker

### LINKED ISSUE #4717: 'Bad Tree Structure' warning no longer prevents saving when it should
**Describe the bug**
The 'bad tree structure' warning no longer appears when selecting an invalid parent (i.e. a parent that's the lowest rank in the taxon tree, such as subspecies), and allows for the user to save, leading to a crash.

**To Reproduce**
1. Go to Create Entry -> New Taxon.
2. Fill name, add a parent that _is not_ the lowest taxon rank to fill the taxonomic rank field (i.e. Animalia).
3. Change parent to lowest taxon rank (i.e. Darlingtonia haetiana haetiana).
4. The parent form will show as valid and you can save, leading to an error.

**Expected behavior**
A warning should flag the parent and prevent the user from saving.

**Screenshots**
First is the edge server, after error message is v7.

https://github.com/specify/specify7/assets/71564869/222610c5-3555-426c-a9e6-f4e39c04e928

**Crash Report**

[Specify 7 Crash Report - 2024-04-01T20 40 51.788Z.txt](https://github.com/specify/specify7/files/14828365/Specify.7.Crash.Report.-.2024-04-01T20.40.51.788Z.txt)

- OS: Windows 10
- Browser: Firefox & Chrome
- Specify 7 Version: edge
- Database Name: KU_Herps_8_17_23
- Collection name: Herpetology
- User Name: spherpsadmin

**Additional context**
May be related to issues #4455 and PR #4462. Crash is likely from issue #2637, but could also be something with adding a child to the smallest rank.

### PR DESCRIPTION
**Pull request by melton-jason**
Fixes #4717

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions
- [ ] On a new Taxon record, set the Parent to be a rank which is not the lowest in the tree
- [ ] Clear the Parent QueryComboBox (the tree rank should clear as well) 
- [ ] Set the Parent of the Taxon to be a node which is the lowest rank in the tree
- [ ] A saveBlocker should be set on the Parent field which reports `Bad Tree Structure` and the Tree Rank picklist should become disabled
- [ ] Change the parent to a Taxon in which the possible ranks do not include the current rank (definitionItem) of the new Taxon record. (See  https://github.com/specify/specify7/pull/4726#pullrequestreview-1974967848)
- [ ] The tree rank should be set accordingly to the lowest enforceable rank 

- [ ] On an existing tree record, ensure the form opens without unload protect being triggered (as in #3259)
- [ ] The tree rank should not be overwritten with a new value, and should use the existing rank of the record as shown in the Tree Viewer (especially when there are multiple possible ranks the node could take, see https://github.com/specify/specify7/pull/4659#issue-2187680064)

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions
- [x] On a new Taxon record, set the Parent to be a rank which is not the lowest in the tree
- [x] Clear the Parent QueryComboBox (the api url of the previous TreeRank should remain) 
- [x] Set the Parent of the Taxon to be a node which is the lowest rank in the tree
- [ ] A saveBlocker should be set on the Parent field which reports `Bad Tree Structure`

After switching to the lowest node in the tree if you try to change it to a valid tree structure there is still a save blocker and even if you try to select a rank from the picklist the save is still blocked and it says bad tree structure.
Also if you go back to the original parent you set it does let you save even with the api link.

https://github.com/specify/specify7/assets/150940840/7eea4353-b922-4355-b9ab-1bc9d981a52b

**Comment by melton-jason** [comment]
> * [ ]  A saveBlocker should be set on the Parent field which reports `Bad Tree Structure`
> 
> After switching to the lowest node in the tree if you try to change it to a valid tree structure there is still a save blocker and even if you try to select a rank from the picklist the save is still blocked and it says bad tree structure. Also if you go back to the original parent you set it does let you save even with the api link.
> 
>  lgtcgFGURE.mp4

This issue should be fixed. 
Can this PR be tested again?

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions
- [x] On a new Taxon record, set the Parent to be a rank which is not the lowest in the tree
- [x] Clear the Parent QueryComboBox (the api url of the previous TreeRank should remain) 
- [x] Set the Parent of the Taxon to be a node which is the lowest rank in the tree
- [ ] A saveBlocker should be set on the Parent field which reports `Bad Tree Structure`

Although now you can save once changing it back from the lowest tree rank the error shows up saying 'bad tree structure' under the parent, but the issue is that you have to change the picklist from api link to the actual rank. I think it would make more sense if the error message was under the picklist in this case. 

https://github.com/specify/specify7/assets/150940840/142199a2-122c-4520-b833-4dc102f30a5f

@specify/ux-testing thoughts? I feel like moving the error message would make it more clear to users what's happening

**Review by maxpatiiuk — APPROVED** [review]

**Comment by melton-jason** [comment]
> ### Testing instructions
> * [x]  On a new Taxon record, set the Parent to be a rank which is not the lowest in the tree
> * [x]  Clear the Parent QueryComboBox (the api url of the previous TreeRank should remain)
> * [x]  Set the Parent of the Taxon to be a node which is the lowest rank in the tree
> * [ ]  A saveBlocker should be set on the Parent field which reports `Bad Tree Structure`
> 
> Although now you can save once changing it back from the lowest tree rank the error shows up saying 'bad tree structure' under the parent, but the issue is that you have to change the picklist from api link to the actual rank. I think it would make more sense if the error message was under the picklist in this case.
> 
>  kUpIxmqBlP.mp4 
> @specify/ux-testing thoughts? I feel like moving the error message would make it more clear to users what's happening

@specify/ux-testing this issue should now be fixed. 
Please ensure that for all cases, the field for which the saveBlocker is set is intuitive for what the underlying issue is.

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions
- [x] On a new Taxon record, set the Parent to be a rank which is not the lowest in the tree
- [x] Clear the Parent QueryComboBox (the api url of the previous TreeRank should remain) 
- [x] Set the Parent of the Taxon to be a node which is the lowest rank in the tree
- [x] A saveBlocker should be set on the Parent field which reports `Bad Tree Structure`
- [x] Change the parent to a Taxon in which the possible ranks do not include the current rank (definitionItem) of the new Taxon record. (See  https://github.com/specify/specify7/pull/4726#pullrequestreview-1974967848)
- [ ] A saveBlocker should be set on the Rank field which reports `Bad Tree Structure`

Inconsistent save blockers and can save with the api link as the rank instead of the title. Not sure exactly why sometimes there is the save blocker dialog and why sometimes it just shows up as 'bad tree structure' but I have been able to recreate both scenarios. And it seems the saving the api link might be when you select a higher rank in the tree than what you originally started with. 

https://github.com/specify/specify7/assets/150940840/b605a249-93ca-4012-8b9a-b0ff20a8413f

**Comment by melton-jason** [comment]
Can this be tested again? I have made some changes and updated the testing instructions. 
Now, the user should never see an API uri in the tree rank picklist, as the rank should be recalculated whenever the parent changes, taking into account if the form is loading and whether or not the resource is new or not.  
(https://github.com/specify/specify7/pull/4743#pullrequestreview-1984393425)

The `Bad Tree Structure` error should now only be visible on the `parent` field when the parent is set to a node which has the lowest rank in the tree .

**Review by pashiav — DISMISSED** [review]
### Testing instructions
- [X] On a new Taxon record, set the Parent to be a rank which is not the lowest in the tree
- [X] Clear the Parent QueryComboBox (the tree rank should clear as well) 
- [X] Set the Parent of the Taxon to be a node which is the lowest rank in the tree
- [ ] A saveBlocker should be set on the Parent field which reports `Bad Tree Structure`
- [ ] Change the parent to a Taxon in which the possible ranks do not include the current rank (definitionItem) of the new Taxon record. (See  https://github.com/specify/specify7/pull/4726#pullrequestreview-1974967848)
- [ ] The tree rank should be set accordingly to the lowest enforceable rank 

- [ ] On an existing tree record, ensure the form opens without unload protect being triggered (as in #3259)
- [ ] The tree rank should not be overwritten with a new value, and should use the existing rank of the record as shown in the Tree Viewer (especially when there are multiple possible ranks the node could take, see https://github.com/specify/specify7/pull/4659#issue-2187680064)
---
Following the instructions, the save blocker is not for "**Bad tree structure.**" but for the blank Rank field and says "**Please fill out this field.**"

The Rank field is no longer a QueryComboBox and is shown to be a text field. After some input in the field, it changes back to a QueryComboBox that cannot accept any input. **Add** selection also doesn't work. 

Shows save blocker's expected behavior in `v7.9`, then in `issue-4714`
LHS `v7.9` | RHS: `issue-4717`

https://github.com/specify/specify7/assets/118556884/791db98b-b784-42df-98ac-c8d1fc4551b5

**Review by lexiclevenger — CHANGES_REQUESTED** [review]
- [x] On a new Taxon record, set the Parent to be a rank which is not the lowest in the tree
- [x]  Clear the Parent QueryComboBox (the tree rank should clear as well)
- [x]  Set the Parent of the Taxon to be a node which is the lowest rank in the tree
- [x]  A saveBlocker should be set on the Parent field which reports Bad Tree Structure
- [ ]  Change the parent to a Taxon in which the possible ranks do not include the current rank (definitionItem) of the new Taxon record. (See https://github.com/specify/specify7/pull/4726#pullrequestreview-1974967848)
- [ ]  The tree rank should be set accordingly to the lowest enforceable rank
- [ ]  On an existing tree record, ensure the form opens without unload protect being triggered (as in https://github.com/specify/specify7/issues/3259)
- [ ]  The tree rank should not be overwritten with a new value, and should use the existing rank of the record as shown in the Tree Viewer (especially when there are multiple possible ranks the node could take, see https://github.com/specify/specify7/pull/4659#issue-2187680064)

I was able to get to the save blocker as expected by following steps 1-3. However, there is still an issue when trying to create a taxon with a valid tree structure. If you put in a rank that is not the lowest, clear it, and put in a parent that is not lowest but is below the original rank, it gives you a 'bad tree structure' error and save blocker. This can be overridden by clicking away from the parent field and putting in a name. If you save after this, an infinite loading screen appears.

In this video, I use a class and then a species.

https://github.com/specify/specify7/assets/164079735/398c269b-f00f-4aec-920f-6bd35efcfd31

If you enter a name before changing the parent, the parent field flashes red and you are still given an infinite loading screen after saving.

In this video, I use a class and then a genus.


https://github.com/specify/specify7/assets/164079735/901abe7c-0aaf-4db6-8bf7-3a84384dc5b3

**Comment by melton-jason** [comment]
https://github.com/specify/specify7/pull/4726#pullrequestreview-1986873244 and https://github.com/specify/specify7/pull/4726#pullrequestreview-1987442239 should be fixed! 

The Tree Rank picklist should now also become disabled when the parent of the tree record is set to the lowest level (testing instructions have been updated)

**Review by emenslin — APPROVED** [review]
### Testing instructions
- [x] On a new Taxon record, set the Parent to be a rank which is not the lowest in the tree
- [x] Clear the Parent QueryComboBox (the tree rank should clear as well) 
- [x] Set the Parent of the Taxon to be a node which is the lowest rank in the tree
- [x] A saveBlocker should be set on the Parent field which reports `Bad Tree Structure` and the Tree Rank picklist should become disabled
- [x] Change the parent to a Taxon in which the possible ranks do not include the current rank (definitionItem) of the new Taxon record. (See  https://github.com/specify/specify7/pull/4726#pullrequestreview-1974967848)
- [x] The tree rank should be set accordingly to the lowest enforceable rank 

- [x] On an existing tree record, ensure the form opens without unload protect being triggered (as in #3259)
- [x] The tree rank should not be overwritten with a new value, and should use the existing rank of the record as shown in the Tree Viewer (especially when there are multiple possible ranks the node could take, see https://github.com/specify/specify7/pull/4659#issue-2187680064)

Looks good! Hopefully we are nearing the end!

**Review by combs-a — APPROVED** [review]
### Testing instructions
- [X] On a new Taxon record, set the Parent to be a rank which is not the lowest in the tree
- [X] Clear the Parent QueryComboBox (the tree rank should clear as well) 
- [X] Set the Parent of the Taxon to be a node which is the lowest rank in the tree
- [X] A saveBlocker should be set on the Parent field which reports `Bad Tree Structure` and the Tree Rank picklist should become disabled
- [X] Change the parent to a Taxon in which the possible ranks do not include the current rank (definitionItem) of the new Taxon record. (See  https://github.com/specify/specify7/pull/4726#pullrequestreview-1974967848)
- [X] The tree rank should be set accordingly to the lowest enforceable rank 
- [X] On an existing tree record, ensure the form opens without unload protect being triggered (as in #3259)
- [X] The tree rank should not be overwritten with a new value, and should use the existing rank of the record as shown in the Tree Viewer (especially when there are multiple possible ranks the node could take, see https://github.com/specify/specify7/pull/4659#issue-2187680064)

Everything looks great, good work! 😄🥇

**Pull request merged**
