### PR TITLE
Fix picklist fetcher getting confusd by picklist with items

### LINKED ISSUE #1491: DNA Sequences pick list discrepancy
image

image

The pick list items are different between `edge` and `a11y`.

db: oldfish

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #1491

To test:
1. Pick list with type "entire table"
2. Pick list with pick list items, but with pick list type "Entire Table"
3. Pick lists with type "Fields from table"
4. Pick list with pick list items, but with pick list type "Fields from table"
5. Regular pick list from items
6. Pick lists with the same name in different collections

### CODE REVIEW

**Review by chanulee1 — CHANGES_REQUESTED** [review]
Creating picklist from entire table and adding custom pick list items shows only custom picklist items in the picklist.
db: `willemcatno`
col: `Tissue Collection`
user: `collection`

**Review by chanulee1 — CHANGES_REQUESTED** [review]
image

Now cannot change type of picklist ;(

**Comment by maxxxxxdlp** [comment]
Ah yes, the front-end-only picklists need to be updated a bit. Fixed

**Comment by chanulee1** [comment]
@maxxxxxdlp The expected behavior for a picklist from a table with custom items is to show both the items from the table and the custom items right?

**Comment by maxxxxxdlp** [comment]
No, only the items from the table

**Review by chanulee1 — APPROVED** [review]
Looks good.

**Pull request merged**
