### PR TITLE
Add length attribute to Calendar fields in datamodel

### LINKED ISSUE #5009: Max length for year is set to 0 in the query builder
**Describe the bug**
When querying on a date year field (e.g. Loan Date (Year)) if you change the operator and try to input a valid year it says the field value is too long.

**To Reproduce**

1. Go to queries 
2. Query on any table with a date field (e.g. loan) 
3. Select the date (year) field (e.g.  Loan Date (Year)) 

**Expected behavior**
A valid year should be accepted

**Screenshots**
Edge: 

https://github.com/specify/specify7/assets/150940840/dc2b0d79-04e1-4f6c-8822-40afd57dfb27

7.9.5: 

https://github.com/specify/specify7/assets/150940840/1a5a63a8-b91c-4c1b-b68b-dc8be7c3394f

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: spadmin

### PR DESCRIPTION
**Pull request by acwhite211**
Fixes #5009

Adding the a length attribute to Calendar fields in the data-model seemed to fix this issue.

In the specify_datamodel.xml file:
```xml
<field column="LoanDate" name="loanDate" type="java.util.Calendar" indexName="LoanDateIDX" updatable="true" required="false" unique="false" indexed="true" partialDate="false"/>
```

In datamodel.py file:
```python
Field(name='loanDate', column='LoanDate', indexed=True, unique=False, required=False, type='java.util.Calendar', length=50)
```

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

https://github.com/specify/specify7/issues/5009#issue-2357554983

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Review by sharadsw — APPROVED** [review]

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
The issue extends beyond simply adding a length attribute to calendar fields. Consider other fields where people want to search, but a length value is not available. Even `Latitude1` and `Longitude1` are examples of this, but that's just the tip of the iceberg.

image

**Comment by realVinayak** [comment]
Hehe, maybe we should auto-reject PRs that use the word "seem". 

From edge

```
{
    "name": "loanDate",
    "column": "LoanDate",
    "indexed": true,
    "unique": false,
    "required": false,
    "type": "java.util.Calendar"
},
```

From 7.9.5

```
{
  "name": "loanDate",
  "column": "LoanDate",
  "indexed": true,
  "unique": false,
  "required": false,
  "type": "java.util.Calendar",
  "length": 0
},
```

What you really need to do is compare the difference of `https://sp7demofish.specifycloud.org/context/datamodel.json` end-point vs what it is now. Maybe consider adding a unit test for it (but look at each manually) Ignore sp7 tables for now. Whatever you do, at the end either make datamodel.json exactly equal to what it was in 7.9.5 OR fix the bugs on the frontend. I think making it equal is the best bet (although, if we had more time, the frontend bugs should be fixed)

**Review by lexiclevenger — CHANGES_REQUESTED** [review]
### Testing instructions
https://github.com/specify/specify7/issues/5009#issue-2357554983

---

The issue is still occurring:

https://github.com/specify/specify7/assets/164079735/737183b7-4bc3-40ce-aad2-260919614165

**Comment by acwhite211** [comment]
I found it better to just fix the serialize_datamodel.py file.  Should be good to re-test now @specify/testing

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
image

🤨 

```
~/Gi/b/specify7 on issue-5009 = !2 ❯ git pull                                              at 01:48:51 PM
Already up to date.
```

running locally

**Comment by acwhite211** [comment]
@grantfitzsimmons hmm... it's working for me locally, odd.

**Comment by acwhite211** [comment]
image
image
image

Changing the field value in the QB worked, didn't get any message about the length.

**Review by grantfitzsimmons — APPROVED** [review]
I rebuilt the containers and I don't have the issue anymore. @specify/ux-testing, please pick some weird fields!

**Review by CarolineDenis — APPROVED** [review]

**Review by combs-a — APPROVED** [review]
### Testing instructions
- [X] Test various date fields for Day/Month/Year in queries.

image

image

image

Tried with a bunch of different date queries, looks like it's fixed! If I need to test some other fields let me know.

**Review by emenslin — APPROVED** [review]
I tried on several different fields and every one I checked seemed to be working properly

**Review by lexiclevenger — APPROVED** [review]
### Testing instructions
https://github.com/specify/specify7/issues/5009#issue-2357554983

---

Looks good! No issue with year-related fields and various other fields.

**Pull request merged**
