### PR TITLE
Add a dialog with the chrono chart image for geologic table

### LINKED ISSUE #3614: Visual stratigraphic age chooser
This would allow you to use the view of the stratigraphic tree in a dialog where you can choose the proper age/section. This is used in BioOffice and is a beloved feature in Geneva.

image

https://stratigraphy.org/chart#latest-version

image

For developers:
> Chronostratigraphy is the branch of stratigraphy that studies the ages of rock strata in relation to time. The ultimate aim of chronostratigraphy is to arrange the sequence of deposition and the time of deposition of all rocks within a geological region, and eventually, the entire geologic record of the Earth. [Wikipedia](https://en.wikipedia.org/wiki/Chronostratigraphy)

This is used in both paleontology and geology.

**Requested By:** Geneva

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3614

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- open the chrono data entry form 
- [ ] verify the icon for the chrono chart is present in the header 
- [ ] verify that you can open and close the dialog with the chart 
- [ ] verify it is not present for other tables 
- open the geologictimeperiod tree 
- [ ] verify there is the clock icon next to the search bar in the top bar 
- [ ] verify that you can open and close the dialog with the chart 
- [ ] verify it is not present for other trees
- [ ] verify you can zoom and dezoom on the image 
- [ ] verify you can move the image when zoomed

### CODE REVIEW

**Review by sharadsw — APPROVED** [review]

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

- open the chrono data entry form 
- [x] verify the icon for the chrono chart is present in the header 
- [x] verify that you can open and close the dialog with the chart 
- [x] verify it is not present for other tables 
- open the geologictimeperiod tree 
- [x] verify there is the clock icon next to the search bar in the top bar 
- [x] verify that you can open and close the dialog with the chart 
- [x] verify it is not present for other trees
- [x] verify you can zoom and dezoom on the image 
- [ ] verify you can move the image when zoomed 

The chrono chart should be limited to the width of the screen otherwise you can't move the image around much and the zoom in and out buttons move 


https://github.com/user-attachments/assets/7c968615-0a5f-4690-bdd2-8771a2c25b0e

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

- open the chrono data entry form 
- [x] verify the icon for the chrono chart is present in the header 
- [x] verify that you can open and close the dialog with the chart 
- [x] verify it is not present for other tables 
- open the geologictimeperiod tree 
- [x] verify there is the clock icon next to the search bar in the top bar 
- [x] verify that you can open and close the dialog with the chart 
- [x] verify it is not present for other trees
- [x] verify you can zoom and dezoom on the image 
- [x] verify you can move the image when zoomed 

There should be a min height for the viewer so it doesn't move the buttons, I also think theres probably a better way to handle this dialog with resizing in general because it looks a little weird when you try expanding it. Maybe a full screen button? But I'm also not sure if that would work/fix it 

https://github.com/user-attachments/assets/022e0acf-37ee-4329-b73b-5919561f423c

**Comment by CarolineDenis** [comment]
@emenslin 
This is the same behavior as for any attachment in sp

**Review by pashiav — APPROVED** [review]
### Testing instructions

- open the chrono data entry form 
- [X] verify the icon for the chrono chart is present in the header 
- [X] verify that you can open and close the dialog with the chart 
- [X] verify it is not present for other tables 
- open the geologictimeperiod tree 
- [X] verify there is the clock icon next to the search bar in the top bar 
- [X] verify that you can open and close the dialog with the chart 
- [X] verify it is not present for other trees
- [X] verify you can zoom and dezoom on the image 
- [X] verify you can move the image when zoomed 

---
Looks great! Working as expected.
Screen Shot 2024-11-04 at 9 08 26 AM

**Review by acwhite211 — APPROVED** [review]

**Review by alesan99 — APPROVED** [review]
- open the chrono data entry form 
- [x] verify the icon for the chrono chart is present in the header 
- [x] verify that you can open and close the dialog with the chart 
- [x] verify it is not present for other tables 
- open the geologictimeperiod tree 
- [x] verify there is the clock icon next to the search bar in the top bar 
- [x] verify that you can open and close the dialog with the chart 
- [x] verify it is not present for other trees
- [x] verify you can zoom and dezoom on the image 
- [x] verify you can move the image when zoomed

Looks good 👍👍👍
chrome_2CxkI5nOcM

**Pull request merged**
