### PR TITLE
upgrade requests to 2.32.2

### LINKED ISSUE #4771: Upgrade requests library to v2.31.0 or later
Upgrade the python library 'request' from version 2.28.1 to at least version 2.31.0 or later in order to fix the security vulnerability pointed out [here](https://github.com/specify/specify7-test-panel/security/dependabot/19)

### PR DESCRIPTION
**Pull request by acwhite211**
Fixes #4771

Upgrades the python library 'request' from version 2.28.1 to at least version 2.31.0 or later in order to fix the security vulnerability pointed out [here](https://github.com/specify/specify7-test-panel/security/dependabot/19)

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

There is not specific test to perform.  Testing for this PR will be covered in the general testing checklist.
For now, test:
- [x] Simple queries work in the QB
- [x] Opening forms work
- [x] Viewing trees work
- [x] Create a report
- [x] Create or Delete attachment

### CODE REVIEW

**Review by sharadsw — APPROVED** [review]

**Comment by acwhite211** [comment]
>Are there any issues with instead updating to 2.32.0?

Looks like version 2.32.0 or the requests module just got pushed two days ago.  I'll go ahead update it to 2.32.2

https://pypi.org/project/requests/#history

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

There is not specific test to perform.  Testing for this PR will be covered in the general testing checklist.
For now, test:
- [x] Simple queries work in the QB
- [ ] Opening forms work
- [x] Viewing trees work

Collectors and groups subforms are broken again 

https://github.com/specify/specify7/assets/150940840/e173e6a4-bf69-4533-b478-98aabc259b82


https://github.com/specify/specify7/assets/150940840/b981c254-2d4c-48c3-bcce-8a7211fc233c

**Comment by melton-jason** [comment]
@emenslin

Looks like this PR was based from an old commit (from April 10) and had not been merged with `production` since then. 
Now that this branch has been updated, can this be tested again?

**Review by emenslin — APPROVED** [review]
### Testing instructions

There is not specific test to perform.  Testing for this PR will be covered in the general testing checklist.
For now, test:
- [x] Simple queries work in the QB
- [x] Opening forms work
- [x] Viewing trees work

Looks good!

**Comment by realVinayak** [comment]
None of those tests requests explicitly AFAIK.
1. try making reports
2. try deleting attachments
3. try SSO login

**Pull request merged**
