### PR TITLE
Fix for "Users can only be added at manager level"

### PR DESCRIPTION
**Pull request by maxxxxxdlp**

### CODE REVIEW

**Review by grantfitzsimmons — DISMISSED** [review]
KQAUGII4DL

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
Their is no longer a button for the username or notifications elements on this branch.
Instead of appearing like this:
look1
They are appearing like this:
look2

_In the interest of being user friendly, maybe a password, agents, and collection permissions should be required upon each user creation._

The Specify name field is carried over when clicking **Save and Add Another**, but if you attempt to add a duplicate user with the same name, this wall of text appears:
errorwhenidenticalnameisadded
This field should be cleared when adding another user and/or potentially a friendly error should appear.

**Comment by maxxxxxdlp** [comment]
> Their is no longer a button for the username or notifications elements on this branch

Fixed. The issue occurred because this branch was out of date with production

> In the interest of being user friendly, maybe a password, agents, and collection permissions should be required upon each user creation.

That's a valid point and it has been brought up before. It is something we would consider when redesigning the user creation and permissions system

> The Specify name field is carried over when clicking Save and Add Another, but if you attempt to add a duplicate user with the same name, this wall of text appears:

That's a know issue too. There are two bugs open for that: https://github.com/specify/specify7/issues/1011 and https://github.com/specify/specify7/issues/124

**Comment by maxxxxxdlp** [comment]
This is redundant now because the user type plugin has been rewritten

**Pull request closed without merging**
