### PR TITLE
Fix "bycatalog" URL not switching collection

### LINKED ISSUE #3451: "bycatalog" URL does not work when signed in to a different collection
Example: https://sp7demofish.specifycloud.org/specify/bycatalog/KUIT/5085/

It is supposed to switch collection automatically, but that does not happen due to react-router bug

image

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #3451

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Comment by melton-jason** [comment]
Here is some further information for @specify/ux-testing to test this further:
The "bycatalog" url is used to share Collection Object records. 

The url is defined as `/specify/bycatalog/<COLLECTION_CODE>/<CATALOG_NUMBER>`

You can optionally supply the id of a record set the Collection Object is in by supplying a `recordsetid` parameter to the url. 
For example, the assuming the Collection Code, CatalogNumber, and RecordsetId is correct, the following are valid bycatalog urls:
`http://localhost/specify/bycatalog/M/000000024`
`http://localhost/specify/bycatalog/M/000000024?recordsetid=5`

The bycatalog url functions nearly identically to the main view url. I'm pretty sure the reason it exists is that 
`specify/bycatalog/KUI/000000005` is _much_ easier to reason about and _know_ which record the url points to than `specify/view/collectionobject/6850/`. 

Essentially, it is a url designed for Collection Objects. 

In the application, this url can be found in the Form Meta menu, under the Share Record heading.
(If the record is not a Collection Object or the Collection Object does not have a Catalog Number, then the main /view/ url will be used)

https://github.com/specify/specify7/assets/64045831/8c905eb9-cb6d-475e-ac17-d133e717d3f6

**Review by melton-jason — CHANGES_REQUESTED** [review]
There seems to a bug causing the page to reload infinitely when navigating to the Collection Object record from another collection. 
   
https://github.com/specify/specify7/assets/64045831/c2fa2ff2-aef1-4bb9-bbd7-6f643c4a70d2

**Review by bronwyncombs — APPROVED** [review]
URL to CO now successfully switches to the proper collection! 

https://github.com/specify/specify7/assets/135047322/d5f7eb81-2aaf-41ae-861d-cd66641d180e

A log in page is still the behavior for URLs to non-CO records:

Screenshot 2023-10-02 at 10 47 40 AM

**Comment by melton-jason** [comment]
> There seems to a bug causing the page to reload infinitely when navigating to the Collection Object record from another collection.
> 
>  infinite_reload.mp4

https://github.com/specify/specify7/pull/3452#pullrequestreview-1481688576

This behavior still occurs for me when running and accessing Specify locally, which leads me to believe the problem here may be related to localhost and CORS. 
@specify/dev-testing can this behavior be reproduced? 

The bycatalog url _is_ working fine when accessing Specify instances _not_ being hosted locally.

**Comment by CarolineDenis** [comment]
> > There seems to a bug causing the page to reload infinitely when navigating to the Collection Object record from another collection.
> > infinite_reload.mp4
> 
> [#3452 (review)](https://github.com/specify/specify7/pull/3452#pullrequestreview-1481688576)
> 
> This behavior still occurs for me when running and accessing Specify locally, which leads me to believe the problem here may be related to localhost and CORS. @specify/dev-testing can this behavior be reproduced?
> 
> The bycatalog url _is_ working fine when accessing Specify instances _not_ being hosted locally.

works for me on localhost

**Comment by realVinayak** [comment]
CORS is just for that, cross origin (so different domain names). Not the case here.

**Review by melton-jason — APPROVED** [review]
Given my issue was not reproducible, I will approve this.

In case this issue arises again, here is some helpful information.
I was able to consistently recreate the problem with the following:

**Operating System**
64-bit Ubuntu - 22.04.3 LTS
(With GNOME - 42.9)


**Browser**
Google Chrome - 117.0.5938.88 

Using the following extensions:

JSON Formatter - 0.7.1
React Developer Tools - 4.28.4

**Comment by realVinayak** [comment]
Can replicate the infinite re-render locally

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-2-release-announcement/1452/1

**Pull request merged**
