### PR TITLE
Fixes check promise not being resolved

### PR DESCRIPTION
**Pull request by realVinayak**
The check promise being resolved was skipped in https://github.com/specify/specify7/pull/3792

I saw this the first time that https://github.com/specify/specify7/pull/3792 was created, left a comment, but forgot to publish my review (that's why the comment date is July 17 lol, the day PR was created) - https://github.com/specify/specify7/pull/3792#pullrequestreview-1532983932

### CODE REVIEW

**Comment by realVinayak** [comment]
Let's put all business rule changes in single branch. Still have separate branches, merge all into one, which then gets merged in `v7.9-dev`. Bugs due to conflicting code will be more apparent

**Review by grantfitzsimmons — APPROVED** [review]
Promise is being resolved. @specify/dev-testing should really take a close look at this

**Comment by realVinayak** [comment]
`I am unsure why this behavior had not appeared earlier in v7.9-dev.`

Because this happened after https://github.com/specify/specify7/pull/3792 was merged, not too long ago.

**Comment by realVinayak** [comment]
> but it had no effect on either the failing tests or the behavior of Specify.

Not sure about failing tests, but it currently does behavior of Specify -- no other relevant changes have been made to `v7.9-dev` yet, after `fix-busrule-tests` was merged, and the incorrect behavior can be replicated.

**Review by acwhite211 — APPROVED** [review]

**Pull request merged**
