### PR TITLE
Fix warnings blocking save

### PR DESCRIPTION
**Pull request by realVinayak**

### CODE REVIEW

**Review by melton-jason — APPROVED** [review]
Nice catch!

**Review by maxxxxxdlp — APPROVED** [review]
ups, I meant to implement this part, but I must have confused in my mind what was implemented with what I though should be implemented

**Review by CarolineDenis — APPROVED** [review]

**Comment by carlosmbe** [comment]
UX Testing Instructions would be greatly appreciated. UwU

**Comment by CarolineDenis** [comment]
> UX Testing Instructions would be greatly appreciated. UwU

once you received more details for testing this PR could you also test if it fixes this issue: https://github.com/specify/specify7/issues/3708
Thanks!

**Review by pashiav — APPROVED** [review]
https://github.com/specify/specify7/assets/118556884/02c1c2dc-b689-4a96-83a7-3945d745312d

Allows Save, looks good!

**Review by grantfitzsimmons — APPROVED** [review]

**Comment by grantfitzsimmons** [comment]
I would very much like to see a summary of these warnings.

**Pull request merged**
