### PR TITLE
Reorder relative dates

### PR DESCRIPTION
**Pull request by grantfitzsimmons**
Solves #3406

### CODE REVIEW

**Review by maxxxxxdlp — APPROVED** [review]
Code looks good. But before we merge this, @CarolineDenis can you take a look at making the order of the 3 boxes be customizable by translators?

See example usage at https://github.com/specify/specify7/blob/51ea5579edffeb1c36edb93612efe140f5046c98/specifyweb/frontend/js_src/lib/components/AppResources/Aside.tsx#L227-L235 and https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/localization/README.md#syntax-for-string-parameters-and-plurals

**Comment by grantfitzsimmons** [comment]
> Code looks good. But before we merge this, @CarolineDenis can you take a look at making the order of the 3 boxes be customizable by translators?

Since we would like to release in the next day or so, can we spin this off into another issue if @CarolineDenis does not have time before release?

**Comment by CarolineDenis** [comment]
> > Code looks good. But before we merge this, @CarolineDenis can you take a look at making the order of the 3 boxes be customizable by translators?
> 
> Since we would like to release in the next day or so, can we spin this off into another issue if @CarolineDenis does not have time before release?

yes let's do that

**Comment by grantfitzsimmons** [comment]
Resolve in https://github.com/specify/specify7/issues/3421

**Pull request merged**
