### PR TITLE
Allow customizing delimiters in InteractionDialog

### LINKED ISSUE #2166: Cannot create a loan from preparations if catalogNumber has a space character in it
https://user-images.githubusercontent.com/37256050/190781948-61849044-b4d1-429d-80b7-2cbab2cec337.mov

https://anfc-v772.test.specifysystems.org/specify/view/collectionobject/3/

catalogNumber: 
`287 Hel sp B (Indian Ocean) 01`

user: `pae008`
db: `ANFC`

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #2166

Added user preferences:
Screen Shot 2022-09-20 at 12 31 29

The default values should leave the previous behavior unchanged, but allow fixing issues like #2166

### CODE REVIEW

**Comment by maxxxxxdlp** [comment]
As part of the review, please also check if the labels and descriptions for newly added user preferences make sense, or if they need to be adjusted

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
chrome_2ZsmKRzMnT

The entire string gets pulled apart!

My configuration:
image

user: `pae008`
db: `ANFC`

**Comment by grantfitzsimmons** [comment]
ANFC's working after customizing the delimiter and not using spaces. Awesome fix!

**Review by grantfitzsimmons — APPROVED** [review]

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1

**Pull request merged**
