### PR TITLE
Display aggregator/formatter label in schema config

### LINKED ISSUE #4797: Table formats and aggregation using title instead of name
**Describe the bug**
The table formats and table aggregation are trying to use the title which then makes it show up with `(current, invalid value)`

**To Reproduce**

1. Go to table formats/aggregation through schema config 
2. Select any table
3. Make the title and name different values 

**Expected behavior**
The schema should use the name

**Screenshots**

https://github.com/specify/specify7/assets/150940840/106e2168-7cca-4c59-9745-f1e4569afc6e

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: Spadmin
[Specify 7 System Information - 2024-04-16T19_11_18.890Z.txt](https://github.com/specify/specify7/files/15001818/Specify.7.System.Information.-.2024-04-16T19_11_18.890Z.txt)

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4797

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

Go to table formats/aggregation through schema config
Select any table
Make the title and name different values
- [ ] Verify the name of the formatter is correct

### CODE REVIEW

**Review by melton-jason — APPROVED** [review]
Nice catch! 

Looks like the Formatter and Aggregator picklists to choose the format for a table were the only places which utilized the `groups` argument of the SchemaConfig generated picklists to be an `IR<IR<string>` rather than `IR<RA<readonly [string, string]>>`

https://github.com/specify/specify7/blob/e0f1234513aac3e379083524f84da47e539d1f66/specifyweb/frontend/js_src/lib/components/SchemaConfig/Table.tsx#L150-L157

Because of this, they were the only places affected by this bug

**Review by melton-jason — COMMENTED** [review]
(optional) 
If you wanted to do some beneficial refactoring, you can name the elements of the tuple within the `RA` when `groups` is `IR<RA<readonly [string, string]>>`

https://github.com/specify/specify7/blob/e0f1234513aac3e379083524f84da47e539d1f66/specifyweb/frontend/js_src/lib/components/SchemaConfig/Components.tsx#L58

The first element of the tuple corresponds to the 'name' of the picklist item, and the second corresponds to the 'title' of the picklist item. 
This can be specified like: 
```ts
  readonly groups: IR<IR<string> | RA<readonly [name: string, title: string]>>;
```

The same can be done to the `values` parameter of the Values function: 
https://github.com/specify/specify7/blob/e0f1234513aac3e379083524f84da47e539d1f66/specifyweb/frontend/js_src/lib/components/SchemaConfig/Components.tsx#L113

**Review by lexiclevenger — APPROVED** [review]
- [x] Verify the name of the formatter is correct
Screenshot 2024-04-17 at 2 52 17 PM

Looks good!

**Review by pashiav — APPROVED** [review]
### Testing instructions

Go to table formats/aggregation through schema config
Select any table
Make the title and name different values
- [X] Verify the name of the formatter is correct 
---
Looks good! Name is correct.
Screen Shot 2024-04-17 at 3 01 25 PM

**Pull request merged**
