### PR TITLE
Unfold the side bar menu to current resource

### LINKED ISSUE #2494: App Resources sidebar should unfold to current resource
If you go to an app resource directly by URL, the app resource might not show the current resource.

To fix, app resources should automatically:
- Change filters to make current record visible
- Uncollapse the necessary categories in the app resources to make the current resource visible
- Scroll down in the list to have the current resource visible on the screen

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixed #2494

### CODE REVIEW

**Review by maxxxxxdlp — APPROVED** [review]

**Comment by grantfitzsimmons** [comment]
How can I test this? @CarolineDenis

**Comment by grantfitzsimmons** [comment]
That's a really cool feature! Didn't even realize this would be so handy!

**Review by grantfitzsimmons — APPROVED** [review]
Tested across several levels in the hierarchy, now collapses unnecessary headers. Really great addition!

**Comment by maxxxxxdlp** [comment]
@CarolineDenis This can be merged as soon as the failing tests are fixed

**Pull request merged**
