### PR TITLE
Support icon display by file name

### LINKED ISSUE #2074: Icon in separator does not appear
image

It appears like this with the following lines:

```
<cell type="separator" label="Collection Object" icon="sgr" colspan="14"/>
```

```
<cell type="separator" label="Collection Object" icon="sgr.png" colspan="14"/>
```

image

Also had no luck establishing an icon when using the `forClass` attribute with the table name. It autogenerated a CO rather than using the icon.

https://github.com/specify/specify7/wiki/Form-System#separator

Please let me know if i have this configured incorrectly.

browser: Chrome & Safari
version: 7.7.1

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixed #2074

### CODE REVIEW

**Review by maxxxxxdlp — APPROVED** [review]
The wiki page was also updated to mention that both name and file name are now accepted

**Comment by grantfitzsimmons** [comment]
Not much success here– am I configuring this wrong?

image

```xml
<cell type="separator" label="Speciforum Demo" icon="sgr.png" colspan="14"/>
```
---

image

```xml
<cell type="separator" label="Speciforum Demo" icon="sgr" colspan="14"/>
```
---

image

```xml
<cell type="separator" label="Speciforum Demo" icon="geolocate" colspan="14"/>
```

---

## `forClass`

This works great!

image

```xml
<cell type="separator" label="Speciforum Demo" forClass="agent" colspan="14"/>
```

https://kufishnotests-issue-2074.test.specifysystems.org/specify/view/collectionobject/new/

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
See my above comment– I may be misconfiguring this, but using the original XML from the issue post

**Review by grantfitzsimmons — APPROVED** [review]

**Comment by maxxxxxdlp** [comment]
Additional context here: front-end only displays an icon if it is defined in an icons_*.xml files.
Thus, even if you put the correct file name, it might still not be visible on a form

**Review by maxxxxxdlp — APPROVED** [review]

**Comment by grantfitzsimmons** [comment]
I added this to the GitHub wiki before approving 😁

**Pull request merged**
