### PR TITLE
Fix Tectonic tree rank deletion

### LINKED ISSUE #5381: Cannot delete new rank in the Tectonic Tree
**Describe the bug**
We cannot delete new created rank in the Tectonic Tree even when it has no nodes

**To Reproduce**

1. Open Tectonic Tree
2. Create a new rank 
3. Try to delete the rank 

image

Nodes in the Tectonic Unit tree cannot be deleted if they have children. When we added support for modifying tree ranks, we addressed cases where ranks with children were deleted by assigning the appropriate parents, provided no nodes were present at that rank. We should apply the same approach in these cases.

### PR DESCRIPTION
**Pull request by acwhite211**
Fixes #5381

Fix the problem of Tectonic tree rank deletion by adding Tectonictreedef to the TREE_MODEL in the tree_utils.py file

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions

1. Open Tectonic Tree
2. Create a new rank 
3. Try to delete the rank 
4. See that the rank is gone

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Review by sharadsw — APPROVED** [review]

**Review by pashiav — DISMISSED** [review]
### Testing instructions

1. Open Tectonic Tree
2. Create a new rank 
3. Try to delete the rank 

- [ ] 4. See that the rank is gone
---

Cannot delete rank, still looks to be the same as production.



`production`

https://github.com/user-attachments/assets/38dd61cb-d90e-442f-b25f-512eaf1293b6

`issue-5381`

https://github.com/user-attachments/assets/a909ace9-1bf4-488c-8f85-f30b54577448


https://github.com/specify/specify7/issues/5387: Also found that you can delete the root node through this pr, but it can also be done in `production`.

**Comment by acwhite211** [comment]
Looks like the new rank is still be added as the root rank, I'll fix that like we did for the Taxon tree.

**Comment by acwhite211** [comment]
Try testing again, hopefully that issue is fixed now @specify/testing

**Review by CarolineDenis — APPROVED** [review]

**Review by emenslin — APPROVED** [review]
### Testing instructions

1. Open Tectonic Tree
2. Create a new rank 
3. Try to delete the rank 

- [x]  See that the rank is gone

Looks good, can now successfully delete ranks

**Pull request merged**
