### PR TITLE
Refactor to remove conditional call to hook in DateElement

### PR DESCRIPTION
**Pull request by realVinayak**
Can't call hooks conditionally

### CODE REVIEW

**Review by grantfitzsimmons — APPROVED** [review]
https://fwri6123-issue-4087.test.specifysystems.org/specify/overlay/about/

image

**Review by CarolineDenis — APPROVED** [review]

**Review by maxxxxxdlp — APPROVED** [review]
ESLint can catch bugs like that
I will clean up our config soon (remove rules that don't provide enough value), and then make the other rules mandatory

**Comment by realVinayak** [comment]
I got an ESLint error in my IDE when I opened this file! Definitely nice to have it configured. @CarolineDenis

**Comment by CarolineDenis** [comment]
@realVinayak @grantfitzsimmons can this be merged?

**Comment by realVinayak** [comment]
> @realVinayak @grantfitzsimmons can this be merged?

Yes!

**Pull request merged**
