### PR TITLE
Restore past behavior for rank tree picklists

### LINKED ISSUE #4664: Match previous behavior with filling ranks when adding tree items
OK, so ..

We had [this issue](https://github.com/specify/specify7/issues/3597) fixed by [this PR](https://github.com/specify/specify7/pull/4273) for `7.9.3`

Behavior was changed with [this PR](https://github.com/specify/specify7/pull/4659) for `7.9.4` 

In recording, **`edge` on right, `7.9.3.1` on left:**

https://github.com/specify/specify7/assets/135047322/9a114906-80f9-4b30-ac0b-6387a3f51c66

Please revert to behavior in `7.9.3.1` for the user's sake and consistency

I don't think we have enough information about UX and practicality of this feature to justify the inconsistency between versions

**To Reproduce**

1. Go to Tree
2. Click on Add Child
3. See that rank is not auto-populated, and filling it is harder for UX

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name: UMich, user HerbAdmin
- Collection name: Herbarium

### LINKED ISSUE #4666: Taxonomic Rank field displays API URL
**Describe the bug**
When viewing a Taxon record with no parent nodes (highest rank), the Taxonomic Rank field displays an API URL instead of the field being blank.

**To Reproduce**

1. Go to Taxon Tree
2. Click on the highest ranking node/node with no parents (https://fwri1924-edge.test.specifysystems.org/specify/view/taxon/12689/)
3. See the **Taxonomic Rank** field contains an API URL 

**Expected behavior**
Taxonomic Rank field should be blank if there are no parent nodes.
Behavior from **`v7.9.3`**:
expected

**Evidence**
issue

https://github.com/specify/specify7/assets/118556884/08e1c353-78f4-43c0-8ae7-fde99972f905

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `fwri_1_9_24`

### LINKED ISSUE #4676: Choosing Parent of taxon record does not auto populate Rank
**Describe the bug**
When creating a new taxon record and choosing a Parent, the Rank field does not auto populate. 
From #4462, https://github.com/specify/specify7/pull/4462#issue-2100900341:

> - wait a few seconds for the taxonomic rank to be populated 

**To Reproduce**
1. Create Taxon record (https://umherb11024-edge.test.specifysystems.org/specify/view/taxon/new/)
2. Choose a Parent (ex: Fungi)
3. Wait a few seconds and see that Rank field stays empty

**Expected behavior**
Rank field should be auto populated with the correct rank when choosing a Parent.
Expected behavior from `v7.9` | Behavior on `edge`:

https://github.com/specify/specify7/assets/118556884/a5a8ebdf-6492-405f-8ac6-ae7b869e1c12

OS: macOS Ventura (13.2.1)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `umherb_1_10_24`

### PR DESCRIPTION
**Pull request by melton-jason**
Fixes #4664 
Fixes #4666 
Fixes #4676

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

For any Tree (Taxon, Geography, Storage, Chronostrat, Lithostrat) 
- [ ] In the TreeViewer, ensure the correct rank populates into the rank picklist when editing/viewing a tree record
- [ ] When using the `Add Child` functionality, ensure the rank picklist is not blank and has the correct options available for ranks
- [ ] When setting the parent of a new Tree Record, the rank picklist should automatically populate with an acceptable rank
- [ ] The rank picklist for all trees should now be disbaled (readonly) when the tree record does not have a parent
- [ ] When viewing the root node for the tree, ensure the rank pisklist contains the correct rank

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Review by bronwyncombs — CHANGES_REQUESTED** [review]
For any Tree (Taxon, Geography, Storage, Chronostrat, Lithostrat) 
- [X] In the TreeViewer, ensure the correct rank populates into the rank picklist when editing/viewing a tree record

When editing/viewing an existing record, and click the Add button, the new record displays with the api call in the rank field. 

In `7.9.3.1`, the behavior is to make the rank field read-only until a Parent is added, and then the rank would be populated from the list.
Screenshot 2024-03-18 at 12 15 52 PM
Screenshot 2024-03-18 at 12 16 11 PM

Doing the first two steps in `edge`, the field is also not read-only, but there is no api call.
Screenshot 2024-03-18 at 12 14 13 PM

Here, the rank field remains blank even after a parent is added.

I guess the change I am requesting is to:
**In the case of data entry from the `Add` button...**
1. make the rank field read-only when no parent is added
2. make the rank field auto populate with rank once parent is added

- [X] When using the `Add Child` functionality, ensure the rank picklist is not blank and has the correct options available for ranks

Old behavior is matched, working as expected 👍

**Review by maxpatiiuk — COMMENTED** [review]
this doesn't match the way the code was made to look in this PR - https://github.com/specify/specify7/pull/4462/files

could you double check if that is intentional and if it makes a difference or not?
i.e since `items` is not loaded on first render, once it's loaded, does default value get set correctly?

**Comment by melton-jason** [comment]
> this doesn't match the way the code was made to look in this PR - https://github.com/specify/specify7/pull/4462/files
> 
> could you double check if that is intentional and if it makes a difference or not? i.e since `items` is not loaded on first render, once it's loaded, does default value get set correctly?

https://github.com/specify/specify7/pull/4665#pullrequestreview-1944945468

The goal of this PR is to return the Tree Rank picklist behavior to as it is in `v7.9.3.1`. 
https://github.com/specify/specify7/blob/v7.9.3.1/specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx

As a result, the changes in https://github.com/specify/specify7/pull/4462/files are not to be included.

**Comment by melton-jason** [comment]
> For any Tree (Taxon, Geography, Storage, Chronostrat, Lithostrat)
> 
> * [x]  In the TreeViewer, ensure the correct rank populates into the rank picklist when editing/viewing a tree record
> 
> When editing/viewing an existing record, and click the Add button, the new record displays with the api call in the rank field.
> 
> In `7.9.3.1`, the behavior is to make the rank field read-only until a Parent is added, and then the rank would be populated from the list. Screenshot 2024-03-18 at 12 15 52 PM Screenshot 2024-03-18 at 12 16 11 PM
> 
> Doing the first two steps in `edge`, the field is also not read-only, but there is no api call. Screenshot 2024-03-18 at 12 14 13 PM
> 
> Here, the rank field remains blank even after a parent is added.
> 
> I guess the change I am requesting is to: **In the case of data entry from the `Add` button...**
> 
> 1. make the rank field read-only when no parent is added
> 2. make the rank field auto populate with rank once parent is added
> 
> * [x]  When using the `Add Child` functionality, ensure the rank picklist is not blank and has the correct options available for ranks
> 
> Old behavior is matched, working as expected 👍

@specify/ux-testing the problems addressed in this comment have been addressed! 
- The rank picklist for all trees should now be disbaled (readonly) when the tree record does not have a parent
- I could not recreate the issue where the rank was not being populated into the picklist from a new tree record when a Parent was added (either via the Add button or directly through DataEntry), but please confirm this is not the case

**Review by emenslin — APPROVED** [review]
### Testing instructions

For any Tree (Taxon, Geography, Storage, Chronostrat, Lithostrat) 
- [x] In the TreeViewer, ensure the correct rank populates into the rank picklist when editing/viewing a tree record
- [x] When using the `Add Child` functionality, ensure the rank picklist is not blank and has the correct options available for ranks

Looks good!

**Comment by melton-jason** [comment]
@specify/ux-testing 
This PR also includes the fix for #4666. The testing instructions have been updated!

**Review by maxpatiiuk — APPROVED** [review]

**Review by pashiav — CHANGES_REQUESTED** [review]
### Testing instructions

For any Tree (Taxon, Geography, Storage, Chronostrat, Lithostrat) 
- [X] In the TreeViewer, ensure the correct rank populates into the rank picklist when editing/viewing a tree record
- [X] When using the `Add Child` functionality, ensure the rank picklist is not blank and has the correct options available for ranks
- [X] The rank picklist for all trees should now be disbaled (readonly) when the tree record does not have a parent
- [ ] When viewing the root node for the tree, ensure the rank pisklist contains the correct rank 

---
Looking great so far!

- [ ] _When viewing the root node for the tree, ensure the rank pisklist contains the correct rank_

The root node's Rank contains itself, but in `v7.9` it is empty. Was this intentional?
Screen Shot 2024-03-21 at 9 56 42 AM



--
Adding a new node: When Editing a node from the TreeViewer, then clicking the **Add** button, the Rank contains an API URL.

https://github.com/specify/specify7/assets/118556884/20ada546-7402-4d2c-9b59-a68f54a4f32e

In `v7.9`, the Rank is empty when adding a new node.

Screen Shot 2024-03-21 at 9 48 58 AM

--
Note: I did notice that there is a bit of a lag loading the Rank, so the API URL is still visible for a split second. In `v7.9`, there is no lag at all. 
Though, this is not a big issue to me as a user, because when I click on the Edit button in the TreeViewer, I most likely will not automatically stare at the Rank field upon click. 

https://github.com/specify/specify7/assets/118556884/f34dd79f-8101-4599-9faf-805507ece05c

**Comment by melton-jason** [comment]
> Adding a new node: When Editing a node from the TreeViewer, then clicking the Add button, the Rank contains an API URL.

Every issue should been resolved save for this. 

More specifically, the remaining problem is: 
- On a tree form which contains data in the rank picklist, click on the Add button
- The value for the rank of the previous tree record is carried over to the new tree resource

This seems to be related to changes which are not specific to the treeLevelPicklist.

**Review by emenslin — APPROVED** [review]
### Testing instructions

For any Tree (Taxon, Geography, Storage, Chronostrat, Lithostrat) 
- [x] In the TreeViewer, ensure the correct rank populates into the rank picklist when editing/viewing a tree record
- [x] When using the `Add Child` functionality, ensure the rank picklist is not blank and has the correct options available for ranks
- [x] When setting the parent of a new Tree Record, the rank picklist should automatically populate with an acceptable rank

Since we discovered the API issue is linked to something else I will approve it for these parts.

**Comment by melton-jason** [comment]
> > Adding a new node: When Editing a node from the TreeViewer, then clicking the Add button, the Rank contains an API URL.
> 
> Every issue should been resolved save for this.
> 
> More specifically, the remaining problem is:
> 
> * On a tree form which contains data in the rank picklist, click on the Add button
> * The value for the rank of the previous tree record is carried over to the new tree resource
> 
> This seems to be related to changes which are not specific to the treeLevelPicklist.

The issue is related to  the `useResourceValue` hook. 
 More specifically, it is setting the value of the new resource's `definitionItem` to that of the previous resource as a result of the `useParsers` hook. 
The specific `resource.set` occurs when setting the default values for new resources: 
https://github.com/specify/specify7/blob/37174e45c96608f30fc495cfd202470c1be94ae3/specifyweb/frontend/js_src/lib/hooks/useResourceValue.tsx#L211-L220

In the case of the `definitionItem`, the `parser.value` when using the `Add` functionality from an existing tree record is always the `definitionItem` of the previous tree record. 

When the field value is being set on the new resource, the value of `defaultParser` is {value: undefined, ...}  in `useResourceValue`, however useParser returns the parser which was used for the previous resource: {value: /api/specify/treedefitem/..., ...}.
https://github.com/specify/specify7/blob/37174e45c96608f30fc495cfd202470c1be94ae3/specifyweb/frontend/js_src/lib/hooks/useResourceValue.tsx#L65

**Review by pashiav — APPROVED** [review]
### Testing instructions

For any Tree (Taxon, Geography, Storage, Chronostrat, Lithostrat) 
- [X] In the TreeViewer, ensure the correct rank populates into the rank picklist when editing/viewing a tree record
- [X] When using the `Add Child` functionality, ensure the rank picklist is not blank and has the correct options available for ranks
- [X] When setting the parent of a new Tree Record, the rank picklist should automatically populate with an acceptable rank
- [X] The rank picklist for all trees should now be disbaled (readonly) when the tree record does not have a parent
- [X] When viewing the root node for the tree, ensure the rank pisklist contains the correct rank 

Everything is great!!!

**Review by bronwyncombs — APPROVED** [review]
1. rank field is read-only until parent is added ✅
2. rank field is auto populated once parent is added, and when using "add child" ✅

thank you jason!

Tested in Taxon and Geography:
- [X] In the TreeViewer, ensure the correct rank populates into the rank picklist when editing/viewing a tree record
- [X] When using the `Add Child` functionality, ensure the rank picklist is not blank and has the correct options available for ranks
- [X] When setting the parent of a new Tree Record, the rank picklist should automatically populate with an acceptable rank
- [X] The rank picklist for all trees should now be disbaled (readonly) when the tree record does not have a parent
- [X] When viewing the root node for the tree, ensure the rank pisklist contains the correct rank

**Review by CarolineDenis — APPROVED** [review]

**Pull request merged**
