### PR TITLE
Print icon has dark background solved.

### LINKED ISSUE #2749: Print icon has a dark background in GeoMap
image

This is in the Workbench GeoMap feature!

https://herbrbge6802-statspage.test.specifysystems.org/specify/workbench/12/

### PR DESCRIPTION
**Pull request by Rishav1707**
## This PR closes the following issue:
closes #2749 

## Changes made:
- Added the `bg:white;` property in the background of the print icon.
- Added the dark mode prefix to the print icon background.

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
Hi @Rishav1707,

Please see my commit to see the most efficient way to make this change: https://github.com/specify/specify7/pull/2763/commits/11ac4d4b1db0f5f705634d11d0711c40533a8b1a

image

Your pull request modifies a large number of files that should not be touched, as it is only necessary to modify the `extend.ts` file!

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons I belive all those files were deleted kind of because of my fault - I used characters in their names which are allowed in file names on macOS, but not allowed on Windows (like `?` and `=`) - Jason and Chanu had the same issue at one point.

I need to rename the files.

**Comment by Rishav1707** [comment]
> Hi @Rishav1707,
> 
> Please see my commit to see the most efficient way to make this change: [11ac4d4](https://github.com/specify/specify7/commit/11ac4d4b1db0f5f705634d11d0711c40533a8b1a)
> 
> image
> 
> Your pull request modifies a large number of files that should not be touched, as it is only necessary to modify the `extend.ts` file!

I haven't changed any file instead of the `extend.ts` file. When I cloned this project those files are already modified.

error

See I have only committed the `extend.ts` file but this error happens.

**Comment by grantfitzsimmons** [comment]
See Max's comment – https://github.com/specify/specify7/pull/2758#issuecomment-1375081065

**Comment by Rishav1707** [comment]
> See Max's comment – [#2758 (comment)](https://github.com/specify/specify7/pull/2758#issuecomment-1375081065)

Yaah thank you @maxxxxxdlp for your clarification regarding this issue

**Pull request closed without merging**
