### PR TITLE
Change default query export format to CSV

### LINKED ISSUE #3106: Default export delimiter is "Tab" instead of "Comma"
>Please see the attached csv that I exported from a SPECIFY query. You will notice that all of the columns from the query have been mashed into a single column, column A, on the spreadsheet.
>
> [issue_query_results.csv](https://github.com/specify/specify7/files/10911741/issue_query_results.csv)

**Contents of the exported CSV:**

```
"Catalog Number	Genus	Species	Preparations Tissue#	Tissue Source	Tissue Available	Barcode Submit?	Barcode Success?	Latitude1	Longitude1	Verbatim Locality",,,,,
"23853	Urobatis	jamaicensis	126	Muscle	1			25.3770000000	-81.7446660000	[Gulf of Mexico", ca. 59 km west on Ponce de Leon Bay, FL],,,
"24734	Urobatis	jamaicensis	946	Muscle	1			26.0381660000	-82.1500000000	[Gulf of Mexico", ca. 42 km southwest of North Naples, FL],,,
"29597	Urobatis	jamaicensis	3414	Muscle	1			25.9020000000	-81.9028330000	[Gulf of Mexico", ca. 19.7 km west of Marco Island, FL],,,
"29631	Urobatis	jamaicensis	3498	Muscle	1	1	1	26.0381660000	-82.1500000000	[Gulf of Mexico", ca. 42 km southwest of North Naples, FL],,,
"34040	Urobatis	jamaicensis	4148	Muscle	1			25.5753330000	-82.1571660000	[Gulf of Mexico", ca. 55.93 km SW of Ten Thousand Island, FL; Start 25.575333 N, -82.157166 W, End 25.550333 N, -82.150833 W]
"34685	Urobatis	jamaicensis	4293	L Pelvic	1			25.3135000000	-82.1410000000	[Gulf of Mexico ca. 95.01 km SW of Everglades City", FL; START 25.31350N -82.1410W END 25.33833330N -82.14416660W],,,,
"34685	Urobatis	jamaicensis	4294	R Pelvic	1			25.3135000000	-82.1410000000	[Gulf of Mexico ca. 95.01 km SW of Everglades City", FL; START 25.31350N -82.1410W END 25.33833330N -82.14416660W],,,,
"35239	Urobatis	jamaicensis	4332	Muscle	1			25.3135000000	-82.1410000000	[Gulf of Mexico ca. 95.01 km SW of Everglades City", FL; START 25.31350N -82.1410W END 25.33833330N -82.14416660W],,,,
"35308	Urobatis	jamaicensis	4325	R Pelvic	1	1	1	26.8118170000	-80.0458170000	[Munyon Island", south end, North Palm Beach, FL; 26.8118170N -80.0458170S],,
"36272	Urobatis	jamaicensis	4873	Muscle	1			25.7345000000	-82.0658333300	Gulf of Mexico ca. 40.00 km WSW of Ten Thousand Island", FL; START 25.73450N -82.065833330W END 25.726166670N -82.0920W],,,,
```

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #3106

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
Exporting as expected.

@chanulee1 – Can you test changing the selected delimiter and try to export with a variety of delimiters (and import them into Excel) to make sure that exporting is working well?

**Review by grantfitzsimmons — APPROVED** [review]

**Review by chanulee1 — CHANGES_REQUESTED** [review]
Tested all delimiters. Seemed to export correctly, except that exporting with the 'space' delimiter put quotations marks around certain fields, seemingly at random. Did not happen with other delimiters. Is this an issue?

image


[query_results_2023-03-08T18_09_50.449580.csv](https://github.com/specify/specify7/files/10923668/query_results_2023-03-08T18_09_50.449580.csv)

https://coldfish-issue-3106.test.specifysystems.org/specify/query/128/

**Comment by maxxxxxdlp** [comment]
It puts quotation marks around values that contain spaces to escape them. See https://stackoverflow.com/a/4617967/8584605

**Comment by chanulee1** [comment]
> This is expected
> 
> It puts quotation marks around values that contain spaces to escape them. See https://stackoverflow.com/a/4617967/8584605

I see!

**Review by chanulee1 — APPROVED** [review]

**Comment by grantfitzsimmons** [comment]
Great work @chanulee1 !

**Comment by grantfitzsimmons** [comment]
Once the failing tests are fixed, should be good to merge.

**Pull request merged**
