### PR TITLE
Fixes query builder bugs causing js render issues and autorun stat queries

### PR DESCRIPTION
**Pull request by realVinayak**

### CODE REVIEW

**Review by maxxxxxdlp — APPROVED** [review]

**Comment by grantfitzsimmons** [comment]
@realVinayak How should we test this?

**Comment by maxxxxxdlp** [comment]
1. try to run a query that has a field with incomplete mapping - the field should be filtered out instead of crash
2. clicking on a query stat, should auto-run the query, rather than require the user to click on "Query"

**Comment by realVinayak** [comment]
Yes, Max describes it perfectly. However, I've made these changes on use-dynamic-stats branch and I'd rather have this tested it on that branch.

**Comment by grantfitzsimmons** [comment]
@realVinayak If that is the case, can you close this PR and describe this on the appropraite PR?

**Pull request closed without merging**
