### PR TITLE
Keep focus on xml code and not on linter after error

### LINKED ISSUE #4753: Text cursor focus is lost when warning panel appears
**Describe the bug**
When the warning panel shows up in xml editor, the location of the text cursor is lost.

**To Reproduce**

1. Go to a form definition.
2. Go to a field and modify the name to be invalid.
3. Either wait for the warning panel to appear or press Command+Shift+M to see warning panel.
5. See that your cursor position has been removed.

**Expected behavior**
When a warning appears, the editor should not lose where your cursor is in the text.

**Screenshots**

https://github.com/specify/specify7/assets/164079735/8f5c14a6-01db-4c16-953d-0b87dab04f52

[Specify 7 System Information - 2024-04-05T20_46_40.528Z.txt](https://github.com/specify/specify7/files/14890647/Specify.7.System.Information.-.2024-04-05T20_46_40.528Z.txt)

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: fitznhmdoct2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4753

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

- Go to a form definition.
- Go to a field and modify the name to be invalid.
- Wait for the warning panel to appear 
- See that your cursor position has not been removed.

### CODE REVIEW

**Review by emenslin — APPROVED** [review]
### Testing instructions

- Go to a form definition.
- Go to a field and modify the name to be invalid.
- Wait for the warning panel to appear 
- See that your cursor position has not been removed.

Looks good! You no longer lose your cursor! 

https://github.com/specify/specify7/assets/150940840/9714d12d-cd9b-4cb8-9ca5-7fd5ef91a77b

**Review by grantfitzsimmons — APPROVED** [review]
- [X] Go to a form definition.
- [X] Go to a field and modify the name to be invalid.
- [X] Wait for the warning panel to appear
- [X] See that your cursor position has not been removed.

https://herbrbge252024-issue-4753.test.specifysystems.org/specify/resources/view-set/1/CollectionObject/CollectionObject

https://github.com/specify/specify7/assets/37256050/ae2b4d93-904d-4dca-ad2b-54bbfca98263

**Review by maxpatiiuk — APPROVED** [review]

**Comment by maxpatiiuk** [comment]
Could testers please also verify that https://github.com/specify/specify7/pull/4171 is still fixed on this branch?

**Comment by CarolineDenis** [comment]
TESTED: 
https://github.com/specify/specify7/pull/4171 is still fixed on this branch

**Pull request merged**
