### PR TITLE
wrap items in detail view in query builder 

### LINKED ISSUE #3859: Query items are not forced to the current window width
Proper behavior can be seen in `v7.8.13`

## `v7.9`
See that the items are cut off on the right and it can be scrolled
image

## `v7.8.13`
image

macOS, Firefox

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3859

### CODE REVIEW

**Review by melton-jason — APPROVED** [review]
@specify/ux-testing get testing!
This change should only effect detailed view. 
Particularly, test QueryBuilder lines on narrow screens and see how the content overflows and wraps. 
Should be compatible on all major browsers!

[tailwind docs](https://tailwindcss.com/docs/flex-wrap#wrap-normally)
[css docs](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap)

**Review by maxxxxxdlp — APPROVED** [review]

**Review by bronwyncombs — CHANGES_REQUESTED** [review]
Firefox has some issues but Chrome and Safari look good! 

https://github.com/specify/specify7/assets/135047322/fb989ea2-0b6f-4211-9d4f-5efcd3726182

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
See @bronwyncombs's message

**Comment by grantfitzsimmons** [comment]
@CarolineDenis Are you going to try and resolve this?

**Comment by CarolineDenis** [comment]
Notes: 
The issue where the line doesn't seem to take the full width when in the narrowest screen is present on Firefox but also on Chrome. This wasn't happening in 7.13 because basic view wasn't a feature yet. 
Basic view changed the way the divs are organized.

**Comment by grantfitzsimmons** [comment]
The issue that @bronwyncombs demonstrated is not in basic view– are we going to try and resolve that?

**Comment by CarolineDenis** [comment]
NOTES: 
Met with @grantfitzsimmons, decision: 
==> hide up and down arrows only for narrow screen when in detailed view. 
Still present in all other screen sizes and always present for basic view

**Review by maxxxxxdlp — APPROVED** [review]

**Comment by grantfitzsimmons** [comment]
@bronwyncombs found that the cut-off for small screen width may be too large– can we make it hide the up and down arrows when the screen width is smaller?

**Comment by CarolineDenis** [comment]
> @bronwyncombs found that the cut-off for small screen width may be too large– can we make it hide the up and down arrows when the screen width is smaller?

I am not sure I get that, can I have a brief drawing on a screenshot?

**Comment by bronwyncombs** [comment]
@CarolineDenis, this is the current behavior. We just think it's removing the buttons disappear a little too early, the window should be smaller before removing buttons. The size I make the window at the end of this clip is around where I imagine the buttons would go away. 


https://github.com/specify/specify7/assets/135047322/e0b961ed-0a87-42cd-9944-90752f1e8358

Let me know if you have any questions!

**Comment by CarolineDenis** [comment]
> @CarolineDenis, this is the current behavior. We just think it's removing the buttons disappear a little too early, the window should be smaller before removing buttons. The size I make the window at the end of this clip is around where I imagine the buttons would go away.
> 
>  Screen.Recording.2023-08-04.at.3.56.37.PM.mov 
> 
> Let me know if you have any questions!

got it thanks

**Comment by CarolineDenis** [comment]
There is a slight difference with what I just pushed but we might want to hard code a pixel break point and hide only when hit?

**Comment by maxxxxxdlp** [comment]
> There is a slight difference with what I just pushed but we might want to hard code a pixel break point and hide only when hit?

I would prefer to not hardcode an arbitrary value, but if you really have to, here is the way to:

https://github.com/tailwindlabs/tailwindcss/discussions/8261#discussioncomment-3251527

**Comment by bronwyncombs** [comment]
Right now, when the up and down arrows disappear, the bottom row functions (Reveal Hidden Form Fields, Distinct, Count, and Query) are moved down the page quite a bit. 

https://github.com/specify/specify7/assets/135047322/72fe1e50-700f-4e3c-bfbf-4807f5592c70

**Review by bronwyncombs — CHANGES_REQUESTED** [review]
Browsers left to right: Chrome, Safari, Firefox (all in smallest size)

- Chrome and Safari still have the blank space between the builder and results. Button alignment is good, though.
- Firefox still causes buttons to misalign with small window. It also gets much smaller than the others so the Query button shifts to a row below the other functions. 
- As for when the up/down buttons disappear, it seems fine, but I'll leave that call to @grantfitzsimmons 

https://github.com/specify/specify7/assets/135047322/6b72416a-970a-474e-9c32-3b6e2851ea3e

up/down buttons:

https://github.com/specify/specify7/assets/135047322/9da732b2-bf34-4a39-bb16-44a87b9c49d5

**Comment by CarolineDenis** [comment]
NOTES: I cannot reproduce=> Firefox still causes buttons to misalign with small window. It also gets much smaller than the others so the Query button shifts to a row below the other functions.

**Review by maxxxxxdlp — APPROVED** [review]

**Review by bronwyncombs — CHANGES_REQUESTED** [review]
Blank space between mapper and results is fixed! 

Part of the problem: Firefox allows the window to get smaller than our longer field names (i.e. Collecting Event Attachments, Reference Work Attachments) which causes the staggered button appearance. I'm not sure how we would want work around that. 

https://github.com/specify/specify7/assets/135047322/389436f8-df3c-4e8d-93fd-7eb3b91b5ba0

**Comment by CarolineDenis** [comment]
I can add an overflow-scroll @melton-jason @bronwyncombs here is an example: 

https://github.com/specify/specify7/assets/108160931/cf03643e-54cb-4efb-ad6f-353a00374c97

**Comment by CarolineDenis** [comment]
@bronwyncombs, just pushed the code with the overflow for you to try :)

**Review by bronwyncombs — APPROVED** [review]
Overflow scroll looks good to me! Thank you for this solution! 😄 

https://github.com/specify/specify7/assets/135047322/3d1d26da-a757-4190-992a-86ada1f1da46

**Review by maxxxxxdlp — CHANGES_REQUESTED** [review]
`overflow-scroll` should almost never be used
prefer `overflow-auto` instead

`overflow-scroll` forced the scrollbars to be present even if content is not overflowing - the only case when that's desirable is if content size changes, and you want to prevent the content shift from scrollbar appearing/disapearing dynamically - though even that can be fixed better by using a [scrollbar-gutter](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter)

see also more info on the issue - https://kilianvalkhof.com/2021/css-html/you-want-overflow-auto-not-overflow-scroll/

the reason scrollbar wasn't visible on the screen recordings posted in the last few comments is that recent versions of chrome make scrollbars invisible when not in use - but that behavior is not the case for all browsers on all systems, and can be customized by the user.

**Pull request merged**
