### PR TITLE
(v7.9) Agent Merging, Statistics, Business Rules

### PR DESCRIPTION
**Pull request by melton-jason**

### CODE REVIEW

**Comment by CarolineDenis** [comment]
Search doesn't work in tree for adding a new node: 
- click on a node 
- select add child
- enter name
- try to enter the parent Geo 
- see pop up errors 
Screenshot 2023-06-21 at 11 36 23 AM
Screenshot 2023-06-21 at 11 36 11 AM

**Comment by maxxxxxdlp** [comment]
@melton-jason how does v7.9-dev differ from xml-editing?

**Comment by melton-jason** [comment]
> @melton-jason how does v7.9-dev differ from xml-editing?

@maxxxxxdlp 
The difference with this branch and `xml-editor` is that this branch only includes `agent-merging`, `use_dynamic_ranks`, and the tag `v7.8.12`. 
That is, it does not include the xml-editing features, nor the `xml-editor` branch. 

The reasoning behind this is that we had alluded/told people that Agent Merging and Statspage would be released sometime in June. It's also clear (or at the very least seems very apparent) from the community that these features are in a high demand. 

Releasing `xml-editor` by the end of June seems unfeasible: the branch has not been thoroughly tested, and even before comprehensive testing there are still a handful of bugs to iron out (The one's that i'm aware of: the saveBlocked dialog can not appear from save blockers, cell value parsing, a bug from business rules caused by changes to the collection api, and complex formatter support on the backend).  

On the other hand, there has been much more testing on `agent-merging`,  `use_dynamic_ranks`, and `v7.8.12`. 
I'm aware you made some changes to `agent-merging` on the `xml-editor` branch related to user experience (such as opening a merged subview when there is a save blocker).Though I am loathe to potentially release agent merging without these features, I know the merging tool was functional on the `agent-merging` branch. 
Given the features for agent merging on `xml-editor` seem to be related to user experience related (though still very important!),  I would be _ok_ shipping them in the next release, v7.9.2 if they can not be cherry-picked over. 
There are also a plethora of currently open pull requests which are targeted to be merged into `xml-editor`. There is a dilemma regarding these pull requests: we would preferably like to stop merging pull requests while the branch is being tested. 

A downside of this approach are the ever-present merge conflicts of course. It was quite a pain to merge the base branches, and I understand this pain will inevitably only grow. However, I figured it would take less time to resolve the merge conflicts (and potentially resolve the bugs caused by merging) begin testing and fix bugs, than it would take to resolve the pull requests targeted to `xml-editor`, fix the known bugs, begin testing, and fix the bugs found while testing. 

I can provide anymore details if necessary and I would greatly appreciate your feedback on this. 
And thank you for continuing dedication to Specify! Your contributions (including feedback) have been, and are, always outstanding.

**Comment by grantfitzsimmons** [comment]
@melton-jason 

> The difference with this branch and `xml-editor` is that this branch only includes `agent-merging`, `use_dynamic_ranks`, and the tag `v7.8.12`.
> That is, it does not include the xml-editing features, nor the `xml-editor` branch.

I was under the impression there were features in `xml-editor` that are necessary for `agent-merging`– am I mistaken? 
I do understand your thought process and why this decision was made.

**Comment by melton-jason** [comment]
> @melton-jason
> 
> > The difference with this branch and `xml-editor` is that this branch only includes `agent-merging`, `use_dynamic_ranks`, and the tag `v7.8.12`.
> > That is, it does not include the xml-editing features, nor the `xml-editor` branch.
> 
> I was under the impression there were features in `xml-editor` that are necessary for `agent-merging`– am I mistaken? I do understand your thought process and why this decision was made.

By necessary, I mean vital for the functionality of the tool. 
Strictly regarding the functionality, there are only two known cases where the merge can not be performed and throws an error:
- When multiple of the agents we are merging is referenced in a records -to-many relationship (https://github.com/specify/specify7/pull/3474#issuecomment-1552195207)
- One of the other Agents includes the agent we are trying to merge as a member, thus making the newly merged agent a member of itself

As far as I know, these have not yet been addressed on `xml-editor`, and can be addressed here if time permits. 
Correct me if I'm wrong, but most of Max's work done on agent-merging on `xml-editor` is to have better UX alerting the user when a merge can not take place. This exists on agent-merging, but to a limited capability. 

This decision is definitely not set in stone and is up for discussion--as long as time allows and demand for these features-even in it's current basic implementation- is high; two metrics I am probably not qualified for or have enough information to measure.

**Comment by mpitblado** [comment]
I do not wish to clutter this PR with non-technical comments, however I feel compelled to lend support to @melton-jason's suggestion that demand for this feature is high. While I can only speak on behalf of one of the smaller museums in the consortium, I am actively following this PR due to how useful this feature will be, and wish to begin using it as soon as it is in production. While anecdotal, perhaps there are other museums in a similar place.

**Comment by maxxxxxdlp** [comment]
@melton-jason you made a difficult decision, but I trust you made the best choice.
My big regret is only that I forced you (Specify) into such a situation where you (Jason) need to make a difficult decision like this.

**Pull request merged**
