### PR TITLE
address of record should not be a dependent relationship.

### PR DESCRIPTION
**Pull request by benanhalt**
for #2006 

Changes all relationships to addressOfRecord to independent.

### CODE REVIEW

**Comment by melton-jason** [comment]
## Specify 7
The subview for AdressOfRecord now shows on the Borrow form, but it is not allowing any data to be added (see attached picture below)

sp7_subview

For something of a workaround, I _was_ able to use a Query Combo Box's add feature to create an Address of Record related to the Borrow, but Address of Record is not defined in Specify 6's `/config/backstop/typesearch_def.xml` so no existing Address of Records can be related with this way. 

XML used for Subview:
`<cell type="subview" id="aor" name="addressOfRecord" viewname="AddressOfRecord" colspan="10"/>`

XML used for Query Combo Box:
`<cell type="label" labelfor="aor1"/>`
`<cell type="field" id="aor1" name="addressOfRecord" uitype="querycbx" initialize="name=AdressOfRecord"/>`

### Notes
If both the Query Combo Box and Subview are on the same form, whenever an Address of Record is created from the QueryComboBox, it populates data in the Address of Record Subview as read-only. (See Below)

sp7_combo_and_subview


## Specify 6
The behavior in Specify 6 is quite different.  The  Address of Record subview works as intended, with no issues. When trying to use a Query Combo Box, Specify throws an error (stating that Address of Record is not in `typesearch_def.xml`) and does not show the Borrow form.

**Review by melton-jason — COMMENTED** [review]
## Specify 7
The subview for AdressOfRecord now shows on the Borrow form, but it is not allowing any data to be added (see attached picture below)

sp7_subview

For something of a workaround, I _was_ able to use a Query Combo Box's add feature to create an Address of Record related to the Borrow, but Address of Record is not defined in Specify 6's `/config/backstop/typesearch_def.xml` so no existing Address of Records can be related with this way. 

XML used for Subview:
`<cell type="subview" id="aor" name="addressOfRecord" viewname="AddressOfRecord" colspan="10"/>`

XML used for Query Combo Box:
`<cell type="label" labelfor="aor1"/>`
`<cell type="field" id="aor1" name="addressOfRecord" uitype="querycbx" initialize="name=AdressOfRecord"/>`

### Notes
If both the Query Combo Box and Subview are on the same form, whenever an Address of Record is created from the QueryComboBox, it populates data in the Address of Record Subview as read-only. (See Below)

sp7_combo_and_subview


## Specify 6
The behavior in Specify 6 is quite different.  The  Address of Record subview works as intended  (Seem to be only able to relate 1 Address of Record ).  When trying to use a Query Combo Box, Specify throws an error (stating that Address of Record is not in `typesearch_def.xml`) and does not show the Borrow form.

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
See @melton-jason's breakdown

**Comment by maxxxxxdlp** [comment]
@benanhalt Why does the subview work in Specify 6? How does it handle rendering subviews for independent relationships?

**Comment by benanhalt** [comment]
It's probably treating it as a one-to-one.

**Comment by maxxxxxdlp** [comment]
Looks good to me.

Since the relationship is now independent, it is not supposed to be used as a SubView. Instead, it should be rendered as a query combo box.

For the sp6 error, the user will have to add an entry to the `TypeSearches` app resource.

**Comment by melton-jason** [comment]
@grantfitzsimmons @maxxxxxdlp 
After doing some digging, it seems like a plethora of other files would need to be edited as well to allow AddressOfRecord be used as a query combo box. The files for Specify 6 seemed to have been created with the intention that AddressOfRecord would not be a query combo box. 

Aside from the query combo box being added to the views.xml, here is a list of other files I have found that would (most likely) need to be edited:
* Located in "Specify/config/backstop/"
  * typesearch_def.xml
  * search.views.xml
  * search_config.xml
  * dialog_defs.xml

* Located in "Specify/config/"
  * (possibly) specify_tableid_listing.xml

I have attempted editing, with the goal of adding AddressOfRecord as a query combo box, these files but have had no luck in Specify 6.  If needed, I can provide the changes I have tried.

### Note
The behavior does change when AddressOfRecord is added to typesearch_def.xml. An error message is shown (attached below) and the form loads, but does not load the query combo box. 

Screenshot 2022-09-21 170154

I have narrowed the problem in the source code of Specify 6 to an error being thrown in `src/edu/ku/brc/af/ui/forms/validation/ValComboBoxFromQuery` (line 216) stating a variable in `src/edu/ku/brc/af/core/db/DBTableInfo` (public facing getter for variable is on line 230) is null. 

The only reference I have found of this variable in the xml forms is in `specify_tableid_listing.xml`

**Comment by maxxxxxdlp** [comment]
> It's probably treating it as a one-to-one.

Can we do the same in Specify 7?

Or is sp6 behaving that way just because it has ugly exceptions for arbituary fields?

**Comment by benanhalt** [comment]
If I set it back to a dependent relationship, that makes it a one-to-one and it should be embeddable as a subview. But it seems like that wasn't working for some reason? Or maybe we just thought it should be shared?

**Comment by maxxxxxdlp** [comment]
I have it working now on #2201 (with dependent relationship). Should be compatible with Sp6.

@benanhalt A reverse relationship must exist for subview to be able to display it (Because of collectionApi.js requiring that). See https://github.com/specify/specify7/issues/2006#issuecomment-1245587592 for more detail

I fixed that in that PR by creating the missing relationship on the front-end: https://github.com/specify/specify7/pull/2201/files#diff-456bc7bb48b232db3a3d29dd34e9381c4bbfb0d78054544402c5b110998907e3R332

Do you want to declare it on the back-end instead?

**Comment by benanhalt** [comment]
I think #2201 is the correct way to handle it. It could be added to the backend, but it would just be an override like you did in the frontend. By rights, it should be declared in the Specify 6 Hibernate annotations. Then it would be included in the specify_datamodel.xml and thence the Specify 7 datamodel.

**Pull request closed without merging**
