### PR TITLE
Disambiguate global prefs on the app resources sidebar

### LINKED ISSUE #2430: Preferences need to be uniquely identified by name
image

I know we have discussed this several times before, but I could not find an issue for this.

**Requested By:** @acbentley and myself

_Even if a UI is on the way, can this be resolved sooner? It is impossible to tell the difference until they are opened._

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #2430

### CODE REVIEW

**Comment by melton-jason** [comment]
Whenever I try to add a new AppResource, I get the following error:

pull_2726_issue

Replicated in `newmexico`, `pripaleo`, and a local instance

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
jason is mad

**Comment by maxxxxxdlp** [comment]
This is actually a bug from production. Added in 7.8.2. Fixed here. Would recommend merging this in as soon as possible

**Comment by maxxxxxdlp** [comment]
Fixed, for good.

I also made typescript detect this type of bug so in the future it should never happen again

**Pull request merged**
