### PR TITLE
Don't set unload protect for new tree records 

### LINKED ISSUE #4856: Creating new tree-related records triggers unload protect
**Describe the bug**
Leaving a new record associated with a tree (such as Taxon, Storage, Geography) without editing it triggers unload protect.

**To Reproduce**

1. Go to Data Entry
2. Create a new Taxon/Storage/Geography record
3. Try to leave newly created record without editing it

**Expected behavior**
Unload protect should not occur unless a user edits the record.

**Screenshots**

https://github.com/specify/specify7/assets/164079735/738f0fc1-1f1a-4aaf-aeb8-404763c7a0f8

https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/taxon/new/

**Crash Report**

If the bug resulted in an error message, please click on "Download Error
Message" and attach it here

[Specify 7 System Information - 2024-04-29T19_44_26.831Z.txt](https://github.com/specify/specify7/files/15154134/Specify.7.System.Information.-.2024-04-29T19_44_26.831Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: Fitz_NHMA_Oct_2023
- Collection name: NHMA Vertebrate
- User Name: petrifiedroadkill

### PR DESCRIPTION
**Pull request by melton-jason**
Fixes #4856 

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

Currently, it is known that unload protect is still triggered specifically when using the `Add Child` functionality on a tree node. 

https://github.com/specify/specify7/assets/64045831/4b205aae-a347-4dba-b771-b6703175c629

@specify/ux-testing, is this behavior 'acceptable' or should that case also additionally covered? 

### Testing instructions
- Open a DataEntry form for a Tree table (Taxon, Storage, Geography, Chronostrat, or Lithostrat)
- Do not make any changes to the form and attempt to navigate away from the form
- [ ] Ensure that the Unload Protect Dialog does not appear and the user can navigate away from the form without interruption
 
Additionally, light testing can be done (following the testing instructions in https://github.com/specify/specify7/pull/4811#issue-2253172557) to ensure that no other prior tree functionality has been impacted.

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Review by emenslin — APPROVED** [review]
### Testing instructions
- Open a DataEntry form for a Tree table (Taxon, Storage, Geography, Chronostrat, or Lithostrat)
- Do not make any changes to the form and attempt to navigate away from the form
- [x] Ensure that the Unload Protect Dialog does not appear and the user can navigate away from the form without interruption
 
- [x] Additionally, light testing can be done (following the testing instructions in https://github.com/specify/specify7/pull/4811#issue-2253172557) to ensure that no other prior tree functionality has been impacted. 

Unload protect no longer triggered, looks good!

https://github.com/specify/specify7/assets/150940840/be9951bb-9319-4aca-822b-f2da8cd8adc3

**Review by Areyes42 — CHANGES_REQUESTED** [review]
**Testing instructions**

- Open a DataEntry form for a Tree table (Taxon, Storage, Geography, Chronostrat, or Lithostrat)

- Do not make any changes to the form and attempt to navigate away from the form
- [ ]  Ensure that the Unload Protect Dialog does not appear and the user can navigate away from the form without interruption
- [ ] Additionally, light testing can be done (following the testing instructions in https://github.com/specify/specify7/pull/4811#issue-2253172557) to ensure that no other prior tree functionality has been impacted.

Unload protect still activates upon the initial opening of the form; however, subsequent openings no longer trigger it.

https://github.com/specify/specify7/assets/130881183/582a85d5-490c-4f73-b716-38d42e367f7c

**Review by lexiclevenger — APPROVED** [review]
- Open a DataEntry form for a Tree table (Taxon, Storage, Geography, Chronostrat, or Lithostrat)
- Do not make any changes to the form and attempt to navigate away from the form
- [x] Ensure that the Unload Protect Dialog does not appear and the user can navigate away from the form without interruption

Looks good, no unload protect unless the records are edited! I tested using the instructions for #4811, and everything still looks good for that, too.

**Comment by melton-jason** [comment]
> **Testing instructions**
> 
> * Open a DataEntry form for a Tree table (Taxon, Storage, Geography, Chronostrat, or Lithostrat)
> * Do not make any changes to the form and attempt to navigate away from the form
> * [ ]   Ensure that the Unload Protect Dialog does not appear and the user can navigate away from the form without interruption
> * [ ]  Additionally, light testing can be done (following the testing instructions in [Don't unset rank for root level tree node #4811 (comment)](https://github.com/specify/specify7/pull/4811#issue-2253172557)) to ensure that no other prior tree functionality has been impacted.
> 
> Unload protect still activates upon the initial opening of the form; however, subsequent openings no longer trigger it.
> 
>  Screen.Recording.2024-04-30.at.11.53.50.AM.mov

https://github.com/specify/specify7/pull/4859#pullrequestreview-2032054779 

@Areyes42 

This follows under the following case mentioned in https://github.com/specify/specify7/pull/4859#issue-2271864683

> Currently, it is known that unload protect is still triggered specifically when using the `Add Child` functionality on a tree node. 
> 
> https://github.com/specify/specify7/assets/64045831/4b205aae-a347-4dba-b771-b6703175c629
> 
> @specify/ux-testing, is this behavior 'acceptable' or should that case also additionally covered? 

To provide additional context as to _why_ the unload protect is being triggered, it is because the Taxon resource is first initialized on the frontend with no rank (undefined) and because the rank is from another table (taxontreedefitem), it has to asynchronously fetch the possible ranks and set the rank with the highest rankid (lowest in the tree) into the field's value, causing the field change. 

Should this specific case be handled to not trigger unload protect when first setting the rank of a new resource?

**Review by grantfitzsimmons — APPROVED** [review]

**Pull request merged**
