### PR TITLE
Fix Login button not working for annonomous users

### LINKED ISSUE #2651: Login button does not work when acting as an anonymous user

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #2651 

### On the test panel:
1. Log in
2. Choose collection
3. Log out
4. Change password

### On a local deployment

@grantfitzsimmons could you do this part?

1. Change sp7 settings file to allow anonymous access - https://github.com/specify/specify7/blob/eb435eaca00b5715a71f2812c7683aabd026d16a/specifyweb/settings/specify_settings.py#L50
3. Test the "Login" button in the heading
4. Change sp7 settings to setup oAuth using Phantauth - just uncomment the example configuration - https://github.com/specify/specify7/blob/eb435eaca00b5715a71f2812c7683aabd026d16a/specifyweb/settings/specify_settings.py#L102-L109
5. Test the `/accounts/login/` and `/accounts/legacy_login/` pages

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
FYI I had to modify the `Dockerfile` to get this to work as well.

**Comment by maxxxxxdlp** [comment]
Ah, I forgot that you can specify that in the docker-compose.yml too

**Comment by grantfitzsimmons** [comment]
`http://localhost/accounts/legacy_login/?next=`

image

**Comment by grantfitzsimmons** [comment]
Choosing `Phantauth` gives this page:

image


Maybe intentional? Not very knowledgable on SSO configuration

**Comment by grantfitzsimmons** [comment]
Login button works for the record, so that issue is solved

**Review by grantfitzsimmons — APPROVED** [review]
works

**Pull request merged**
