### PR TITLE
7.8.12-prerelease into production

### PR DESCRIPTION
**Pull request by grantfitzsimmons**

### CODE REVIEW

**Comment by carlosmbe** [comment]
Every Pull Request included in the release:

- Change smallBtn background color when hover to saveBtn color #3543
- Fix console error when exiting query builder #3546
- Change the string in show form button depending on status #3480
- Use proper icons for paginator elements #3537
- Show quotes after auto-generated query names #3532
- Add language subheading to login screen #3531
- Improve CollectionRelationship uploads in the WorkBench #3240
- Add [inert] attribute to #root when in modal dialog #3264
- Create CSV export with only selected query rows #3476
- Change Express Search to Simple Search #3513
- Integrate Specify Network into Specify 7 #3065
- Allow to edit app resources in narrow screens #3505

**This one is technically outdated** - v7.8.11-prerelease merge into production #3508

- Add ability to customize buttons'color in preferences #3241
- Es localization #3469
- Implement skeleton loader (forms, query builder, attachment) #3334
- Allow user to have institution logo in navigation menu #3216
- Highlight interaction menu item when in interaction forms #3481

**Comment by carlosmbe** [comment]
Issue is present in 7.8.12
Dark/Light Mode Transitions Now Require Refresh #3544

**Comment by bronwyncombs** [comment]
Issue in prerelease: #3580 

It is slightly illusive in that there are several fields and workflows affected.  So far, I am able to find the bug in v7.8.11.  I have also tested this issue in other databases in both versions and have found the same results.

**Review by melton-jason — APPROVED** [review]

**Review by carlosmbe — APPROVED** [review]

**Comment by melton-jason** [comment]
Before this is merged we need to create a new tag from the v7.8.12-prelease branch

**Pull request merged**
