### PR TITLE
Add github hash and build date to the About dialog

### LINKED ISSUE #1980: Add github hash to the end of version name
Especially helpful when distinguishing which version of Specify a user is on when they are using the `edge` tag

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #1980

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
Does the Git SHA refer to the total sum of the most recent changes?

**Comment by maxxxxxdlp** [comment]
Its a git commit hash. Each change has an associated git hash

From the commit hash, you can find out what was the previous commit, and what branches is current commit present on

More info: https://www.mikestreety.co.uk/blog/the-git-commit-hash/

**Review by grantfitzsimmons — APPROVED** [review]

**Comment by grantfitzsimmons** [comment]
Do you think this will confuse for people on the current numbered release?

**Comment by maxxxxxdlp** [comment]
Why?
If they don't know what it is, they would probably just ignore it

**Pull request merged**
