### PR TITLE
Add pref to automatically have records in read-only mode, then click …

### LINKED ISSUE #2451: Add pref to automatically have records in read-only mode, then click an Edit button

### PR DESCRIPTION
**Pull request by CarolineDenis**
…an Edit button

Fixes #2451

### CODE REVIEW

**Review by maxxxxxdlp — CHANGES_REQUESTED** [review]
This feature is already half implemented on xml-editor branch.
See ReadOnlyContext on that branch. The only thing left there is to add a button to change ReadOnlyContext value - the button would likely be in ResourceView or one of the related components

**Comment by CarolineDenis** [comment]
> This feature is already half implemented on xml-editor branch.
> See ReadOnlyContext on that branch. The only thing left there is to add a button to change ReadOnlyContext value - the button would likely be in ResourceView or one of the related components

I wish I knew that before :sweat_smile:

**Comment by melton-jason** [comment]
This is good to know!
Specifically take a look in `*/Core/Contexts.tsx`. Looks like the value for ReadOnlyContext is being read by from the cache or the value provided by the ReadOnlyContext. 

The `Enable Read-Only Mode` button (to globally enable Read-Only Mode) on the Form Meta menu (look in `*/FormMeta/ReadOnlyMode.tsx`) looks like it utilizes the cache.

**Comment by CarolineDenis** [comment]
Work done in https://github.com/specify/specify7/pull/3550 to use code from xml-editor branch

**Pull request closed without merging**
