### PR TITLE
Handle case when picklist name is duplicated

### LINKED ISSUE #2285: Sp7 uses wrong PickList if same there is picklist with same name in multiple collections
Need to add `&domainfilter=true` when requesting picklists to only return results for current collection.

To Test:
Create picklist with the same name in 2 collections
Assign that pick list to a field in the schema config
Make sure each collection uses the pick list items from the pick list for that collection

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #2285

### CODE REVIEW

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
https://github.com/specify/specify7/issues/2285#issuecomment-1267574579

**Review by chanulee1 — COMMENTED** [review]
Picklists with same name but different items in different collections show items defined in their respective collections.
db: `KUBirds`

**Comment by acbentley** [comment]
KUBirds doesn't have multiple collections?

Andy

    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard<x-apple-data-detectors://9/>
Lawrence, KS, 66045-7561<x-apple-data-detectors://9/>
USA<x-apple-data-detectors://9/>

Tel: (785) 864-3863<tel:%28785%29%20864-3863>
Fax: (785) 864-5335<tel:%28785%29%20864-5335>
Email: ***@***.******@***.***>
ORCID: https://orcid.org/0000-0002-3093-1258
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V

**Review by chanulee1 — APPROVED** [review]
Picklists with same name but different items in different collections show items defined in their respective collections.
db: KUBirds

**Comment by acbentley** [comment]
I suspected so but wanted to be sure.

Andy
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard<x-apple-data-detectors://9/>
Lawrence, KS, 66045-7561<x-apple-data-detectors://9/>
USA<x-apple-data-detectors://9/>

Tel: (785) 864-3863<tel:%28785%29%20864-3863>
Fax: (785) 864-5335<tel:%28785%29%20864-5335>
Email: ***@***.******@***.***>
ORCID: https://orcid.org/0000-0002-3093-1258
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V

**Comment by chanulee1** [comment]
@acbentley There is another collection called "m" in KU alongside the "Ornithology" collection.

**Comment by acbentley** [comment]
There is only one collection in the bird database unless you are using a copy that someone has changed for testing:

***@***.***

    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard<x-apple-data-detectors://9/>
Lawrence, KS, 66045-7561<x-apple-data-detectors://9/>
USA<x-apple-data-detectors://9/>

Tel: (785) 864-3863<tel:%28785%29%20864-3863>
Fax: (785) 864-5335<tel:%28785%29%20864-5335>
Email: ***@***.******@***.***>
ORCID: https://orcid.org/0000-0002-3093-1258
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V

**Comment by maxxxxxdlp** [comment]
Yes, it was probably created by someone during testing.
I saw that `m` collection there for a while.
https://kubirds-issue-2270.test.specifysystems.org/

**Pull request merged**
