### PR TITLE
Fix Merging Status in Merging Dialog

### PR DESCRIPTION
**Pull request by melton-jason**
> > However, it will tell you success but then send a fail notification
> > https://drive.google.com/file/d/1zehhB45CYmOHkdRnEZ_vK3JtxUz90NCz/view?usp=sharing (drive for privacy)
> 
> This is a backend-related problem. The backend endoint for getting the merge status always states the merge is a success. Should be fixed if we fix that endpoint

From https://github.com/specify/specify7/pull/3864#issuecomment-1677420435

The `/merge/status/` endpoint was always returning SUCCESS for the merge status, even when it had failed. 
Since the Celery task status is not getting properly updated, I am using the `mergingstatus` attribute on the SpMerging object instead. 

TO TEST:
- Perform a merge that will fail
- The header of the dialog should show "Merge Failed" instead of "Merge Success"

### CODE REVIEW

**Review by carlosmbe — APPROVED** [review]
Works as expected. I tested it on morpaleo_2may. Merged `Specify Support` and `제발 오빠
Smith 多`. These 2 are linked to Specify User Accounts.

**Review by carlosmbe — CHANGES_REQUESTED** [review]
On success, the message is blank.

**Review by acwhite211 — APPROVED** [review]

**Review by bronwyncombs — CHANGES_REQUESTED** [review]
We should also change the button from `Cancel` to `Close` for both outcomes. It already does this for success in v7.9-dev

**Comparing succeeded message:**
Screenshot 2023-08-17 at 3 56 39 PM

**Failed message:**
Screenshot 2023-08-17 at 3 59 26 PM

**Comment by melton-jason** [comment]
> On success, the message is blank.

> We should also change the button from `Cancel` to `Close` for both outcomes. It already does this for success in v7.9-dev
> 
> **Comparing succeeded message:** Screenshot 2023-08-17 at 3 56 39 PM
> 
> **Failed message:** Screenshot 2023-08-17 at 3 59 26 PM

These issues should now be fixed!

**Review by bronwyncombs — APPROVED** [review]
Final merging dialogs accurately reflect the outcome of the merge!

Succeeded Merge:

https://github.com/specify/specify7/assets/135047322/af45a63a-b8fb-45aa-abf9-bd5433ab998b

Failed Merge: 

https://github.com/specify/specify7/assets/135047322/30528f57-954f-47e6-b736-763d35fdeae7

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
image

User is `nkosinathi`, Invertebrate Collection

https://saiabjan1023-fix-merge-status.test.specifysystems.org/specify/overlay/merge/Agent/?records=8%2C10


The button should say "Close" instead of "Cancel" if it fails.

**Comment by melton-jason** [comment]
Fixed. 
The button should now only say "Cancel" when it is in the Merging state.

**Review by bronwyncombs — APPROVED** [review]
Button reads `Close` after success: 

https://github.com/specify/specify7/assets/135047322/b084db2a-a189-40b3-9444-09371e7ec127

Button reads `Close` after fail:

https://github.com/specify/specify7/assets/135047322/d00ee9d2-026d-4f1c-bc33-24f68eaaae6d

**Comment by CarolineDenis** [comment]
> Fixed.
> The button should now only say "Cancel" when it is in the Merging state and say "Close" otherwise

has been done in: https://github.com/specify/specify7/pull/3911 too

**Review by CarolineDenis — APPROVED** [review]

**Pull request merged**
