### PR TITLE
Unify save buttons in stats 

### LINKED ISSUE #3722: Apply button color preferences to statistics page save button
**Describe the Bug**
Changing save button color in preferences has no effect on save button in stats page. Currently, the save button is still controlled by 'Secondary button color'. 

**To Reproduce**
1. Go to preferences and change button color
2. Go to statistics and click edit to show save button

**Expected behavior**
Secondary button color shouldn't apply to stats save button. Save color should apply to stats save button.

**Screenshots**
Screen Shot 2023-07-05 at 11 44 08 AM
Screen Shot 2023-07-05 at 11 43 48 AM

**Desktop:**
 - OS: macOS 
 - Browser: Chrome
 - Specify 7 Version: v7.9-dev

**Database Name:** If applicable
uoregonpaleo

**Additional context**
Database name or any other context about the problem here.

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3722

### CODE REVIEW

**Comment by melton-jason** [comment]
@specify/ux-testing 
How about the footer buttons (Clone, Close, Save) in the Stats Query Dialog? Should these be consistent with other buttons as well? 
The Clone and Save buttons are current Info buttons. 

Screenshot_2023-07-07_13-33-35

**Comment by bronwyncombs** [comment]
> @carlosmbe @bronwyncombs Please test this soon

I didn't think we could until @melton-jason has a ✔️

**Review by bronwyncombs — APPROVED** [review]
Save buttons in stats page are now synced with `Save button color` chosen in preferences. 

Edit Page and main save:
Screenshot 2023-07-12 at 11 36 12 AM

Other areas confirmed on stats: 
- Add page save
- Add new stat save

**Review by melton-jason — APPROVED** [review]
If all the buttons are consistent in the UI throughout StatsPage, then this is good now :grin:

**Pull request merged**
