### PR TITLE
FormTable enhancements

### LINKED ISSUE #290: Scrolling for formtable subviews

### LINKED ISSUE #1933: In one to many displays in grid form, add border around each record
Reported by RBGE

Their determinations are in grid format.  When they expand the determinations, the determinations records seem to bleed into each other and it can be hard to tell when one determination ends and another begins.
The image below is several determinations
image

### LINKED ISSUE #1936: If a grid view contains more than 20 items, it is truncated, but no warning that data is missing is shown
As an example - Rhododendron has 100's of child taxa. 
we've set our taxon object view to include a grid of child taxa.  
this doesn't show all the child taxa of rhododendron - just the first 20.  limiting it in this way is probably sensible - to prevent the UI being overwhelmed.  however, what's not good is that there's no indication that the data has been truncated.  - if we are going to truncate the data, its important that's flagged to the user, so that they don't erroneously thing this is all the records.  
image

==Reported By:
RBGE

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #1933
Fixes #290
Fixes #1936

### CODE REVIEW

**Review by grantfitzsimmons — COMMENTED** [review]
image

image


Content is visible to the left and right of the header. Not noticable until you have a line. Continuing to test.

**Comment by grantfitzsimmons** [comment]
image

Spacing is not symmetrical

**Comment by maxxxxxdlp** [comment]
> image
> 
> image
> 
> Content is visible to the left and right of the header. Not noticable until you have a line. Continuing to test.

Fixed

**Comment by maxxxxxdlp** [comment]
> image
> 
> Spacing is not symmetrical

Fixed

Please use the Pull Requests's "Reject" feature for things like this in the future

**Comment by grantfitzsimmons** [comment]
I've been testing this quite a bit. I am very happy with the changes introduced here.

**Review by grantfitzsimmons — APPROVED** [review]
@tlammer Could you test these changes on the `edge` deployments during the next couple days?

**Pull request merged**
