### PR TITLE
Remove stats from the menu items

### LINKED ISSUE #3405: Statistics page button still in the defaults for the navigation menu
image

It is throws a 404 message whenever you click on it, as expected.

### PR DESCRIPTION
**Pull request by grantfitzsimmons**
Fixes #3405

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
image

image

**Comment by grantfitzsimmons** [comment]
@realVinayak Can you fix the automatic tests?

**Comment by maxxxxxdlp** [comment]
Hold off for a second.
I am still investigating https://github.com/specify/specify7/issues/3405#event-9084579691 - the behavior is not what I would have expected.
Also, I am assuming you tested https://github.com/specify/specify7/issues/3405 on the `v7.8.10-prerelease` branch, and yet this pull request is based on the `production` branch, not `v7.8.10-prerelease`. Was that intentional?

**Comment by maxxxxxdlp** [comment]
Closing this in favor of https://github.com/specify/specify7/issues/3405#issuecomment-1521882181

**Pull request closed without merging**
