### PR TITLE
Fix failing frontend test

### PR DESCRIPTION
**Pull request by melton-jason**
Addresses a failing test caused by 770d58a

### CODE REVIEW

**Comment by maxxxxxdlp** [comment]
@melton-jason see https://github.com/specify/specify7/pull/3093/files#r1128124455

**Review by maxxxxxdlp — APPROVED** [review]

**Comment by maxxxxxdlp** [comment]
To test: add a field with name `locality.geography` to CollectingEvent form and make sure it doesn't throw an exception when a new Collecting Event form is opened

**Review by chanulee1 — APPROVED** [review]
Does not seem to throw an exception. However, renders field as "Loading...". Is this an issue?

image

**Comment by maxxxxxdlp** [comment]
> However, renders field as "Loading...". Is this an issue?

It's a bug. Fixed. Please test this again

**Review by chanulee1 — APPROVED** [review]
Fixed.

**Pull request merged**
