### PR TITLE
Improve error message for oversized attachments

### LINKED ISSUE #729: Check attachment file size before attempting to upload to asset server.
Currently the nginx proxy rejects uploads above a set size. The Sp 7 interface just reports this as an unknown error.

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Fixes #729

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Comment by chanulee1** [comment]
How do I test this?

**Comment by maxxxxxdlp** [comment]
Try to upload a 200mb file, and see that the error message includes:
```
    This error happened because you tried to upload a file that is larger than
    the configured server limit. Either contact your system administrator about
    increasing the limit, or try uploading a smaller file.
```

**Review by chanulee1 — CHANGES_REQUESTED** [review]
Getting this error when trying to create a 300 mb collection object attachment.

image

[Specify 7 Crash Report - 2023-03-08T20_49_46.386Z.txt](https://github.com/specify/specify7/files/10925218/Specify.7.Crash.Report.-.2023-03-08T20_49_46.386Z.txt)

**Comment by maxxxxxdlp** [comment]
I was able to replicate that (bad) error message.

Screenshot 2023-03-08 at 16 18 56


It appears to happen if the asset server run out of storage:

Screenshot 2023-03-08 at 16 18 17

And the reason the error is so bad, is that the asset server does not send proper headers in the response, which leads to chrome not allowing specify 7 to see it's response:

Screenshot 2023-03-08 at 16 19 40

Not much specify 7 can do about that, other than fixing this on the asset server side.

I am going to merge this PR and close the issue, but open another issue on the asset server's side

**Pull request merged**
